SPRINZBWIPPAZ
HPRINZBWIPPAZ
 SP09POST PostScript printer driver
 SP0AZBWIPPAZXPOST00001POST2 with added Aztec code   1117111711170000                DEVELOPER   20101118182416700 N4S     RUSSELL     20100819160843640 JP1     SAP         2000080715380250A BIN
 FO03     0.00 ZBWIPPAZCOURIER 000     SF001                         SF001                         X0
 FO03     0.00 ZBWIPPAZCOURIER 000 X   SF002                         SF002                         X0
 FO03     0.00 ZBWIPPAZCOURIER 000X    SF003                         SF003                         X0
 FO03     0.00 ZBWIPPAZCOURIER 000XX   SF004                         SF004                         X0
 FO03     0.00 ZBWIPPAZHELVE   000     SF005                         SF005                         X0
 FO03     0.00 ZBWIPPAZHELVE   000 X   SF006                         SF006                         X0
 FO03     0.00 ZBWIPPAZHELVE   000X    SF007                         SF007                         X0
 FO03     0.00 ZBWIPPAZHELVE   000XX   SF008                         SF008                         X0
 FO03     0.00 ZBWIPPAZTIMES   000     SF009                         SF009                         X0
 FO03     0.00 ZBWIPPAZTIMES   000 X   SF010                         SF010                         X0
 FO03     0.00 ZBWIPPAZTIMES   000X    SF011                         SF011                         X0
 FO03     0.00 ZBWIPPAZTIMES   000XX   SF012                         SF012                         X0
 FO06ZBWIPPAZARTNR   SBP01SBS01
 FO06ZBWIPPAZAUFNR   SBP01SBS01
 FO06ZBWIPPAZBARCLVS SBP01SBS01
 FO06ZBWIPPAZBC_C128BSBP01SBS01
 FO06ZBWIPPAZBC_CD39 SBP01SBS01
 FO06ZBWIPPAZBC_CD39CSBP01SBS01
 FO06ZBWIPPAZBC_EAN13SBP01SBS01
 FO06ZBWIPPAZBC_EAN8 SBP01SBS01
 FO06ZBWIPPAZBC_EANH SBP01SBS01
 FO06ZBWIPPAZBC_ESC  SBP00SBS00
 FO06ZBWIPPAZBC_I25  SBP01SBS01
 FO06ZBWIPPAZBC_I25C SBP01SBS01
 FO06ZBWIPPAZBC_JAN  SBP26SBS26
 FO06ZBWIPPAZBC_MSI  SBP01SBS01
 FO06ZBWIPPAZBC_MSIC SBP01SBS01
 FO06ZBWIPPAZBC_MSIC1SBP01SBS01
 FO06ZBWIPPAZBC_MSIC2SBP01SBS01
 FO06ZBWIPPAZBC_PSN5 SBP01SBS01
 FO06ZBWIPPAZBC_PSN9 SBP01SBS01
 FO06ZBWIPPAZKUNAUNR SBP01SBS01
 FO06ZBWIPPAZKUNAUPS SBP01SBS01
 FO06ZBWIPPAZMBBARC  SBP01SBS01
 FO06ZBWIPPAZMBBARC1 SBP01SBS01
 FO06ZBWIPPAZRSNUM   SBP01SBS01
 FO06ZBWIPPAZRSPOS   SBP01SBS01
 FO06ZBWIPPAZRUECKNR SBP01SBS01
 022DZBWIPPAZCOL0H 1X
 022DZBWIPPAZCOL0N 1X
 022DZBWIPPAZCOL0V 1X
 022DZBWIPPAZCOL1H 1X
 022DZBWIPPAZCOL1N 1X
 022DZBWIPPAZCOL1V 1X
 022DZBWIPPAZCOL2H 1X
 022DZBWIPPAZCOL2N 1X
 022DZBWIPPAZCOL2V 1X
 022DZBWIPPAZCOL3H 1X
 022DZBWIPPAZCOL3N 1X
 022DZBWIPPAZCOL3V 1X
 022DZBWIPPAZCOL4H 1X
 022DZBWIPPAZCOL4N 1X
 022DZBWIPPAZCOL4V 1X
 022DZBWIPPAZCOL5H 1X
 022DZBWIPPAZCOL5N 1X
 022DZBWIPPAZCOL5V 1X
 022DZBWIPPAZCOL6H 1X
 022DZBWIPPAZCOL6N 1X
 022DZBWIPPAZCOL6V 1X
 022DZBWIPPAZCOL7H 1X
 022DZBWIPPAZCOL7N 1X
 022DZBWIPPAZCOL7V 1X
 022DZBWIPPAZS0000 1X
 022DZBWIPPAZS1100 1X
 022DZBWIPPAZS1150 1X
 022DZBWIPPAZS1401 1X
 022DZBWIPPAZS1500 1X
 022DZBWIPPAZS1610 1X
 022DZBWIPPAZS1700 1X
 022DZBWIPPAZS1800 1X
 022DZBWIPPAZS4001 1X
 022DZBWIPPAZS4004 1X
 022DZBWIPPAZS8000 1X
 022DZBWIPPAZS8300 1X
 022DZBWIPPAZS8400 1X
 022DZBWIPPAZS8500 1X
 022DZBWIPPAZS8600 1X
 022DZBWIPPAZS<<<< 1X
 022DZBWIPPAZS>>>> 1X
 022DZBWIPPAZSABLD 1X
 022DZBWIPPAZSAOFF 1X
 022DZBWIPPAZSAULN 1X
 022DZBWIPPAZSBP00 1X     25
 022DZBWIPPAZSBP01 1X     2520
 022DZBWIPPAZSBP02 1
 022DZBWIPPAZSBS00 1
 022DZBWIPPAZSBS01 1X     0A
 022DZBWIPPAZSBS02 1X     2073
 022DZBWIPPAZSF001 1X     436F7572696572
 022DZBWIPPAZSF002 1X     436F75726965722D4F626C69717565
 022DZBWIPPAZSF003 1X     436F75726965722D426F6C64
 022DZBWIPPAZSF004 1X     436F75726965722D426F6C644F626C69717565
 022DZBWIPPAZSF005 1X     48656C766574696361
 022DZBWIPPAZSF006 1X     48656C7665746963612D4F626C69717565
 022DZBWIPPAZSF007 1X     48656C7665746963612D426F6C64
 022DZBWIPPAZSF008 1X     48656C7665746963612D426F6C644F626C69717565
 022DZBWIPPAZSF009 1X     54696D65732D526F6D616E
 022DZBWIPPAZSF010 1X     54696D65732D4974616C6963
 022DZBWIPPAZSF011 1X     54696D65732D426F6C64
 022DZBWIPPAZSF012 1X     54696D65732D426F6C644974616C6963
 022DZBWIPPAZSF013 1X     54696D65732D526F6D616E
 022DZBWIPPAZSF014 1X     54696D65732D4974616C6963
 022DZBWIPPAZSF015 1X     54696D65732D426F6C64
 022DZBWIPPAZSF016 1X     54696D65732D426F6C644974616C6963
 022DZBWIPPAZSOB01 1      OutputBin1
 022DZBWIPPAZSOB02 1      OutputBin2
 022DZBWIPPAZSOB03 1X
 022DZBWIPPAZSPMBS 1X
 022DZBWIPPAZSPMDU 1      PrintModeDuplex
 022DZBWIPPAZSPMFS 1X
 022DZBWIPPAZSPMSI 1      PrintModeSimplex
 022DZBWIPPAZSPMTU 1      PrintModeTumble
 022DZBWIPPAZTRY01 1X     203020536574496E70757454726179
 022DZBWIPPAZTRY02 1X     203120536574496E70757454726179
 022DZBWIPPAZTRY03 1X     203320536574496E70757454726179
 022DZBWIPPAZTRY04 1X     203220536574496E70757454726179
 022DZBWIPPAZTRYEN 1
 022DZBWIPPAZTRYME 1
 022DZBWIPPAZTRYMN 1
 022DZBWIPPAZZBW01 1      /s {bct exch ctxt /bct exch def}  def \n
 022DZBWIPPAZZBW02 1      bwippst\nbct sqrd\nbwippen\n
 022DZBWIPPAZZBW03 1      %%bct sqrd \n  /bct () def \n /s {show} def \n
 022DZBWIPPAZZDN01 1      /bcver  bcver 1 sub def\n
 022DZBWIPPAZZDN10 1      /bcver  bcver 10 sub def\n
 022DZBWIPPAZZDN50 1      /bcver  bcver 50 sub def\n
 022DZBWIPPAZZLT01 1      /bchor  bchor 1 sub def\n
 022DZBWIPPAZZLT10 1      /bchor  bchor 10 sub def\n
 022DZBWIPPAZZLT50 1      /bchor  bchor 50 sub def\n
 022DZBWIPPAZZOP01 1      /bcopt (parse) def\n
 022DZBWIPPAZZOP02 1      /bcopt (raw) def\n
 022DZBWIPPAZZPD01 1      %%PDSTEXTz\n
 022DZBWIPPAZZQR01 1      %%QRSTEXTz\n
 022DZBWIPPAZZQR02 1      %%QRETEXTz\n
 022DZBWIPPAZZRO01 1      /bcrot  bcrot 45 add def\n
 022DZBWIPPAZZRT01 1      /bchor  bchor 1 add def\n
 022DZBWIPPAZZRT10 1      /bchor  bchor 10 add def\n
 022DZBWIPPAZZRT50 1      /bchor  bchor 50 add def\n
 022DZBWIPPAZZSH01 1      %%SHIFTSz\n
 022DZBWIPPAZZSH02 1      %%SHIFTEz\n
 022DZBWIPPAZZSX01 1      /bcscx bcscx 0.1 add def\n
 022DZBWIPPAZZSX02 1      /bcscx bcscx 0.1 sub def\n
 022DZBWIPPAZZSY01 1      /bcscy bcscy 0.1 add def\n
 022DZBWIPPAZZSY02 1      /bcscy bcscy 0.1 sub def\n
 022DZBWIPPAZZUP01 1      /bcver  bcver 1 add def\n
 022DZBWIPPAZZUP10 1      /bcver  bcver 10 add def\n
 022DZBWIPPAZZUP50 1      /bcver  bcver 50 add def\n
 SP6AZBWIPPAZDINA3                           00027 0000                                     DEVELOPER   20101118182503700 N4S     SAP         20001114101909610 BIN     SAP         1998012609371040C BIN
 SP6XZBWIPPAZDINA3                                                                                                                                                                                                                                                                                   000000000
 SP6AZBWIPPAZDINA4                           00103 0000                                     DEVELOPER   20101001223205700 N4S     RUSSELL     20100819163508640 JP1     SAP         20001114101913610 BIN
 SP6XZBWIPPAZDINA4                                                                                                                                                                                                                                                                                   000000000
 SP6AZBWIPPAZDINA5                           00016 0000                                     DEVELOPER   20101118182512700 N4S     SAP         20001114101918610 BIN     SAP         1998012609375440C BIN
 SP6XZBWIPPAZDINA5                                                                                                                                                                                                                                                                                   000000000
 SP6AZBWIPPAZEXECUTIV                        00021 0000                                     DEVELOPER   20101118182519700 N4S     SAP         20001114101922610 BIN     SAP         1998012609383640C BIN
 SP6XZBWIPPAZEXECUTIV                                                                                                                                                                                                                                                                                000000000
 SP6AZBWIPPAZINCH11                          00014 0000                                     DEVELOPER   20101118182527700 N4S     SAP         20001114101927610 BIN     SAP         1998012609390440C BIN
 SP6XZBWIPPAZINCH11                                                                                                                                                                                                                                                                                  000000000
 SP6AZBWIPPAZINCH12                          00017 0000                                     DEVELOPER   20101118182535700 N4S     SAP         20001114101931610 BIN     SAP         1998012609393140C BIN
 SP6XZBWIPPAZINCH12                                                                                                                                                                                                                                                                                  000000000
 SP6AZBWIPPAZINCH2                           00018 0000                                     DEVELOPER   20101118182543700 N4S     SAP         20001114101936610 BIN     SAP         1998042117362140C BIN
 SP6XZBWIPPAZINCH2                                                                                                                                                                                                                                                                                   000000000
 SP6AZBWIPPAZINCH4                           00016 0000                                     DEVELOPER   20101118182550700 N4S     SAP         20001114101940610 BIN     SAP         1998012609395040C BIN
 SP6XZBWIPPAZINCH4                                                                                                                                                                                                                                                                                   000000000
 SP6AZBWIPPAZINCH4C                          00016 0000                                     DEVELOPER   20101118182558700 N4S     SAP         20001114101945610 BIN     SAP         1998012609401140C BIN
 SP6XZBWIPPAZINCH4C                                                                                                                                                                                                                                                                                  000000000
 SP6AZBWIPPAZINCH5                           00017 0000                                     DEVELOPER   20101118182606700 N4S     SAP         20001114101951610 BIN     SAP         1998021009544640C BIN
 SP6XZBWIPPAZINCH5                                                                                                                                                                                                                                                                                   000000000
 SP6AZBWIPPAZINCH6                           00016 0000                                     DEVELOPER   20101118182614700 N4S     SAP         20001114101959610 BIN     SAP         1998012609402740C BIN
 SP6XZBWIPPAZINCH6                                                                                                                                                                                                                                                                                   000000000
 SP6AZBWIPPAZINCH7                           00014 0000                                     DEVELOPER   20101118182621700 N4S     SAP         20001114102008610 BIN     SAP         1998012609404040C BIN
 SP6XZBWIPPAZINCH7                                                                                                                                                                                                                                                                                   000000000
 SP6AZBWIPPAZINCH8                           00013 0000                                     DEVELOPER   20101118182630700 N4S     SAP         20001114102012610 BIN     SAP         1998012609410540C BIN
 SP6XZBWIPPAZINCH8                                                                                                                                                                                                                                                                                   000000000
 SP6AZBWIPPAZLEGAL                           00023 0000                                     DEVELOPER   20101118182640700 N4S     SAP         20001114102016610 BIN     SAP         1998012609412840C BIN
 SP6XZBWIPPAZLEGAL                                                                                                                                                                                                                                                                                   000000000
 SP6AZBWIPPAZLETTER                          00023 0000                                     DEVELOPER   20101118182649700 N4S     SAP         20001114102020610 BIN     SAP         1998012609414340C BIN
 SP6XZBWIPPAZLETTER                                                                                                                                                                                                                                                                                  000000000
 SP6AZBWIPPAZLINE_21                         00013 0000                                     DEVELOPER   20101118182657700 N4S     SAP         20001114102024610 BIN     SAP         1998012609415540C BIN
 SP6XZBWIPPAZLINE_21                                                                                                                                                                                                                                                                                 000000000
 SP6AZBWIPPAZLINE_22                         00013 0000                                     DEVELOPER   20101118182704700 N4S     SAP         20001114102028610 BIN     SAP         1998012609420540C BIN
 SP6XZBWIPPAZLINE_22                                                                                                                                                                                                                                                                                 000000000
 SP6AZBWIPPAZX_44_120                        00025 0000                                     DEVELOPER   20101118182717700 N4S     SAP         1998041617185540C BIN     SAP         1996051400000040A BIN
 SP6XZBWIPPAZX_44_120        POST    Courier                                                     0600V                                                                                                                                                                                              D000000000
 SP6AZBWIPPAZX_58_170                        00024 0000                                     DEVELOPER   20101118182729700 N4S     SAP         1998041617190440C BIN     SAP         1996051400000040A BIN
 SP6XZBWIPPAZX_58_170        POST    Courier                                                     0600V                                                                                                                                                                                              D000000000
 SP6AZBWIPPAZX_65_132                        00026 0000                                     DEVELOPER   20101118182744700 N4S     SAP         1998041617191340C BIN     SAP         1996051400000040A BIN
 SP6XZBWIPPAZX_65_132        POST    Courier                                                     0600V                                                                                                                                                                                              D000000000
 SP6AZBWIPPAZX_65_200                        00027 0000                                     DEVELOPER   20101118182759700 N4S     SAP         1998111709412646A BIN     SAP
 SP6XZBWIPPAZX_65_200        POST    Courier                                                     0600V                                                                                                                                                                                              D000000000
 SP6AZBWIPPAZX_65_255                        00028 0000                                     DEVELOPER   20101118182813700 N4S     RUSSELL     20100724090927640 JP1     SAP         1998041617192040C BIN
 SP6XZBWIPPAZX_65_255        POST    Courier                                                     0600V                                                                                                                                                                                              D000000000
 SP6AZBWIPPAZX_65_80                         00026 0000                                     DEVELOPER   20101118182823700 N4S     SAP         1998041617192740C BIN     SAP         1996051400000040A BIN
 SP6XZBWIPPAZX_65_80         POST    Courier                                                     0600V                                                                                                                                                                                              D000000000
 SP6AZBWIPPAZX_90_120                        00026 0000                                     DEVELOPER   20101118182842700 N4S     SAP         1998041617193440C BIN     SAP         1996051400000040A BIN
 SP6XZBWIPPAZX_90_120        POST    Courier                                                     0600V                                                                                                                                                                                              D000000000
 SP1DDINA3           DINA3   .S0000000000SAP         1997081213394540A BIN     SAP                                   SAP
 SP1XDINA3            000000000000000000000000
 SP06001006ZBWIPPAZDINA3           CONTROL     2 \n
 SP06002072ZBWIPPAZDINA3           CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZDINA3           CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZDINA3           CONTROL                                                                         \n
 SP06001043ZBWIPPAZDINA3           ENDLINE   #this is a reference to another device type
 SP06002026ZBWIPPAZDINA3           ENDLINE   \i<POSTSCPT:DINA3:ENDLINE>
 SP06001043ZBWIPPAZDINA3           ENDPAGE   #this is a reference to another device type
 SP06002026ZBWIPPAZDINA3           ENDPAGE   \i<POSTSCPT:DINA3:ENDPAGE>
 SP06001043ZBWIPPAZDINA3           LEAVE     #this is a reference to another device type
 SP06002024ZBWIPPAZDINA3           LEAVE     \i<POSTSCPT:DINA3:LEAVE>
 SP06001043ZBWIPPAZDINA3           SETUP     #this is a reference to another device type
 SP06002026ZBWIPPAZDINA3           SETUP     \i<POSTSCPT:DINA3:SETUP>\n
 SP06003027ZBWIPPAZDINA3           SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZDINA3           SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZDINA3           SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZDINA3           SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZDINA3           SETUP
 SP1DDINA4           DINA4   .S0000000000SAP         1997081213395640A BIN     SAP                                   SAP
 SP1XDINA4            000000000000000000000000
 SP06001006ZBWIPPAZDINA4           CONTROL     7 \n
 SP06002072ZBWIPPAZDINA4           CONTROL   DEVELOPER   101001N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   100914\n
 SP06003072ZBWIPPAZDINA4           CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZDINA4           CONTROL                                                                         \n
 SP06001043ZBWIPPAZDINA4           ENDLINE   #this is a reference to another device type
 SP06002026ZBWIPPAZDINA4           ENDLINE   \i<POSTSCPT:DINA4:ENDLINE>
 SP06001043ZBWIPPAZDINA4           ENDPAGE   #this is a reference to another device type
 SP06002028ZBWIPPAZDINA4           ENDPAGE   \i<POSTSCPT:DINA4:ENDPAGE>\n
 SP06001043ZBWIPPAZDINA4           LEAVE     #this is a reference to another device type
 SP06002024ZBWIPPAZDINA4           LEAVE     \i<POSTSCPT:DINA4:LEAVE>
 SP06001026ZBWIPPAZDINA4           SETUP     \i<POSTSCPT:DINA4:SETUP>\n
 SP06002027ZBWIPPAZDINA4           SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06003027ZBWIPPAZDINA4           SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06004026ZBWIPPAZDINA4           SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06005026ZBWIPPAZDINA4           SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06001015ZBWIPPAZDINA4           STRTPAGE  %%GOTOBARCODE\n
 SP06000007ZBWIPPAZDINA4           ZBWIPP    CREDITS
 SP06001016ZBWIPPAZDINA4           ZBWIPP    ##usage: CREDITS
 SP06002036ZBWIPPAZDINA4           ZBWIPP    ##DO NOT CHANGE the first two lines!
 SP06003053ZBWIPPAZDINA4           ZBWIPP    %% SAP device type put together by Robert Russell, \n
 SP06004048ZBWIPPAZDINA4           ZBWIPP    %% send any comments to rob.roosky@yahoo.com. \n
 SP06005019ZBWIPPAZDINA4           ZBWIPP    %% 2010 RJR......\n
 SP06006009ZBWIPPAZDINA4           ZBWIPP    /ctxt {\n
 SP06007044ZBWIPPAZDINA4           ZBWIPP             2 copy length exch length add  % \n
 SP06008059ZBWIPPAZDINA4           ZBWIPP               string dup     % string1 string2 string string\n
 SP06009059ZBWIPPAZDINA4           ZBWIPP               4 2 roll       % string string string1 string2\n
 SP06010030ZBWIPPAZDINA4           ZBWIPP               2 index 0 3 index\n
 SP06011061ZBWIPPAZDINA4           ZBWIPP               % string string string1 string2 string 0 string1\n
 SP06012056ZBWIPPAZDINA4           ZBWIPP               putinterval    % stuff the first string in.\n
 SP06013044ZBWIPPAZDINA4           ZBWIPP               % string string string1 string2\n
 SP06014040ZBWIPPAZDINA4           ZBWIPP              exch length exch putinterval\n
 SP06015007ZBWIPPAZDINA4           ZBWIPP    } def\n
 SP06016072ZBWIPPAZDINA4           ZBWIPP    /sqrd {bcopt /azteccode /uk.co.terryburton.bwipp findresource exec} def\
 SP06017013ZBWIPPAZDINA4           ZBWIPP    /bct () def\n
 SP06018014ZBWIPPAZDINA4           ZBWIPP    /bchor 0 def\n
 SP06019014ZBWIPPAZDINA4           ZBWIPP    /bcver 0 def\n
 SP06020016ZBWIPPAZDINA4           ZBWIPP    /bcscx 1.0 def\n
 SP06021016ZBWIPPAZDINA4           ZBWIPP    /bcscy 1.0 def\n
 SP06022015ZBWIPPAZDINA4           ZBWIPP    /bcopt () def\n
 SP06023015ZBWIPPAZDINA4           ZBWIPP    /bcrot 0 def \n
 SP06024012ZBWIPPAZDINA4           ZBWIPP    /bwippst {\n
 SP06025007ZBWIPPAZDINA4           ZBWIPP    gsave\n
 SP06026024ZBWIPPAZDINA4           ZBWIPP    currentpoint translate\n
 SP06027019ZBWIPPAZDINA4           ZBWIPP    bcscx bcscy scale\n
 SP06028021ZBWIPPAZDINA4           ZBWIPP    bchor bcver rmoveto\n
 SP06029014ZBWIPPAZDINA4           ZBWIPP    bcrot rotate\n
 SP06030008ZBWIPPAZDINA4           ZBWIPP    } def \n
 SP06031012ZBWIPPAZDINA4           ZBWIPP    /bwippen {\n
 SP06032010ZBWIPPAZDINA4           ZBWIPP    grestore\n
 SP06033013ZBWIPPAZDINA4           ZBWIPP    /bct () def\n
 SP06034015ZBWIPPAZDINA4           ZBWIPP    /s {show} def\n
 SP06035015ZBWIPPAZDINA4           ZBWIPP    /bchor  0 def\n
 SP06036015ZBWIPPAZDINA4           ZBWIPP    /bcver  0 def\n
 SP06037017ZBWIPPAZDINA4           ZBWIPP    /bcscx  1.0 def\n
 SP06038017ZBWIPPAZDINA4           ZBWIPP    /bcscy  1.0 def\n
 SP06039015ZBWIPPAZDINA4           ZBWIPP    /bcopt () def\n
 SP06040015ZBWIPPAZDINA4           ZBWIPP    /bcrot 0 def \n
 SP06041007ZBWIPPAZDINA4           ZBWIPP    } def\n
 SP06042025ZBWIPPAZDINA4           ZBWIPP    %%Creator: Terry Burton\n
 SP06043026ZBWIPPAZDINA4           ZBWIPP    %%DocumentPaperSizes: a4\n
 SP06044015ZBWIPPAZDINA4           ZBWIPP    %%EndComments\n
 SP06045060ZBWIPPAZDINA4           ZBWIPP    % Barcode Writer in Pure PostScript - Version 2010-07-16-1\n
 SP06046047ZBWIPPAZDINA4           ZBWIPP    % http://www.terryburton.co.uk/barcodewriter/\n
 SP06047003ZBWIPPAZDINA4           ZBWIPP    %\n
 SP06048040ZBWIPPAZDINA4           ZBWIPP    % Copyright (c) 2004-2010 Terry Burton\n
 SP06049003ZBWIPPAZDINA4           ZBWIPP    %\n
 SP06050056ZBWIPPAZDINA4           ZBWIPP    % Permission is hereby granted, free of charge, to any\n
 SP06051059ZBWIPPAZDINA4           ZBWIPP    % person obtaining a copy of this software and associated\n
 SP06052056ZBWIPPAZDINA4           ZBWIPP    % documentation files (the "Software"), to deal in the\n
 SP06053051ZBWIPPAZDINA4           ZBWIPP    % Software without restriction, including without\n
 SP06054054ZBWIPPAZDINA4           ZBWIPP    % limitation the rights to use, copy, modify, merge,\n
 SP06055058ZBWIPPAZDINA4           ZBWIPP    % publish, distribute, sublicense, and/or sell copies of\n
 SP06056060ZBWIPPAZDINA4           ZBWIPP    % the Software, and to permit persons to whom the Software\n
 SP06057051ZBWIPPAZDINA4           ZBWIPP    % is furnished to do so, subject to the following\n
 SP06058015ZBWIPPAZDINA4           ZBWIPP    % conditions:\n
 SP06059003ZBWIPPAZDINA4           ZBWIPP    %\n
 SP06060057ZBWIPPAZDINA4           ZBWIPP    % The above copyright notice and this permission notice\n
 SP06061059ZBWIPPAZDINA4           ZBWIPP    % shall be included in all copies or substantial portions\n
 SP06062020ZBWIPPAZDINA4           ZBWIPP    % of the Software.\n
 SP06063003ZBWIPPAZDINA4           ZBWIPP    %\n
 SP06064061ZBWIPPAZDINA4           ZBWIPP    % THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY\n
 SP06065058ZBWIPPAZDINA4           ZBWIPP    % KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO\n
 SP06066052ZBWIPPAZDINA4           ZBWIPP    % THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A\n
 SP06067061ZBWIPPAZDINA4           ZBWIPP    % PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL\n
 SP06068061ZBWIPPAZDINA4           ZBWIPP    % THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,\n
 SP06069055ZBWIPPAZDINA4           ZBWIPP    % DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF\n
 SP06070059ZBWIPPAZDINA4           ZBWIPP    % CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\n
 SP06071061ZBWIPPAZDINA4           ZBWIPP    % CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS\n
 SP06072020ZBWIPPAZDINA4           ZBWIPP    % IN THE SOFTWARE.\n
 SP06073058ZBWIPPAZDINA4           ZBWIPP    % Uncomment this next line to allow these named resource\n
 SP06074053ZBWIPPAZDINA4           ZBWIPP    % definitions to remain resident within a printer's\n
 SP06075061ZBWIPPAZDINA4           ZBWIPP    % PostScript virtual machine so that the barcode generation\n
 SP06076037ZBWIPPAZDINA4           ZBWIPP    % capability persists between jobs.\n
 SP06077034ZBWIPPAZDINA4           ZBWIPP    % serverdict begin 0 exitserver \n
 SP06078022ZBWIPPAZDINA4           ZBWIPP    % --BEGIN TEMPLATE--\n
 SP06079022ZBWIPPAZDINA4           ZBWIPP    % --BEGIN PREAMBLE--\n
 SP06080015ZBWIPPAZDINA4           ZBWIPP    currentglobal\n
 SP06081016ZBWIPPAZDINA4           ZBWIPP    true setglobal\n
 SP06082033ZBWIPPAZDINA4           ZBWIPP    /Generic /Category findresource\n
 SP06083028ZBWIPPAZDINA4           ZBWIPP    dup length 1 add dict copy\n
 SP06084040ZBWIPPAZDINA4           ZBWIPP    dup /InstanceType /packedarraytype put\n
 SP06085060ZBWIPPAZDINA4           ZBWIPP    /uk.co.terryburton.bwipp exch /Category defineresource pop\n
 SP06086011ZBWIPPAZDINA4           ZBWIPP    setglobal\n
 SP06087020ZBWIPPAZDINA4           ZBWIPP    % --END PREAMBLE--\n
 SP06088000ZBWIPPAZDINA4           ZBWIPP
 SP06000017ZBWIPPAZDINA4           ZENC1     BWIPP encode qr 1
 SP06001026ZBWIPPAZDINA4           ZENC1     ##usage: BWIPP encode qr 1
 SP06002036ZBWIPPAZDINA4           ZENC1     ##DO NOT CHANGE the first two lines!
 SP06003059ZBWIPPAZDINA4           ZENC1     /setpacking where {pop currentpacking true setpacking} if\n
 SP06004008ZBWIPPAZDINA4           ZENC1     1 dict\n
 SP06005062ZBWIPPAZDINA4           ZENC1     dup /renmatrix dup /uk.co.terryburton.bwipp findresource put\n
 SP06006007ZBWIPPAZDINA4           ZENC1     begin\n
 SP06007014ZBWIPPAZDINA4           ZENC1     /azteccode {\n
 SP06008019ZBWIPPAZDINA4           ZENC1         20 dict begin\n
 SP06009023ZBWIPPAZDINA4           ZENC1         /options exch def\n
 SP06010023ZBWIPPAZDINA4           ZENC1         /barcode exch def\n
 SP06011025ZBWIPPAZDINA4           ZENC1         /dontdraw false def\n
 SP06012029ZBWIPPAZDINA4           ZENC1         /format (unset) def    \n
 SP06013027ZBWIPPAZDINA4           ZENC1         /readerinit false def\n
 SP06014020ZBWIPPAZDINA4           ZENC1         /layers -1 def\n
 SP06015021ZBWIPPAZDINA4           ZENC1         /eclevel 23 def\n
 SP06016023ZBWIPPAZDINA4           ZENC1         /ecaddchars 3 def\n
 SP06017020ZBWIPPAZDINA4           ZENC1         /raw false def\n
 SP06018022ZBWIPPAZDINA4           ZENC1         /parse false def\n
 SP06019006ZBWIPPAZDINA4           ZENC1         \n
 SP06020035ZBWIPPAZDINA4           ZENC1         options type /stringtype eq {\n
 SP06021022ZBWIPPAZDINA4           ZENC1             1 dict begin\n
 SP06022019ZBWIPPAZDINA4           ZENC1             options {\n
 SP06023071ZBWIPPAZDINA4           ZENC1                 token false eq {exit} if dup length string cvs (=) search\n
 SP06024071ZBWIPPAZDINA4           ZENC1                 true eq {cvlit exch pop exch def} {cvlit true def} ifelse\n
 SP06025016ZBWIPPAZDINA4           ZENC1             } loop\n
 SP06026043ZBWIPPAZDINA4           ZENC1             currentdict end /options exch def\n
 SP06027010ZBWIPPAZDINA4           ZENC1         } if\n
 SP06028026ZBWIPPAZDINA4           ZENC1         options {def} forall\n
 SP06029003ZBWIPPAZDINA4           ZENC1      \n
 SP06030028ZBWIPPAZDINA4           ZENC1         /layers layers cvi def\n
 SP06031030ZBWIPPAZDINA4           ZENC1         /eclevel eclevel cvr def\n
 SP06032036ZBWIPPAZDINA4           ZENC1         /ecaddchars ecaddchars cvi def\n
 SP06033006ZBWIPPAZDINA4           ZENC1         \n
 SP06034013ZBWIPPAZDINA4           ZENC1         parse {\n
 SP06035040ZBWIPPAZDINA4           ZENC1             /msg barcode length string def\n
 SP06036018ZBWIPPAZDINA4           ZENC1             /j 0 def\n
 SP06037017ZBWIPPAZDINA4           ZENC1             barcode\n
 SP06038012ZBWIPPAZDINA4           ZENC1             { \n
 SP06039026ZBWIPPAZDINA4           ZENC1                 (^) search {\n
 SP06040049ZBWIPPAZDINA4           ZENC1                     dup msg exch j exch putinterval\n
 SP06041048ZBWIPPAZDINA4           ZENC1                     length j add 1 add /j exch def\n
 SP06042021ZBWIPPAZDINA4           ZENC1                     pop\n
 SP06043067ZBWIPPAZDINA4           ZENC1                     dup 0 3 getinterval cvi msg exch j 1 sub exch put\n
 SP06044053ZBWIPPAZDINA4           ZENC1                     dup length 3 sub 3 exch getinterval\n
 SP06045017ZBWIPPAZDINA4           ZENC1                 } {\n
 SP06046049ZBWIPPAZDINA4           ZENC1                     dup msg exch j exch putinterval\n
 SP06047042ZBWIPPAZDINA4           ZENC1                     length j add /j exch def\n
 SP06048050ZBWIPPAZDINA4           ZENC1                     /barcode msg 0 j getinterval def\n
 SP06049022ZBWIPPAZDINA4           ZENC1                     exit\n
 SP06050023ZBWIPPAZDINA4           ZENC1                 } ifelse \n
 SP06051016ZBWIPPAZDINA4           ZENC1             } loop\n
 SP06052010ZBWIPPAZDINA4           ZENC1         } if\n
 SP06053006ZBWIPPAZDINA4           ZENC1         \n
 SP06054022ZBWIPPAZDINA4           ZENC1         /msgbits () def \n
 SP06055057ZBWIPPAZDINA4           ZENC1         format (rune) ne raw and {/msgbits barcode def} if \n
 SP06056038ZBWIPPAZDINA4           ZENC1         format (rune) ne raw not and {  \n
 SP06057010ZBWIPPAZDINA4           ZENC1             \n
 SP06058036ZBWIPPAZDINA4           ZENC1             /barlen barcode length def\n
 SP06059024ZBWIPPAZDINA4           ZENC1             barlen 31 le {\n
 SP06060062ZBWIPPAZDINA4           ZENC1                 (00000) 5 string copy dup barlen 2 5 string cvrs\n
 SP06061052ZBWIPPAZDINA4           ZENC1                 dup length 5 exch sub exch putinterval\n
 SP06062026ZBWIPPAZDINA4           ZENC1                 /cc exch def\n
 SP06063013ZBWIPPAZDINA4           ZENC1             } {\n
 SP06064071ZBWIPPAZDINA4           ZENC1                 (0000000000000000) 16 string copy dup barlen 31 sub 2 16 st
 SP06065011ZBWIPPAZDINA4           ZENC1     ring cvrs\n
 SP06066053ZBWIPPAZDINA4           ZENC1                 dup length 16 exch sub exch putinterval\n
 SP06067026ZBWIPPAZDINA4           ZENC1                 /cc exch def\n
 SP06068018ZBWIPPAZDINA4           ZENC1             } ifelse\n
 SP06069030ZBWIPPAZDINA4           ZENC1             /cclen cc length def\n
 SP06070010ZBWIPPAZDINA4           ZENC1             \n
 SP06071058ZBWIPPAZDINA4           ZENC1             /msgbits 5 cclen add barlen 8 mul add string def\n
 SP06072039ZBWIPPAZDINA4           ZENC1             msgbits 0 (11111) putinterval\n
 SP06073034ZBWIPPAZDINA4           ZENC1             msgbits 5 cc putinterval\n
 SP06074028ZBWIPPAZDINA4           ZENC1             0 1 barlen 1 sub {\n
 SP06075025ZBWIPPAZDINA4           ZENC1                 /i exch def\n
 SP06076071ZBWIPPAZDINA4           ZENC1                 (00000000) 8 string copy dup barcode i get cvi 2 8 string c
 SP06077045ZBWIPPAZDINA4           ZENC1     vrs dup length 8 exch sub exch putinterval \n
 SP06078067ZBWIPPAZDINA4           ZENC1                 msgbits 5 cclen add i 8 mul add 3 -1 roll putinterval\n
 SP06079015ZBWIPPAZDINA4           ZENC1             } for\n
 SP06080010ZBWIPPAZDINA4           ZENC1         } if\n
 SP06081006ZBWIPPAZDINA4           ZENC1         \n
 SP06082016ZBWIPPAZDINA4           ZENC1         /metrics [\n
 SP06083038ZBWIPPAZDINA4           ZENC1             [ (rune)     0 0    0  6 ]  \n
 SP06084071ZBWIPPAZDINA4           ZENC1             [ (compact)  1 1   17  6 ] [ (full)     1 1   21  6 ] [ (compac
 SP06085019ZBWIPPAZDINA4           ZENC1     t)  2 0   40  6 ]\n
 SP06086070ZBWIPPAZDINA4           ZENC1             [ (full)     2 1   48  6 ] [ (compact)  3 0   51  8 ] [ (full)
 SP06087020ZBWIPPAZDINA4           ZENC1          3 1   60  8 ]\n
 SP06088070ZBWIPPAZDINA4           ZENC1             [ (compact)  4 0   76  8 ] [ (full)     4 1   88  8 ] [ (full)
 SP06089020ZBWIPPAZDINA4           ZENC1          5 1  120  8 ]\n
 SP06090070ZBWIPPAZDINA4           ZENC1             [ (full)     6 1  156  8 ] [ (full)     7 1  196  8 ] [ (full)
 SP06091020ZBWIPPAZDINA4           ZENC1          8 1  240  8 ]\n
 SP06092070ZBWIPPAZDINA4           ZENC1             [ (full)     9 1  230 10 ] [ (full)    10 1  272 10 ] [ (full)
 SP06093020ZBWIPPAZDINA4           ZENC1         11 1  316 10 ]\n
 SP06094070ZBWIPPAZDINA4           ZENC1             [ (full)    12 1  364 10 ] [ (full)    13 1  416 10 ] [ (full)
 SP06095020ZBWIPPAZDINA4           ZENC1         14 1  470 10 ]\n
 SP06096070ZBWIPPAZDINA4           ZENC1             [ (full)    15 1  528 10 ] [ (full)    16 1  588 10 ] [ (full)
 SP06097020ZBWIPPAZDINA4           ZENC1         17 1  652 10 ]\n
 SP06098070ZBWIPPAZDINA4           ZENC1             [ (full)    18 1  720 10 ] [ (full)    19 1  790 10 ] [ (full)
 SP06099020ZBWIPPAZDINA4           ZENC1         20 1  864 10 ]\n
 SP06100070ZBWIPPAZDINA4           ZENC1             [ (full)    21 1  940 10 ] [ (full)    22 1 1020 10 ] [ (full)
 SP06101020ZBWIPPAZDINA4           ZENC1         23 0  920 12 ]\n
 SP06102070ZBWIPPAZDINA4           ZENC1             [ (full)    24 0  992 12 ] [ (full)    25 0 1066 12 ] [ (full)
 SP06103020ZBWIPPAZDINA4           ZENC1         26 0 1144 12 ]\n
 SP06104070ZBWIPPAZDINA4           ZENC1             [ (full)    27 0 1224 12 ] [ (full)    28 0 1306 12 ] [ (full)
 SP06105020ZBWIPPAZDINA4           ZENC1         29 0 1392 12 ]\n
 SP06106070ZBWIPPAZDINA4           ZENC1             [ (full)    30 0 1480 12 ] [ (full)    31 0 1570 12 ] [ (full)
 SP06107020ZBWIPPAZDINA4           ZENC1         32 0 1664 12 ]\n
 SP06108011ZBWIPPAZDINA4           ZENC1         ] def\n
 SP06109014ZBWIPPAZDINA4           ZENC1         /i 0 def\n
 SP06110008ZBWIPPAZDINA4           ZENC1         { \n
 SP06111030ZBWIPPAZDINA4           ZENC1             /m metrics i get def\n
 SP06112053ZBWIPPAZDINA4           ZENC1             /frmt m 0 get def                          \n
 SP06113053ZBWIPPAZDINA4           ZENC1             /mlyr m 1 get def                          \n
 SP06114053ZBWIPPAZDINA4           ZENC1             /icap m 2 get def                          \n
 SP06115053ZBWIPPAZDINA4           ZENC1             /ncws m 3 get def                          \n
 SP06116053ZBWIPPAZDINA4           ZENC1             /bpcw m 4 get def                          \n
 SP06117071ZBWIPPAZDINA4           ZENC1             /numecw ncws eclevel mul 100 div ecaddchars add ceiling cvi def
 SP06118002ZBWIPPAZDINA4           ZENC1     \n
 SP06119053ZBWIPPAZDINA4           ZENC1             msgbits length 0 eq {/numecw 0 def} if     \n
 SP06120053ZBWIPPAZDINA4           ZENC1             /numdcw ncws numecw sub def                \n
 SP06121024ZBWIPPAZDINA4           ZENC1             /okay true def\n
 SP06122067ZBWIPPAZDINA4           ZENC1             format (unset) ne format frmt ne and {/okay false def} if\n
 SP06123055ZBWIPPAZDINA4           ZENC1             readerinit icap 1 ne and {/okay false def} if\n
 SP06124063ZBWIPPAZDINA4           ZENC1             layers -1 ne layers mlyr ne and {/okay false def} if \n
 SP06125071ZBWIPPAZDINA4           ZENC1             msgbits length bpcw div ceiling cvi numdcw gt {/okay false def}
 SP06126005ZBWIPPAZDINA4           ZENC1      if\n
 SP06127024ZBWIPPAZDINA4           ZENC1             okay {exit} if\n
 SP06128024ZBWIPPAZDINA4           ZENC1             /i i 1 add def\n
 SP06129012ZBWIPPAZDINA4           ZENC1         } loop\n
 SP06130022ZBWIPPAZDINA4           ZENC1         /layers mlyr def\n
 SP06131022ZBWIPPAZDINA4           ZENC1         /format frmt def\n
 SP06132006ZBWIPPAZDINA4           ZENC1         \n
 SP06133071ZBWIPPAZDINA4           ZENC1         /allzero {dup length (000000000000) 0 3 -1 roll getinterval eq} bin
 SP06134007ZBWIPPAZDINA4           ZENC1     d def\n
 SP06135071ZBWIPPAZDINA4           ZENC1         /allones {dup length (111111111111) 0 3 -1 roll getinterval eq} bin
 SP06136007ZBWIPPAZDINA4           ZENC1     d def\n
 SP06137025ZBWIPPAZDINA4           ZENC1         /cws ncws array def\n
 SP06138023ZBWIPPAZDINA4           ZENC1         /m 0 def /c 0 def\n
 SP06139007ZBWIPPAZDINA4           ZENC1         {\n
 SP06140039ZBWIPPAZDINA4           ZENC1             msgbits length m le {exit} if\n
 SP06141040ZBWIPPAZDINA4           ZENC1             msgbits length m sub bpcw ge {\n
 SP06142063ZBWIPPAZDINA4           ZENC1                 /cwb msgbits m bpcw 1 sub getinterval def        \n
 SP06143063ZBWIPPAZDINA4           ZENC1                 /cwf msgbits m bpcw add 1 sub 1 getinterval def  \n
 SP06144063ZBWIPPAZDINA4           ZENC1                 cwb allzero {/cwf (1) def /m m 1 sub def} if     \n
 SP06145063ZBWIPPAZDINA4           ZENC1                 cwb allones {/cwf (0) def /m m 1 sub def} if     \n
 SP06146014ZBWIPPAZDINA4           ZENC1                 \n
 SP06147046ZBWIPPAZDINA4           ZENC1                 12 string dup 0 cwb putinterval \n
 SP06148044ZBWIPPAZDINA4           ZENC1                 dup bpcw 1 sub cwf putinterval\n
 SP06149032ZBWIPPAZDINA4           ZENC1                 0 bpcw getinterval\n
 SP06150027ZBWIPPAZDINA4           ZENC1                 /cwb exch def\n
 SP06151015ZBWIPPAZDINA4           ZENC1             } {  \n
 SP06152065ZBWIPPAZDINA4           ZENC1                 /cwb msgbits m msgbits length m sub getinterval def\n
 SP06153070ZBWIPPAZDINA4           ZENC1                 /cwb (111111111111) 12 string copy dup 0 cwb putinterval 0
 SP06154023ZBWIPPAZDINA4           ZENC1      bpcw getinterval def\n
 SP06155069ZBWIPPAZDINA4           ZENC1                 cwb allones {cwb cwb length 1 sub (0) putinterval} if  \n
 SP06156018ZBWIPPAZDINA4           ZENC1             } ifelse\n
 SP06157010ZBWIPPAZDINA4           ZENC1             \n
 SP06158019ZBWIPPAZDINA4           ZENC1             /cw 0 def\n
 SP06159026ZBWIPPAZDINA4           ZENC1             0 1 bpcw 1 sub {\n
 SP06160025ZBWIPPAZDINA4           ZENC1                 /i exch def\n
 SP06161070ZBWIPPAZDINA4           ZENC1                 /cw cw 2 bpcw i sub 1 sub exp cvi cwb i get 48 sub mul add
 SP06162006ZBWIPPAZDINA4           ZENC1      def\n
 SP06163015ZBWIPPAZDINA4           ZENC1             } for\n
 SP06164022ZBWIPPAZDINA4           ZENC1             cws c cw put\n
 SP06165028ZBWIPPAZDINA4           ZENC1             /m m bpcw add def \n
 SP06166024ZBWIPPAZDINA4           ZENC1             /c c 1 add def\n
 SP06167016ZBWIPPAZDINA4           ZENC1         } loop    \n
 SP06168034ZBWIPPAZDINA4           ZENC1         /cws cws 0 c getinterval def\n
 SP06169006ZBWIPPAZDINA4           ZENC1         \n
 SP06170016ZBWIPPAZDINA4           ZENC1         /rscodes {\n
 SP06171024ZBWIPPAZDINA4           ZENC1             /rspm exch def\n
 SP06172024ZBWIPPAZDINA4           ZENC1             /rsgf exch def\n
 SP06173024ZBWIPPAZDINA4           ZENC1             /rsnc exch def\n
 SP06174025ZBWIPPAZDINA4           ZENC1             /rscws exch def\n
 SP06175010ZBWIPPAZDINA4           ZENC1             \n
 SP06176070ZBWIPPAZDINA4           ZENC1             /rsalog [ 1 rsgf 1 sub { dup 2 mul dup rsgf ge {rspm xor} if }
 SP06177015ZBWIPPAZDINA4           ZENC1      repeat ] def\n
 SP06178031ZBWIPPAZDINA4           ZENC1             /rslog rsgf array def\n
 SP06179071ZBWIPPAZDINA4           ZENC1             1 1 rsgf 1 sub {dup rsalog exch get exch rslog 3 1 roll put} fo
 SP06180003ZBWIPPAZDINA4           ZENC1     r\n
 SP06181010ZBWIPPAZDINA4           ZENC1             \n
 SP06182019ZBWIPPAZDINA4           ZENC1             /rsprod {\n
 SP06183041ZBWIPPAZDINA4           ZENC1                 2 copy 0 ne exch 0 ne and {\n
 SP06184071ZBWIPPAZDINA4           ZENC1                     rslog exch get exch rslog exch get add rsgf 1 sub mod r
 SP06185016ZBWIPPAZDINA4           ZENC1     salog exch get\n
 SP06186017ZBWIPPAZDINA4           ZENC1                 } {\n
 SP06187027ZBWIPPAZDINA4           ZENC1                     pop pop 0\n
 SP06188022ZBWIPPAZDINA4           ZENC1                 } ifelse\n
 SP06189020ZBWIPPAZDINA4           ZENC1             } bind def\n
 SP06190010ZBWIPPAZDINA4           ZENC1             \n
 SP06191043ZBWIPPAZDINA4           ZENC1             /coeffs [ 1 rsnc {0} repeat ] def\n
 SP06192020ZBWIPPAZDINA4           ZENC1             1 1 rsnc {\n
 SP06193026ZBWIPPAZDINA4           ZENC1                 /i exch def \n
 SP06194045ZBWIPPAZDINA4           ZENC1                 coeffs i coeffs i 1 sub get put\n
 SP06195028ZBWIPPAZDINA4           ZENC1                 i 1 sub -1 1 {\n
 SP06196029ZBWIPPAZDINA4           ZENC1                     /j exch def\n
 SP06197071ZBWIPPAZDINA4           ZENC1                     coeffs j coeffs j 1 sub get coeffs j get rsalog i get r
 SP06198015ZBWIPPAZDINA4           ZENC1     sprod xor put\n
 SP06199020ZBWIPPAZDINA4           ZENC1                 } for \n
 SP06200059ZBWIPPAZDINA4           ZENC1                 coeffs 0 coeffs 0 get rsalog i get rsprod put\n
 SP06201015ZBWIPPAZDINA4           ZENC1             } for\n
 SP06202010ZBWIPPAZDINA4           ZENC1             \n
 SP06203030ZBWIPPAZDINA4           ZENC1             /nd rscws length def\n
 SP06204058ZBWIPPAZDINA4           ZENC1             /rscws [ rscws {} forall rsnc {0} repeat 0 ] def\n
 SP06205024ZBWIPPAZDINA4           ZENC1             0 1 nd 1 sub {\n
 SP06206058ZBWIPPAZDINA4           ZENC1                 /k exch rscws exch get rscws nd get xor def \n
 SP06207030ZBWIPPAZDINA4           ZENC1                 0 1 rsnc 1 sub {\n
 SP06208030ZBWIPPAZDINA4           ZENC1                     /j exch def \n
 SP06209071ZBWIPPAZDINA4           ZENC1                     rscws nd j add rscws nd j add 1 add get k coeffs rsnc j
 SP06210031ZBWIPPAZDINA4           ZENC1      sub 1 sub get rsprod xor put\n
 SP06211020ZBWIPPAZDINA4           ZENC1                 } for \n
 SP06212015ZBWIPPAZDINA4           ZENC1             } for\n
 SP06213010ZBWIPPAZDINA4           ZENC1             \n
 SP06214048ZBWIPPAZDINA4           ZENC1             rscws 0 rscws length 1 sub getinterval\n
 SP06215016ZBWIPPAZDINA4           ZENC1         } bind def\n
 SP06216006ZBWIPPAZDINA4           ZENC1         \n
 SP06217024ZBWIPPAZDINA4           ZENC1         format (full) eq {\n
 SP06218065ZBWIPPAZDINA4           ZENC1             /mode layers 1 sub 11 bitshift cws length 1 sub add def\n
 SP06219062ZBWIPPAZDINA4           ZENC1             readerinit {/mode mode 2#1000000000000000 or def} if\n
 SP06220017ZBWIPPAZDINA4           ZENC1             /mode [\n
 SP06221054ZBWIPPAZDINA4           ZENC1                 mode 2#1111000000000000 and -12 bitshift\n
 SP06222053ZBWIPPAZDINA4           ZENC1                 mode 2#0000111100000000 and -8 bitshift\n
 SP06223053ZBWIPPAZDINA4           ZENC1                 mode 2#0000000011110000 and -4 bitshift\n
 SP06224041ZBWIPPAZDINA4           ZENC1                 mode 2#0000000000001111 and\n
 SP06225015ZBWIPPAZDINA4           ZENC1             ] def\n
 SP06226041ZBWIPPAZDINA4           ZENC1             /mode mode 6 16 19 rscodes def \n
 SP06227010ZBWIPPAZDINA4           ZENC1         } if\n
 SP06228027ZBWIPPAZDINA4           ZENC1         format (compact) eq {\n
 SP06229064ZBWIPPAZDINA4           ZENC1             /mode layers 1 sub 6 bitshift cws length 1 sub add def\n
 SP06230055ZBWIPPAZDINA4           ZENC1             readerinit {/mode mode 2#10000000 or def} if \n
 SP06231017ZBWIPPAZDINA4           ZENC1             /mode [\n
 SP06232045ZBWIPPAZDINA4           ZENC1                 mode 2#11110000 and -4 bitshift\n
 SP06233033ZBWIPPAZDINA4           ZENC1                 mode 2#00001111 and\n
 SP06234015ZBWIPPAZDINA4           ZENC1             ] def\n
 SP06235040ZBWIPPAZDINA4           ZENC1             /mode mode 5 16 19 rscodes def\n
 SP06236010ZBWIPPAZDINA4           ZENC1         } if\n
 SP06237024ZBWIPPAZDINA4           ZENC1         format (rune) eq {\n
 SP06238031ZBWIPPAZDINA4           ZENC1             /mode barcode cvi def\n
 SP06239017ZBWIPPAZDINA4           ZENC1             /mode [\n
 SP06240045ZBWIPPAZDINA4           ZENC1                 mode 2#11110000 and -4 bitshift\n
 SP06241033ZBWIPPAZDINA4           ZENC1                 mode 2#00001111 and\n
 SP06242015ZBWIPPAZDINA4           ZENC1             ] def\n
 SP06243040ZBWIPPAZDINA4           ZENC1             /mode mode 5 16 19 rscodes def\n
 SP06244048ZBWIPPAZDINA4           ZENC1             /mode [mode {2#1010 xor} forall] def  \n
 SP06245010ZBWIPPAZDINA4           ZENC1         } if\n
 SP06246044ZBWIPPAZDINA4           ZENC1         /modebits mode length 4 mul string def\n
 SP06247067ZBWIPPAZDINA4           ZENC1         0 1 modebits length 1 sub {modebits exch (0) putinterval} for\n
 SP06248029ZBWIPPAZDINA4           ZENC1         0 1 mode length 1 sub {\n
 SP06249021ZBWIPPAZDINA4           ZENC1             /i exch def\n
 SP06250071ZBWIPPAZDINA4           ZENC1             modebits mode i get 2 4 string cvrs dup length 4 exch sub 4 i m
 SP06251026ZBWIPPAZDINA4           ZENC1     ul add exch putinterval \n
 SP06252011ZBWIPPAZDINA4           ZENC1         } for\n
 SP06000017ZBWIPPAZDINA4           ZENC2     BWIPP encode qr 2
 SP06001026ZBWIPPAZDINA4           ZENC2     ##usage: BWIPP encode qr 2
 SP06002036ZBWIPPAZDINA4           ZENC2     ##DO NOT CHANGE the first two lines!
 SP06003006ZBWIPPAZDINA4           ZENC2         \n
 SP06004017ZBWIPPAZDINA4           ZENC2         /rsparams [\n
 SP06005028ZBWIPPAZDINA4           ZENC2             [] [] [] [] [] [] \n
 SP06006025ZBWIPPAZDINA4           ZENC2             [ 64 67 ]      \n
 SP06007012ZBWIPPAZDINA4           ZENC2             []\n
 SP06008025ZBWIPPAZDINA4           ZENC2             [ 256 301 ]    \n
 SP06009013ZBWIPPAZDINA4           ZENC2             [] \n
 SP06010025ZBWIPPAZDINA4           ZENC2             [ 1024 1033 ]  \n
 SP06011012ZBWIPPAZDINA4           ZENC2             []\n
 SP06012025ZBWIPPAZDINA4           ZENC2             [ 4096 4201 ]  \n
 SP06013011ZBWIPPAZDINA4           ZENC2         ] def\n
 SP06014071ZBWIPPAZDINA4           ZENC2         /cws cws ncws cws length sub rsparams bpcw get {} forall rscodes de
 SP06015003ZBWIPPAZDINA4           ZENC2     f\n
 SP06016024ZBWIPPAZDINA4           ZENC2         format (full) eq {\n
 SP06017071ZBWIPPAZDINA4           ZENC2             /databits layers layers mul 16 mul layers 112 mul add string de
 SP06018004ZBWIPPAZDINA4           ZENC2     f \n
 SP06019009ZBWIPPAZDINA4           ZENC2         } {\n
 SP06020071ZBWIPPAZDINA4           ZENC2             /databits layers layers mul 16 mul layers 88 mul add string def
 SP06021003ZBWIPPAZDINA4           ZENC2      \n
 SP06022014ZBWIPPAZDINA4           ZENC2         } ifelse\n
 SP06023067ZBWIPPAZDINA4           ZENC2         0 1 databits length 1 sub {databits exch (0) putinterval} for\n
 SP06024023ZBWIPPAZDINA4           ZENC2         0 1 ncws 1 sub { \n
 SP06025021ZBWIPPAZDINA4           ZENC2             /i exch def\n
 SP06026048ZBWIPPAZDINA4           ZENC2             databits cws i get 2 bpcw string cvrs \n
 SP06027071ZBWIPPAZDINA4           ZENC2             dup length bpcw exch sub bpcw i mul add databits length ncws bp
 SP06028017ZBWIPPAZDINA4           ZENC2     cw mul sub add \n
 SP06029027ZBWIPPAZDINA4           ZENC2             exch putinterval \n
 SP06030011ZBWIPPAZDINA4           ZENC2         } for\n
 SP06031006ZBWIPPAZDINA4           ZENC2         \n
 SP06032042ZBWIPPAZDINA4           ZENC2         /cmv {size mul sub mid add} bind def\n
 SP06033006ZBWIPPAZDINA4           ZENC2         \n
 SP06034012ZBWIPPAZDINA4           ZENC2         /lmv {\n
 SP06035024ZBWIPPAZDINA4           ZENC2             /lbit exch def\n
 SP06036024ZBWIPPAZDINA4           ZENC2             /llyr exch def\n
 SP06037037ZBWIPPAZDINA4           ZENC2             /lwid fw llyr 4 mul add def\n
 SP06038041ZBWIPPAZDINA4           ZENC2             /ldir lbit 2 idiv lwid idiv def\n
 SP06039023ZBWIPPAZDINA4           ZENC2             ldir 0 eq {  \n
 SP06040067ZBWIPPAZDINA4           ZENC2                 lwid 1 sub 2 idiv neg 1 add lbit 2 idiv lwid mod add \n
 SP06041059ZBWIPPAZDINA4           ZENC2                 fw 1 sub 2 idiv llyr 2 mul add lbit 2 mod add\n
 SP06042017ZBWIPPAZDINA4           ZENC2                 cmv\n
 SP06043014ZBWIPPAZDINA4           ZENC2             } if\n
 SP06044023ZBWIPPAZDINA4           ZENC2             ldir 1 eq {  \n
 SP06045053ZBWIPPAZDINA4           ZENC2                 fw 2 idiv llyr 2 mul add lbit 2 mod add\n
 SP06046062ZBWIPPAZDINA4           ZENC2                 lwid 1 sub 2 idiv 1 sub lbit 2 idiv lwid mod sub\n
 SP06047017ZBWIPPAZDINA4           ZENC2                 cmv\n
 SP06048014ZBWIPPAZDINA4           ZENC2             } if\n
 SP06049023ZBWIPPAZDINA4           ZENC2             ldir 2 eq {  \n
 SP06050064ZBWIPPAZDINA4           ZENC2                 lwid 2 idiv neg 1 add lbit 2 idiv lwid mod add neg\n
 SP06051057ZBWIPPAZDINA4           ZENC2                 fw 2 idiv llyr 2 mul add lbit 2 mod add neg\n
 SP06052017ZBWIPPAZDINA4           ZENC2                 cmv\n
 SP06053014ZBWIPPAZDINA4           ZENC2             } if\n
 SP06054023ZBWIPPAZDINA4           ZENC2             ldir 3 eq {  \n
 SP06055063ZBWIPPAZDINA4           ZENC2                 fw 1 sub 2 idiv llyr 2 mul add lbit 2 mod add neg\n
 SP06056060ZBWIPPAZDINA4           ZENC2                 lwid 2 idiv 1 sub lbit 2 idiv lwid mod sub neg\n
 SP06057017ZBWIPPAZDINA4           ZENC2                 cmv\n
 SP06058014ZBWIPPAZDINA4           ZENC2             } if\n
 SP06059016ZBWIPPAZDINA4           ZENC2         } bind def\n
 SP06060006ZBWIPPAZDINA4           ZENC2         \n
 SP06061006ZBWIPPAZDINA4           ZENC2         \n
 SP06062054ZBWIPPAZDINA4           ZENC2         format (full) eq {/fw 12 def} {/fw 9 def} ifelse\n
 SP06063042ZBWIPPAZDINA4           ZENC2         /size fw layers 4 mul add 2 add def \n
 SP06064043ZBWIPPAZDINA4           ZENC2         /pixs [size size mul {-1} repeat] def\n
 SP06065063ZBWIPPAZDINA4           ZENC2         /mid size 1 sub 2 idiv size mul size 1 sub 2 idiv add def\n
 SP06066006ZBWIPPAZDINA4           ZENC2         \n
 SP06067014ZBWIPPAZDINA4           ZENC2         /i 0 def\n
 SP06068018ZBWIPPAZDINA4           ZENC2         1 1 layers {\n
 SP06069025ZBWIPPAZDINA4           ZENC2             /layer exch def\n
 SP06070046ZBWIPPAZDINA4           ZENC2             0 1 fw layer 4 mul add 8 mul 1 sub {\n
 SP06071027ZBWIPPAZDINA4           ZENC2                 /pos exch def\n
 SP06072071ZBWIPPAZDINA4           ZENC2                 pixs layer pos lmv databits databits length i sub 1 sub get
 SP06073013ZBWIPPAZDINA4           ZENC2      48 sub put\n
 SP06074028ZBWIPPAZDINA4           ZENC2                 /i i 1 add def\n
 SP06075015ZBWIPPAZDINA4           ZENC2             } for\n
 SP06076011ZBWIPPAZDINA4           ZENC2         } for\n
 SP06077006ZBWIPPAZDINA4           ZENC2         \n
 SP06078024ZBWIPPAZDINA4           ZENC2         format (full) eq {\n
 SP06079020ZBWIPPAZDINA4           ZENC2             /fw 13 def\n
 SP06080071ZBWIPPAZDINA4           ZENC2             /size fw layers 4 mul add 2 add layers 10.5 add 7.5 div 1 sub c
 SP06081018ZBWIPPAZDINA4           ZENC2     vi 2 mul add def\n
 SP06082039ZBWIPPAZDINA4           ZENC2             /mid size size mul 2 idiv def\n
 SP06083048ZBWIPPAZDINA4           ZENC2             /npixs [size size mul {-2} repeat] def\n
 SP06084028ZBWIPPAZDINA4           ZENC2             0 16 size 2 idiv {\n
 SP06085025ZBWIPPAZDINA4           ZENC2                 /i exch def\n
 SP06086030ZBWIPPAZDINA4           ZENC2                 0 1 size 1 sub {\n
 SP06087029ZBWIPPAZDINA4           ZENC2                     /j exch def\n
 SP06088071ZBWIPPAZDINA4           ZENC2                     npixs size 2 idiv neg j add i cmv     [size 2 idiv j ad
 SP06089034ZBWIPPAZDINA4           ZENC2     d i add 1 add 2 mod] putinterval\n
 SP06090071ZBWIPPAZDINA4           ZENC2                     npixs size 2 idiv neg j add i neg cmv [size 2 idiv j ad
 SP06091034ZBWIPPAZDINA4           ZENC2     d i add 1 add 2 mod] putinterval\n
 SP06092071ZBWIPPAZDINA4           ZENC2                     npixs i size 2 idiv neg j add cmv     [size 2 idiv j ad
 SP06093034ZBWIPPAZDINA4           ZENC2     d i add 1 add 2 mod] putinterval\n
 SP06094071ZBWIPPAZDINA4           ZENC2                     npixs i neg size 2 idiv neg j add cmv [size 2 idiv j ad
 SP06095034ZBWIPPAZDINA4           ZENC2     d i add 1 add 2 mod] putinterval\n
 SP06096019ZBWIPPAZDINA4           ZENC2                 } for\n
 SP06097016ZBWIPPAZDINA4           ZENC2             } for \n
 SP06098018ZBWIPPAZDINA4           ZENC2             /j 0 def\n
 SP06099034ZBWIPPAZDINA4           ZENC2             0 1 npixs length 1 sub {\n
 SP06100025ZBWIPPAZDINA4           ZENC2                 /i exch def\n
 SP06101033ZBWIPPAZDINA4           ZENC2                 npixs i get -2 eq {\n
 SP06102040ZBWIPPAZDINA4           ZENC2                     npixs i pixs j get put\n
 SP06103032ZBWIPPAZDINA4           ZENC2                     /j j 1 add def\n
 SP06104018ZBWIPPAZDINA4           ZENC2                 } if\n
 SP06105015ZBWIPPAZDINA4           ZENC2             } for\n
 SP06106025ZBWIPPAZDINA4           ZENC2             /pixs npixs def\n
 SP06107010ZBWIPPAZDINA4           ZENC2         } if\n
 SP06108006ZBWIPPAZDINA4           ZENC2         \n
 SP06109023ZBWIPPAZDINA4           ZENC2         /fw fw 2 idiv def\n
 SP06110019ZBWIPPAZDINA4           ZENC2         fw neg 1 fw {\n
 SP06111021ZBWIPPAZDINA4           ZENC2             /i exch def\n
 SP06112023ZBWIPPAZDINA4           ZENC2             fw neg 1 fw {\n
 SP06113025ZBWIPPAZDINA4           ZENC2                 /j exch def\n
 SP06114026ZBWIPPAZDINA4           ZENC2                 pixs i j cmv\n
 SP06115063ZBWIPPAZDINA4           ZENC2                 i abs j abs gt {i abs} {j abs} ifelse 1 add 2 mod\n
 SP06116017ZBWIPPAZDINA4           ZENC2                 put\n
 SP06117015ZBWIPPAZDINA4           ZENC2             } for\n
 SP06118011ZBWIPPAZDINA4           ZENC2         } for\n
 SP06119006ZBWIPPAZDINA4           ZENC2         \n
 SP06120067ZBWIPPAZDINA4           ZENC2         [ [ fw 1 add neg   fw             1 ] [ fw 1 add neg   fw 1 add
 SP06121009ZBWIPPAZDINA4           ZENC2         1 ]\n
 SP06122067ZBWIPPAZDINA4           ZENC2           [ fw neg         fw 1 add       1 ] [ fw 1 add       fw 1 add
 SP06123009ZBWIPPAZDINA4           ZENC2         1 ]\n
 SP06124065ZBWIPPAZDINA4           ZENC2           [ fw 1 add       fw             1 ] [ fw 1 add       fw neg
 SP06125009ZBWIPPAZDINA4           ZENC2         1 ]\n
 SP06126071ZBWIPPAZDINA4           ZENC2           [ fw             fw 1 add       0 ] [ fw 1 add       fw 1 add neg
 SP06127008ZBWIPPAZDINA4           ZENC2        0 ]\n
 SP06128071ZBWIPPAZDINA4           ZENC2           [ fw             fw 1 add neg   0 ] [ fw neg         fw 1 add neg
 SP06129008ZBWIPPAZDINA4           ZENC2        0 ]\n
 SP06130065ZBWIPPAZDINA4           ZENC2           [ fw 1 add neg   fw 1 add neg   0 ] [ fw 1 add neg   fw neg
 SP06131009ZBWIPPAZDINA4           ZENC2         0 ]\n
 SP06132058ZBWIPPAZDINA4           ZENC2         ] {pixs exch {} forall 3 1 roll cmv exch put} forall\n
 SP06133006ZBWIPPAZDINA4           ZENC2         \n
 SP06134024ZBWIPPAZDINA4           ZENC2         format (full) eq {\n
 SP06135021ZBWIPPAZDINA4           ZENC2             /modemap [ \n
 SP06136071ZBWIPPAZDINA4           ZENC2                 [-5  7] [-4  7] [-3  7] [-2  7] [-1  7] [ 1  7] [ 2  7] [ 3
 SP06137022ZBWIPPAZDINA4           ZENC2       7] [ 4  7] [ 5  7]\n
 SP06138071ZBWIPPAZDINA4           ZENC2                 [ 7  5] [ 7  4] [ 7  3] [ 7  2] [ 7  1] [ 7 -1] [ 7 -2] [ 7
 SP06139022ZBWIPPAZDINA4           ZENC2      -3] [ 7 -4] [ 7 -5]\n
 SP06140071ZBWIPPAZDINA4           ZENC2                 [ 5 -7] [ 4 -7] [ 3 -7] [ 2 -7] [ 1 -7] [-1 -7] [-2 -7] [-3
 SP06141022ZBWIPPAZDINA4           ZENC2      -7] [-4 -7] [-5 -7]\n
 SP06142071ZBWIPPAZDINA4           ZENC2                 [-7 -5] [-7 -4] [-7 -3] [-7 -2] [-7 -1] [-7  1] [-7  2] [-7
 SP06143022ZBWIPPAZDINA4           ZENC2       3] [-7  4] [-7  5]\n
 SP06144015ZBWIPPAZDINA4           ZENC2             ] def\n
 SP06145009ZBWIPPAZDINA4           ZENC2         } {\n
 SP06146020ZBWIPPAZDINA4           ZENC2             /modemap [\n
 SP06147069ZBWIPPAZDINA4           ZENC2                 [-3  5] [-2  5] [-1  5] [ 0  5] [ 1  5] [ 2  5] [ 3  5]\n
 SP06148069ZBWIPPAZDINA4           ZENC2                 [ 5  3] [ 5  2] [ 5  1] [ 5  0] [ 5 -1] [ 5 -2] [ 5 -3]\n
 SP06149069ZBWIPPAZDINA4           ZENC2                 [ 3 -5] [ 2 -5] [ 1 -5] [ 0 -5] [-1 -5] [-2 -5] [-3 -5]\n
 SP06150069ZBWIPPAZDINA4           ZENC2                 [-5 -3] [-5 -2] [-5 -1] [-5  0] [-5  1] [-5  2] [-5  3]\n
 SP06151015ZBWIPPAZDINA4           ZENC2             ] def\n
 SP06152014ZBWIPPAZDINA4           ZENC2         } ifelse\n
 SP06153032ZBWIPPAZDINA4           ZENC2         0 1 modemap length 1 sub {\n
 SP06154021ZBWIPPAZDINA4           ZENC2             /i exch def\n
 SP06155068ZBWIPPAZDINA4           ZENC2             pixs modemap i get {} forall cmv modebits i get 48 sub put\n
 SP06156011ZBWIPPAZDINA4           ZENC2         } for\n
 SP06157008ZBWIPPAZDINA4           ZENC2         <<\n
 SP06158022ZBWIPPAZDINA4           ZENC2         /ren //renmatrix\n
 SP06159016ZBWIPPAZDINA4           ZENC2         /pixs pixs\n
 SP06160016ZBWIPPAZDINA4           ZENC2         /pixx size\n
 SP06161016ZBWIPPAZDINA4           ZENC2         /pixy size\n
 SP06162031ZBWIPPAZDINA4           ZENC2         /height size 2 mul 72 div\n
 SP06163030ZBWIPPAZDINA4           ZENC2         /width size 2 mul 72 div\n
 SP06164018ZBWIPPAZDINA4           ZENC2         /opt options\n
 SP06165008ZBWIPPAZDINA4           ZENC2         >>\n
 SP06166033ZBWIPPAZDINA4           ZENC2         dontdraw not //renmatrix if\n
 SP06167009ZBWIPPAZDINA4           ZENC2         end\n
 SP06168012ZBWIPPAZDINA4           ZENC2     } bind def\n
 SP06169065ZBWIPPAZDINA4           ZENC2     /azteccode dup load /uk.co.terryburton.bwipp defineresource pop\n
 SP06170005ZBWIPPAZDINA4           ZENC2     end\n
 SP06171040ZBWIPPAZDINA4           ZENC2     /setpacking where {pop setpacking} if \n
 SP06000020ZBWIPPAZDINA4           ZREND3    BWIPP rend renmatrix
 SP06001029ZBWIPPAZDINA4           ZREND3    ##usage: BWIPP rend renmatrix
 SP06002036ZBWIPPAZDINA4           ZREND3    ##DO NOT CHANGE the first two lines!
 SP06003059ZBWIPPAZDINA4           ZREND3    /setpacking where {pop currentpacking true setpacking} if\n
 SP06004008ZBWIPPAZDINA4           ZREND3    1 dict\n
 SP06005007ZBWIPPAZDINA4           ZREND3    begin\n
 SP06006014ZBWIPPAZDINA4           ZREND3    /renmatrix {\n
 SP06007019ZBWIPPAZDINA4           ZREND3        20 dict begin\n
 SP06008020ZBWIPPAZDINA4           ZREND3        /args exch def\n
 SP06009006ZBWIPPAZDINA4           ZREND3        \n
 SP06010018ZBWIPPAZDINA4           ZREND3        /width 1 def\n
 SP06011019ZBWIPPAZDINA4           ZREND3        /height 1 def\n
 SP06012024ZBWIPPAZDINA4           ZREND3        /color (unset) def\n
 SP06013034ZBWIPPAZDINA4           ZREND3        /backgroundcolor (unset) def\n
 SP06014006ZBWIPPAZDINA4           ZREND3        \n
 SP06015023ZBWIPPAZDINA4           ZREND3        args {def} forall\n
 SP06016022ZBWIPPAZDINA4           ZREND3        opt {def} forall\n
 SP06017026ZBWIPPAZDINA4           ZREND3        /width width cvr def\n
 SP06018028ZBWIPPAZDINA4           ZREND3        /height height cvr def\n
 SP06019028ZBWIPPAZDINA4           ZREND3        /color color cvlit def\n
 SP06020048ZBWIPPAZDINA4           ZREND3        /backgroundcolor backgroundcolor cvlit def\n
 SP06021006ZBWIPPAZDINA4           ZREND3        \n
 SP06022045ZBWIPPAZDINA4           ZREND3        /pixx8 pixx 8 div ceiling cvi 8 mul def\n
 SP06023046ZBWIPPAZDINA4           ZREND3        /pixs8 [ pixx8 pixy mul {0} repeat ] def\n
 SP06024022ZBWIPPAZDINA4           ZREND3        0 1 pixy 1 sub {\n
 SP06025021ZBWIPPAZDINA4           ZREND3            /i exch def\n
 SP06026071ZBWIPPAZDINA4           ZREND3            pixs8 pixx8 i mul pixs pixx i mul pixx getinterval putinterval\
 SP06027001ZBWIPPAZDINA4           ZREND3    n
 SP06028011ZBWIPPAZDINA4           ZREND3        } for\n
 SP06029021ZBWIPPAZDINA4           ZREND3        /pixs pixs8 def\n
 SP06030006ZBWIPPAZDINA4           ZREND3        \n
 SP06031043ZBWIPPAZDINA4           ZREND3        /imgstr pixs length 8 idiv string def\n
 SP06032029ZBWIPPAZDINA4           ZREND3        0 1 pixs length 1 sub {\n
 SP06033021ZBWIPPAZDINA4           ZREND3            /i exch def\n
 SP06034071ZBWIPPAZDINA4           ZREND3            imgstr i 8 idiv 2 copy get 2 7 i 8 mod sub exp cvi pixs i get m
 SP06035012ZBWIPPAZDINA4           ZREND3    ul add put\n
 SP06036011ZBWIPPAZDINA4           ZREND3        } for\n
 SP06037006ZBWIPPAZDINA4           ZREND3        \n
 SP06038020ZBWIPPAZDINA4           ZREND3        /setanycolor {\n
 SP06039028ZBWIPPAZDINA4           ZREND3            /anycolor exch def\n
 SP06040032ZBWIPPAZDINA4           ZREND3            anycolor length 6 eq {\n
 SP06041071ZBWIPPAZDINA4           ZREND3                (<      >) 8 string copy dup 1 anycolor putinterval cvx exe
 SP06042032ZBWIPPAZDINA4           ZREND3    c {255 div} forall setrgbcolor\n
 SP06043014ZBWIPPAZDINA4           ZREND3            } if\n
 SP06044032ZBWIPPAZDINA4           ZREND3            anycolor length 8 eq {\n
 SP06045070ZBWIPPAZDINA4           ZREND3                (<        >) 10 string copy dup 1 anycolor putinterval cvx
 SP06046037ZBWIPPAZDINA4           ZREND3     exec {255 div} forall setcmykcolor\n
 SP06047014ZBWIPPAZDINA4           ZREND3            } if\n
 SP06048016ZBWIPPAZDINA4           ZREND3        } bind def\n
 SP06049006ZBWIPPAZDINA4           ZREND3        \n
 SP06050011ZBWIPPAZDINA4           ZREND3        gsave\n
 SP06051028ZBWIPPAZDINA4           ZREND3        currentpoint translate\n
 SP06052038ZBWIPPAZDINA4           ZREND3        72 width mul 72 height mul scale\n
 SP06053071ZBWIPPAZDINA4           ZREND3        .0001 .0001 moveto .9999 .0001 lineto .9999 .9999 lineto .0001 .999
 SP06054020ZBWIPPAZDINA4           ZREND3    9 lineto closepath\n
 SP06055071ZBWIPPAZDINA4           ZREND3        backgroundcolor (unset) ne { gsave backgroundcolor setanycolor fill
 SP06056017ZBWIPPAZDINA4           ZREND3     grestore } if \n
 SP06057047ZBWIPPAZDINA4           ZREND3        color (unset) ne { color setanycolor } if\n
 SP06058068ZBWIPPAZDINA4           ZREND3        pixx pixy true [ pixx 0 0 pixy neg 0 pixy ] {imgstr} imagemask\n
 SP06059014ZBWIPPAZDINA4           ZREND3        grestore\n
 SP06060009ZBWIPPAZDINA4           ZREND3        end\n
 SP06061012ZBWIPPAZDINA4           ZREND3    } bind def\n
 SP06062065ZBWIPPAZDINA4           ZREND3    /renmatrix dup load /uk.co.terryburton.bwipp defineresource pop\n
 SP06063005ZBWIPPAZDINA4           ZREND3    end\n
 SP06064039ZBWIPPAZDINA4           ZREND3    /setpacking where {pop setpacking} if\n
 SP06065000ZBWIPPAZDINA4           ZREND3
 SP1DDINA5           DINA5   .S0000000000SAP         1997081213400240A BIN     SAP                                   SAP
 SP1XDINA5            000000000000000000000000
 SP06001006ZBWIPPAZDINA5           CONTROL     2 \n
 SP06002072ZBWIPPAZDINA5           CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZDINA5           CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZDINA5           CONTROL                                                                         \n
 SP06001043ZBWIPPAZDINA5           ENDLINE   #this is a reference to another device type
 SP06002026ZBWIPPAZDINA5           ENDLINE   \i<POSTSCPT:DINA5:ENDLINE>
 SP06001043ZBWIPPAZDINA5           ENDPAGE   #this is a reference to another device type
 SP06002026ZBWIPPAZDINA5           ENDPAGE   \i<POSTSCPT:DINA5:ENDPAGE>
 SP06001043ZBWIPPAZDINA5           LEAVE     #this is a reference to another device type
 SP06002024ZBWIPPAZDINA5           LEAVE     \i<POSTSCPT:DINA5:LEAVE>
 SP06001043ZBWIPPAZDINA5           SETUP     #this is a reference to another device type
 SP06002026ZBWIPPAZDINA5           SETUP     \i<POSTSCPT:DINA5:SETUP>\n
 SP06003027ZBWIPPAZDINA5           SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZDINA5           SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZDINA5           SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZDINA5           SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZDINA5           SETUP
 SP1DEXECUTIV        EXECUTIV.S0000000000SAP         1997081213401940A BIN     SAP                                   SAP
 SP1XEXECUTIV         000000000000000000000000
 SP06001006ZBWIPPAZEXECUTIV        CONTROL     2 \n
 SP06002072ZBWIPPAZEXECUTIV        CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZEXECUTIV        CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZEXECUTIV        CONTROL                                                                         \n
 SP06001043ZBWIPPAZEXECUTIV        ENDLINE   #this is a reference to another device type
 SP06002029ZBWIPPAZEXECUTIV        ENDLINE   \i<POSTSCPT:EXECUTIV:ENDLINE>
 SP06001043ZBWIPPAZEXECUTIV        ENDPAGE   #this is a reference to another device type
 SP06002029ZBWIPPAZEXECUTIV        ENDPAGE   \i<POSTSCPT:EXECUTIV:ENDPAGE>
 SP06001043ZBWIPPAZEXECUTIV        LEAVE     #this is a reference to another device type
 SP06002027ZBWIPPAZEXECUTIV        LEAVE     \i<POSTSCPT:EXECUTIV:LEAVE>
 SP06001043ZBWIPPAZEXECUTIV        SETUP     #this is a reference to another device type
 SP06002029ZBWIPPAZEXECUTIV        SETUP     \i<POSTSCPT:EXECUTIV:SETUP>\n
 SP06003027ZBWIPPAZEXECUTIV        SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZEXECUTIV        SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZEXECUTIV        SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZEXECUTIV        SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZEXECUTIV        SETUP
 SP1DINCH11          INCH11  PS0000000000SAP         1997081213444840A BIN     SAP                                   SAP
 SP1XINCH11           000000000000000000000000
 SP06001006ZBWIPPAZINCH11          CONTROL     2 \n
 SP06002072ZBWIPPAZINCH11          CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZINCH11          CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZINCH11          CONTROL                                                                         \n
 SP06001043ZBWIPPAZINCH11          ENDLINE   #this is a reference to another device type
 SP06002027ZBWIPPAZINCH11          ENDLINE   \i<POSTSCPT:INCH11:ENDLINE>
 SP06001043ZBWIPPAZINCH11          ENDPAGE   #this is a reference to another device type
 SP06002027ZBWIPPAZINCH11          ENDPAGE   \i<POSTSCPT:INCH11:ENDPAGE>
 SP06001043ZBWIPPAZINCH11          LEAVE     #this is a reference to another device type
 SP06002025ZBWIPPAZINCH11          LEAVE     \i<POSTSCPT:INCH11:LEAVE>
 SP06001043ZBWIPPAZINCH11          SETUP     #this is a reference to another device type
 SP06002027ZBWIPPAZINCH11          SETUP     \i<POSTSCPT:INCH11:SETUP>\n
 SP06003027ZBWIPPAZINCH11          SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZINCH11          SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZINCH11          SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZINCH11          SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZINCH11          SETUP
 SP1DINCH12          INCH12  PS0000000000SAP         1997081213445640A BIN     SAP                                   SAP
 SP1XINCH12           000000000000000000000000
 SP06001006ZBWIPPAZINCH12          CONTROL     2 \n
 SP06002072ZBWIPPAZINCH12          CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZINCH12          CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZINCH12          CONTROL                                                                         \n
 SP06001043ZBWIPPAZINCH12          ENDLINE   #this is a reference to another device type
 SP06002027ZBWIPPAZINCH12          ENDLINE   \i<POSTSCPT:INCH12:ENDLINE>
 SP06001043ZBWIPPAZINCH12          ENDPAGE   #this is a reference to another device type
 SP06002027ZBWIPPAZINCH12          ENDPAGE   \i<POSTSCPT:INCH12:ENDPAGE>
 SP06001043ZBWIPPAZINCH12          LEAVE     #this is a reference to another device type
 SP06002025ZBWIPPAZINCH12          LEAVE     \i<POSTSCPT:INCH12:LEAVE>
 SP06001043ZBWIPPAZINCH12          SETUP     #this is a reference to another device type
 SP06002027ZBWIPPAZINCH12          SETUP     \i<POSTSCPT:INCH12:SETUP>\n
 SP06003027ZBWIPPAZINCH12          SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZINCH12          SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZINCH12          SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZINCH12          SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZINCH12          SETUP
 SP1DINCH2           INCH2   PS0000000000SAP         1998040710415940C BIN     SAP         1997081213453740A BIN     SAP
 SP1XINCH2            000000000000000000000000
 SP06001006ZBWIPPAZINCH2           CONTROL     2 \n
 SP06002072ZBWIPPAZINCH2           CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZINCH2           CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZINCH2           CONTROL                                                                         \n
 SP06001043ZBWIPPAZINCH2           ENDLINE   #this is a reference to another device type
 SP06002026ZBWIPPAZINCH2           ENDLINE   \i<POSTSCPT:INCH2:ENDLINE>
 SP06001043ZBWIPPAZINCH2           ENDPAGE   #this is a reference to another device type
 SP06002026ZBWIPPAZINCH2           ENDPAGE   \i<POSTSCPT:INCH2:ENDPAGE>
 SP06001043ZBWIPPAZINCH2           LEAVE     #this is a reference to another device type
 SP06002024ZBWIPPAZINCH2           LEAVE     \i<POSTSCPT:INCH2:LEAVE>
 SP06001043ZBWIPPAZINCH2           SETUP     #this is a reference to another device type
 SP06002026ZBWIPPAZINCH2           SETUP     \i<POSTSCPT:INCH2:SETUP>\n
 SP06003027ZBWIPPAZINCH2           SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZINCH2           SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZINCH2           SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZINCH2           SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZINCH2           SETUP
 SP1DINCH4           INCH4   PS0000000000SAP         1997081213450240A BIN     SAP                                   SAP
 SP1XINCH4            000000000000000000000000
 SP06001006ZBWIPPAZINCH4           CONTROL     2 \n
 SP06002072ZBWIPPAZINCH4           CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZINCH4           CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZINCH4           CONTROL                                                                         \n
 SP06001043ZBWIPPAZINCH4           ENDLINE   #this is a reference to another device type
 SP06002026ZBWIPPAZINCH4           ENDLINE   \i<POSTSCPT:INCH4:ENDLINE>
 SP06001043ZBWIPPAZINCH4           ENDPAGE   #this is a reference to another device type
 SP06002026ZBWIPPAZINCH4           ENDPAGE   \i<POSTSCPT:INCH4:ENDPAGE>
 SP06001043ZBWIPPAZINCH4           LEAVE     #this is a reference to another device type
 SP06002024ZBWIPPAZINCH4           LEAVE     \i<POSTSCPT:INCH4:LEAVE>
 SP06001043ZBWIPPAZINCH4           SETUP     #this is a reference to another device type
 SP06002026ZBWIPPAZINCH4           SETUP     \i<POSTSCPT:INCH4:SETUP>\n
 SP06003027ZBWIPPAZINCH4           SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZINCH4           SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZINCH4           SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZINCH4           SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZINCH4           SETUP
 SP1DINCH4C          INCH4C  PS0000000000SAP         1997081213451240A BIN     SAP                                   SAP
 SP1XINCH4C           000000000000000000000000
 SP06001006ZBWIPPAZINCH4C          CONTROL     2 \n
 SP06002072ZBWIPPAZINCH4C          CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZINCH4C          CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZINCH4C          CONTROL                                                                         \n
 SP06001043ZBWIPPAZINCH4C          ENDLINE   #this is a reference to another device type
 SP06002027ZBWIPPAZINCH4C          ENDLINE   \i<POSTSCPT:INCH4C:ENDLINE>
 SP06001043ZBWIPPAZINCH4C          ENDPAGE   #this is a reference to another device type
 SP06002027ZBWIPPAZINCH4C          ENDPAGE   \i<POSTSCPT:INCH4C:ENDPAGE>
 SP06001043ZBWIPPAZINCH4C          LEAVE     #this is a reference to another device type
 SP06002025ZBWIPPAZINCH4C          LEAVE     \i<POSTSCPT:INCH4C:LEAVE>
 SP06001043ZBWIPPAZINCH4C          SETUP     #this is a reference to another device type
 SP06002027ZBWIPPAZINCH4C          SETUP     \i<POSTSCPT:INCH4C:SETUP>\n
 SP06003027ZBWIPPAZINCH4C          SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZINCH4C          SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZINCH4C          SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZINCH4C          SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZINCH4C          SETUP
 SP1DINCH5           INCH5   PS0000000000SAP         1998020915380140C BIN     SAP         1997081213452140A BIN     SAP
 SP1XINCH5            000000000000000000000000
 SP06001006ZBWIPPAZINCH5           CONTROL     2 \n
 SP06002072ZBWIPPAZINCH5           CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZINCH5           CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZINCH5           CONTROL                                                                         \n
 SP06001043ZBWIPPAZINCH5           ENDLINE   #this is a reference to another device type
 SP06002026ZBWIPPAZINCH5           ENDLINE   \i<POSTSCPT:INCH5:ENDLINE>
 SP06001043ZBWIPPAZINCH5           ENDPAGE   #this is a reference to another device type
 SP06002026ZBWIPPAZINCH5           ENDPAGE   \i<POSTSCPT:INCH5:ENDPAGE>
 SP06001043ZBWIPPAZINCH5           LEAVE     #this is a reference to another device type
 SP06002024ZBWIPPAZINCH5           LEAVE     \i<POSTSCPT:INCH5:LEAVE>
 SP06001043ZBWIPPAZINCH5           SETUP     #this is a reference to another device type
 SP06002026ZBWIPPAZINCH5           SETUP     \i<POSTSCPT:INCH5:SETUP>\n
 SP06003027ZBWIPPAZINCH5           SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZINCH5           SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZINCH5           SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZINCH5           SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZINCH5           SETUP
 SP1DINCH6           INCH6   PS0000000000SAP         1997081213452140A BIN     SAP                                   SAP
 SP1XINCH6            000000000000000000000000
 SP06001006ZBWIPPAZINCH6           CONTROL     2 \n
 SP06002072ZBWIPPAZINCH6           CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZINCH6           CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZINCH6           CONTROL                                                                         \n
 SP06001043ZBWIPPAZINCH6           ENDLINE   #this is a reference to another device type
 SP06002026ZBWIPPAZINCH6           ENDLINE   \i<POSTSCPT:INCH6:ENDLINE>
 SP06001043ZBWIPPAZINCH6           ENDPAGE   #this is a reference to another device type
 SP06002026ZBWIPPAZINCH6           ENDPAGE   \i<POSTSCPT:INCH6:ENDPAGE>
 SP06001043ZBWIPPAZINCH6           LEAVE     #this is a reference to another device type
 SP06002024ZBWIPPAZINCH6           LEAVE     \i<POSTSCPT:INCH6:LEAVE>
 SP06001043ZBWIPPAZINCH6           SETUP     #this is a reference to another device type
 SP06002026ZBWIPPAZINCH6           SETUP     \i<POSTSCPT:INCH6:SETUP>\n
 SP06003027ZBWIPPAZINCH6           SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZINCH6           SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZINCH6           SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZINCH6           SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZINCH6           SETUP
 SP1DINCH7           INCH7   PS0000000000SAP         1997081213452940A BIN     SAP                                   SAP
 SP1XINCH7            000000000000000000000000
 SP06001006ZBWIPPAZINCH7           CONTROL     2 \n
 SP06002072ZBWIPPAZINCH7           CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZINCH7           CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZINCH7           CONTROL                                                                         \n
 SP06001043ZBWIPPAZINCH7           ENDLINE   #this is a reference to another device type
 SP06002026ZBWIPPAZINCH7           ENDLINE   \i<POSTSCPT:INCH7:ENDLINE>
 SP06001043ZBWIPPAZINCH7           ENDPAGE   #this is a reference to another device type
 SP06002026ZBWIPPAZINCH7           ENDPAGE   \i<POSTSCPT:INCH7:ENDPAGE>
 SP06001043ZBWIPPAZINCH7           LEAVE     #this is a reference to another device type
 SP06002024ZBWIPPAZINCH7           LEAVE     \i<POSTSCPT:INCH7:LEAVE>
 SP06001043ZBWIPPAZINCH7           SETUP     #this is a reference to another device type
 SP06002026ZBWIPPAZINCH7           SETUP     \i<POSTSCPT:INCH7:SETUP>\n
 SP06003027ZBWIPPAZINCH7           SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZINCH7           SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZINCH7           SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZINCH7           SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZINCH7           SETUP
 SP1DINCH8           INCH8   PS0000000000SAP         1997081213453740A BIN     SAP                                   SAP
 SP1XINCH8            000000000000000000000000
 SP06001006ZBWIPPAZINCH8           CONTROL     2 \n
 SP06002072ZBWIPPAZINCH8           CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZINCH8           CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZINCH8           CONTROL                                                                         \n
 SP06001043ZBWIPPAZINCH8           ENDLINE   #this is a reference to another device type
 SP06002026ZBWIPPAZINCH8           ENDLINE   \i<POSTSCPT:INCH8:ENDLINE>
 SP06001043ZBWIPPAZINCH8           ENDPAGE   #this is a reference to another device type
 SP06002026ZBWIPPAZINCH8           ENDPAGE   \i<POSTSCPT:INCH8:ENDPAGE>
 SP06001043ZBWIPPAZINCH8           LEAVE     #this is a reference to another device type
 SP06002024ZBWIPPAZINCH8           LEAVE     \i<POSTSCPT:INCH8:LEAVE>
 SP06001043ZBWIPPAZINCH8           SETUP     #this is a reference to another device type
 SP06002026ZBWIPPAZINCH8           SETUP     \i<POSTSCPT:INCH8:SETUP>\n
 SP06003027ZBWIPPAZINCH8           SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZINCH8           SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZINCH8           SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZINCH8           SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZINCH8           SETUP
 SP1DLEGAL           LEGAL   .S0000000000SAP         1997081213454840A BIN     SAP                                   SAP
 SP1XLEGAL            000000000000000000000000
 SP06001006ZBWIPPAZLEGAL           CONTROL     2 \n
 SP06002072ZBWIPPAZLEGAL           CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZLEGAL           CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZLEGAL           CONTROL                                                                         \n
 SP06001043ZBWIPPAZLEGAL           ENDLINE   #this is a reference to another device type
 SP06002026ZBWIPPAZLEGAL           ENDLINE   \i<POSTSCPT:LEGAL:ENDLINE>
 SP06001043ZBWIPPAZLEGAL           ENDPAGE   #this is a reference to another device type
 SP06002026ZBWIPPAZLEGAL           ENDPAGE   \i<POSTSCPT:LEGAL:ENDPAGE>
 SP06001043ZBWIPPAZLEGAL           LEAVE     #this is a reference to another device type
 SP06002024ZBWIPPAZLEGAL           LEAVE     \i<POSTSCPT:LEGAL:LEAVE>
 SP06001043ZBWIPPAZLEGAL           SETUP     #this is a reference to another device type
 SP06002026ZBWIPPAZLEGAL           SETUP     \i<POSTSCPT:LEGAL:SETUP>\n
 SP06003027ZBWIPPAZLEGAL           SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZLEGAL           SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZLEGAL           SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZLEGAL           SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZLEGAL           SETUP
 SP1DLETTER          LETTER  .S0000000000SAP         1997081213455640A BIN     SAP                                   SAP
 SP1XLETTER           000000000000000000000000
 SP06001006ZBWIPPAZLETTER          CONTROL     2 \n
 SP06002072ZBWIPPAZLETTER          CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZLETTER          CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZLETTER          CONTROL                                                                         \n
 SP06001043ZBWIPPAZLETTER          ENDLINE   #this is a reference to another device type
 SP06002027ZBWIPPAZLETTER          ENDLINE   \i<POSTSCPT:LETTER:ENDLINE>
 SP06001043ZBWIPPAZLETTER          ENDPAGE   #this is a reference to another device type
 SP06002027ZBWIPPAZLETTER          ENDPAGE   \i<POSTSCPT:LETTER:ENDPAGE>
 SP06001043ZBWIPPAZLETTER          LEAVE     #this is a reference to another device type
 SP06002025ZBWIPPAZLETTER          LEAVE     \i<POSTSCPT:LETTER:LEAVE>
 SP06001043ZBWIPPAZLETTER          SETUP     #this is a reference to another device type
 SP06002027ZBWIPPAZLETTER          SETUP     \i<POSTSCPT:LETTER:SETUP>\n
 SP06003027ZBWIPPAZLETTER          SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZLETTER          SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZLETTER          SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZLETTER          SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZLETTER          SETUP
 SP1DLINE_21         LINE_21 PS0000000000SAP         1997081213460440A BIN     SAP                                   SAP
 SP1XLINE_21          000000000000000000000000
 SP06001006ZBWIPPAZLINE_21         CONTROL     2 \n
 SP06002072ZBWIPPAZLINE_21         CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZLINE_21         CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZLINE_21         CONTROL                                                                         \n
 SP06001043ZBWIPPAZLINE_21         ENDLINE   #this is a reference to another device type
 SP06002028ZBWIPPAZLINE_21         ENDLINE   \i<POSTSCPT:LINE_21:ENDLINE>
 SP06001043ZBWIPPAZLINE_21         ENDPAGE   #this is a reference to another device type
 SP06002028ZBWIPPAZLINE_21         ENDPAGE   \i<POSTSCPT:LINE_21:ENDPAGE>
 SP06001043ZBWIPPAZLINE_21         LEAVE     #this is a reference to another device type
 SP06002026ZBWIPPAZLINE_21         LEAVE     \i<POSTSCPT:LINE_21:LEAVE>
 SP06001043ZBWIPPAZLINE_21         SETUP     #this is a reference to another device type
 SP06002028ZBWIPPAZLINE_21         SETUP     \i<POSTSCPT:LINE_21:SETUP>\n
 SP06003027ZBWIPPAZLINE_21         SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZLINE_21         SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZLINE_21         SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZLINE_21         SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZLINE_21         SETUP
 SP1DLINE_22         LINE_22 PS0000000000SAP         1997081213461140A BIN     SAP                                   SAP
 SP1XLINE_22          000000000000000000000000
 SP06001006ZBWIPPAZLINE_22         CONTROL     2 \n
 SP06002072ZBWIPPAZLINE_22         CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZLINE_22         CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZLINE_22         CONTROL                                                                         \n
 SP06001043ZBWIPPAZLINE_22         ENDLINE   #this is a reference to another device type
 SP06002028ZBWIPPAZLINE_22         ENDLINE   \i<POSTSCPT:LINE_22:ENDLINE>
 SP06001043ZBWIPPAZLINE_22         ENDPAGE   #this is a reference to another device type
 SP06002028ZBWIPPAZLINE_22         ENDPAGE   \i<POSTSCPT:LINE_22:ENDPAGE>
 SP06001043ZBWIPPAZLINE_22         LEAVE     #this is a reference to another device type
 SP06002026ZBWIPPAZLINE_22         LEAVE     \i<POSTSCPT:LINE_22:LEAVE>
 SP06001043ZBWIPPAZLINE_22         SETUP     #this is a reference to another device type
 SP06002028ZBWIPPAZLINE_22         SETUP     \i<POSTSCPT:LINE_22:SETUP>\n
 SP06003027ZBWIPPAZLINE_22         SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06004027ZBWIPPAZLINE_22         SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06005026ZBWIPPAZLINE_22         SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06006026ZBWIPPAZLINE_22         SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06007000ZBWIPPAZLINE_22         SETUP
 SP1DX_44_120        ANY     LL0012000044SAP         1998040710425340C BIN     SAP         1997081213463340A BIN     SAP
 SP1XX_44_120        M000000000000000000000000
 SP06001006ZBWIPPAZX_44_120        CONTROL     2 \n
 SP06002072ZBWIPPAZX_44_120        CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZX_44_120        CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZX_44_120        CONTROL                                                                         \n
 SP06001002ZBWIPPAZX_44_120        ENDLINE   \n
 SP06001011ZBWIPPAZX_44_120        ENDPAGE   # no action
 SP06001022ZBWIPPAZX_44_120        LEAVE     # CTRL-D to finish job
 SP06002005ZBWIPPAZX_44_120        LEAVE     \0x04
 SP06001007ZBWIPPAZX_44_120        SETUP     %!PS-\n
 SP06002029ZBWIPPAZX_44_120        SETUP     %%Creator: SAP R/3 rel.4.0C\n
 SP06003015ZBWIPPAZX_44_120        SETUP     %%EndComments\n
 SP06004022ZBWIPPAZX_44_120        SETUP     /SAPdict 12 dict def\n
 SP06005012ZBWIPPAZX_44_120        SETUP     /SAPencode\n
 SP06006017ZBWIPPAZX_44_120        SETUP     { SAPdict begin\n
 SP06007026ZBWIPPAZX_44_120        SETUP       /basefontname exch def\n
 SP06008025ZBWIPPAZX_44_120        SETUP       /SAPfontname exch def\n
 SP06009043ZBWIPPAZX_44_120        SETUP       /basefontdict basefontname findfont def\n
 SP06010049ZBWIPPAZX_44_120        SETUP       /SAPfont      basefontdict maxlength dict def\n
 SP06011016ZBWIPPAZX_44_120        SETUP       basefontdict\n
 SP06012022ZBWIPPAZX_44_120        SETUP       { exch dup /FID ne\n
 SP06013024ZBWIPPAZX_44_120        SETUP         { dup /Encoding eq\n
 SP06014059ZBWIPPAZX_44_120        SETUP           { exch dup length array copy SAPfont 3 1 roll put }\n
 SP06015037ZBWIPPAZX_44_120        SETUP           { exch SAPfont 3 1 roll put }\n
 SP06016016ZBWIPPAZX_44_120        SETUP           ifelse }\n
 SP06017017ZBWIPPAZX_44_120        SETUP         { pop pop }\n
 SP06018014ZBWIPPAZX_44_120        SETUP         ifelse }\n
 SP06019010ZBWIPPAZX_44_120        SETUP       forall\n
 SP06020037ZBWIPPAZX_44_120        SETUP       SAPfont /FontName SAPfontname put\n
 SP06021022ZBWIPPAZX_44_120        SETUP       SAPcodes aload pop\n
 SP06022026ZBWIPPAZX_44_120        SETUP       SAPcodes length 2 idiv\n
 SP06023051ZBWIPPAZX_44_120        SETUP         { SAPfont /Encoding get 3 1 roll put } repeat\n
 SP06024040ZBWIPPAZX_44_120        SETUP         SAPfontname SAPfont definefont pop\n
 SP06025011ZBWIPPAZX_44_120        SETUP     end } def\n
 SP06026016ZBWIPPAZX_44_120        SETUP     /SAPcodes mark\n
 SP06027014ZBWIPPAZX_44_120        SETUP     16#20 /space\n
 SP06028015ZBWIPPAZX_44_120        SETUP     16#21 /exclam\n
 SP06029017ZBWIPPAZX_44_120        SETUP     16#22 /quotedbl\n
 SP06030019ZBWIPPAZX_44_120        SETUP     16#23 /numbersign\n
 SP06031015ZBWIPPAZX_44_120        SETUP     16#24 /dollar\n
 SP06032016ZBWIPPAZX_44_120        SETUP     16#25 /percent\n
 SP06033018ZBWIPPAZX_44_120        SETUP     16#26 /ampersand\n
 SP06034019ZBWIPPAZX_44_120        SETUP     16#27 /quoteright\n
 SP06035018ZBWIPPAZX_44_120        SETUP     16#28 /parenleft\n
 SP06036019ZBWIPPAZX_44_120        SETUP     16#29 /parenright\n
 SP06037017ZBWIPPAZX_44_120        SETUP     16#2A /asterisk\n
 SP06038013ZBWIPPAZX_44_120        SETUP     16#2B /plus\n
 SP06039014ZBWIPPAZX_44_120        SETUP     16#2C /comma\n
 SP06040015ZBWIPPAZX_44_120        SETUP     16#2D /hyphen\n
 SP06041015ZBWIPPAZX_44_120        SETUP     16#2E /period\n
 SP06042014ZBWIPPAZX_44_120        SETUP     16#2F /slash\n
 SP06043013ZBWIPPAZX_44_120        SETUP     16#30 /zero\n
 SP06044012ZBWIPPAZX_44_120        SETUP     16#31 /one\n
 SP06045012ZBWIPPAZX_44_120        SETUP     16#32 /two\n
 SP06046014ZBWIPPAZX_44_120        SETUP     16#33 /three\n
 SP06047013ZBWIPPAZX_44_120        SETUP     16#34 /four\n
 SP06048013ZBWIPPAZX_44_120        SETUP     16#35 /five\n
 SP06049012ZBWIPPAZX_44_120        SETUP     16#36 /six\n
 SP06050014ZBWIPPAZX_44_120        SETUP     16#37 /seven\n
 SP06051014ZBWIPPAZX_44_120        SETUP     16#38 /eight\n
 SP06052013ZBWIPPAZX_44_120        SETUP     16#39 /nine\n
 SP06053014ZBWIPPAZX_44_120        SETUP     16#3A /colon\n
 SP06054018ZBWIPPAZX_44_120        SETUP     16#3B /semicolon\n
 SP06055013ZBWIPPAZX_44_120        SETUP     16#3C /less\n
 SP06056014ZBWIPPAZX_44_120        SETUP     16#3D /equal\n
 SP06057016ZBWIPPAZX_44_120        SETUP     16#3E /greater\n
 SP06058017ZBWIPPAZX_44_120        SETUP     16#3F /question\n
 SP06059011ZBWIPPAZX_44_120        SETUP     16#40 /at\n
 SP06060070ZBWIPPAZX_44_120        SETUP     16#41 /A  16#42 /B  16#43 /C  16#44 /D  16#45 /E  16#46 /F  16#47 /G\n
 SP06061070ZBWIPPAZX_44_120        SETUP     16#48 /H  16#49 /I  16#4A /J  16#4B /K  16#4C /L  16#4D /M  16#4E /N\n
 SP06062070ZBWIPPAZX_44_120        SETUP     16#4F /O  16#50 /P  16#51 /Q  16#52 /R  16#53 /S  16#54 /T  16#55 /U\n
 SP06063050ZBWIPPAZX_44_120        SETUP     16#56 /V  16#57 /W  16#58 /X  16#59 /Y  16#5A /Z\n
 SP06064020ZBWIPPAZX_44_120        SETUP     16#5B /bracketleft\n
 SP06065018ZBWIPPAZX_44_120        SETUP     16#5C /backslash\n
 SP06066021ZBWIPPAZX_44_120        SETUP     16#5D /bracketright\n
 SP06067020ZBWIPPAZX_44_120        SETUP     16#5E /asciicircum\n
 SP06068019ZBWIPPAZX_44_120        SETUP     16#5F /underscore\n
 SP06069018ZBWIPPAZX_44_120        SETUP     16#60 /quoteleft\n
 SP06070070ZBWIPPAZX_44_120        SETUP     16#61 /a  16#62 /b  16#63 /c  16#64 /d  16#65 /e  16#66 /f  16#67 /g\n
 SP06071070ZBWIPPAZX_44_120        SETUP     16#68 /h  16#69 /i  16#6A /j  16#6B /k  16#6C /l  16#6D /m  16#6E /n\n
 SP06072070ZBWIPPAZX_44_120        SETUP     16#6F /o  16#70 /p  16#71 /q  16#72 /r  16#73 /s  16#74 /t  16#75 /u\n
 SP06073050ZBWIPPAZX_44_120        SETUP     16#76 /v  16#77 /w  16#78 /x  16#79 /y  16#7A /z\n
 SP06074018ZBWIPPAZX_44_120        SETUP     16#7B /braceleft\n
 SP06075012ZBWIPPAZX_44_120        SETUP     16#7C /bar\n
 SP06076019ZBWIPPAZX_44_120        SETUP     16#7D /braceright\n
 SP06077019ZBWIPPAZX_44_120        SETUP     16#7E /asciitilde\n
 SP06078066ZBWIPPAZX_44_120        SETUP     16#80 /grave  16#81 /acute    16#82 /circumflex     16#83 /tilde\n
 SP06079069ZBWIPPAZX_44_120        SETUP     16#84 /ogonek 16#85 /breve    16#86 /dotaccent      16#87 /dieresis\n
 SP06080066ZBWIPPAZX_44_120        SETUP     16#88 /ring   16#89 /cedilla  16#8A /hungarumlaut   16#8B /caron\n
 SP06081019ZBWIPPAZX_44_120        SETUP     16#A1 /exclamdown\n
 SP06082013ZBWIPPAZX_44_120        SETUP     16#A2 /cent\n
 SP06083017ZBWIPPAZX_44_120        SETUP     16#A3 /sterling\n
 SP06084017ZBWIPPAZX_44_120        SETUP     16#A4 /currency\n
 SP06085012ZBWIPPAZX_44_120        SETUP     16#A5 /yen\n
 SP06086018ZBWIPPAZX_44_120        SETUP     16#A6 /brokenbar\n
 SP06087016ZBWIPPAZX_44_120        SETUP     16#A7 /section\n
 SP06088017ZBWIPPAZX_44_120        SETUP     16#A8 /dieresis\n
 SP06089018ZBWIPPAZX_44_120        SETUP     16#A9 /copyright\n
 SP06090020ZBWIPPAZX_44_120        SETUP     16#AA /ordfeminine\n
 SP06091022ZBWIPPAZX_44_120        SETUP     16#AB /guillemotleft\n
 SP06092019ZBWIPPAZX_44_120        SETUP     16#AC /logicalnot\n
 SP06093014ZBWIPPAZX_44_120        SETUP     16#AD /minus\n
 SP06094019ZBWIPPAZX_44_120        SETUP     16#AE /registered\n
 SP06095015ZBWIPPAZX_44_120        SETUP     16#AF /macron\n
 SP06096015ZBWIPPAZX_44_120        SETUP     16#B0 /degree\n
 SP06097018ZBWIPPAZX_44_120        SETUP     16#B1 /plusminus\n
 SP06098020ZBWIPPAZX_44_120        SETUP     16#B2 /twosuperior\n
 SP06099022ZBWIPPAZX_44_120        SETUP     16#B3 /threesuperior\n
 SP06100020ZBWIPPAZX_44_120        SETUP     16#B4 /quotesingle\n
 SP06101011ZBWIPPAZX_44_120        SETUP     16#B5 /mu\n
 SP06102018ZBWIPPAZX_44_120        SETUP     16#B6 /paragraph\n
 SP06103023ZBWIPPAZX_44_120        SETUP     16#B7 /periodcentered\n
 SP06104016ZBWIPPAZX_44_120        SETUP     16#B8 /cedilla\n
 SP06105020ZBWIPPAZX_44_120        SETUP     16#B9 /onesuperior\n
 SP06106021ZBWIPPAZX_44_120        SETUP     16#BA /ordmasculine\n
 SP06107023ZBWIPPAZX_44_120        SETUP     16#BB /guillemotright\n
 SP06108019ZBWIPPAZX_44_120        SETUP     16#BC /onequarter\n
 SP06109016ZBWIPPAZX_44_120        SETUP     16#BD /onehalf\n
 SP06110022ZBWIPPAZX_44_120        SETUP     16#BE /threequarters\n
 SP06111021ZBWIPPAZX_44_120        SETUP     16#BF /questiondown\n
 SP06112015ZBWIPPAZX_44_120        SETUP     16#C0 /Agrave\n
 SP06113015ZBWIPPAZX_44_120        SETUP     16#C1 /Aacute\n
 SP06114020ZBWIPPAZX_44_120        SETUP     16#C2 /Acircumflex\n
 SP06115015ZBWIPPAZX_44_120        SETUP     16#C3 /Atilde\n
 SP06116018ZBWIPPAZX_44_120        SETUP     16#C4 /Adieresis\n
 SP06117014ZBWIPPAZX_44_120        SETUP     16#C5 /Aring\n
 SP06118011ZBWIPPAZX_44_120        SETUP     16#C6 /AE\n
 SP06119017ZBWIPPAZX_44_120        SETUP     16#C7 /Ccedilla\n
 SP06120015ZBWIPPAZX_44_120        SETUP     16#C8 /Egrave\n
 SP06121015ZBWIPPAZX_44_120        SETUP     16#C9 /Eacute\n
 SP06122020ZBWIPPAZX_44_120        SETUP     16#CA /Ecircumflex\n
 SP06123018ZBWIPPAZX_44_120        SETUP     16#CB /Edieresis\n
 SP06124015ZBWIPPAZX_44_120        SETUP     16#CC /Igrave\n
 SP06125015ZBWIPPAZX_44_120        SETUP     16#CD /Iacute\n
 SP06126020ZBWIPPAZX_44_120        SETUP     16#CE /Icircumflex\n
 SP06127018ZBWIPPAZX_44_120        SETUP     16#CF /Idieresis\n
 SP06128012ZBWIPPAZX_44_120        SETUP     16#D0 /Eth\n
 SP06129015ZBWIPPAZX_44_120        SETUP     16#D1 /Ntilde\n
 SP06130015ZBWIPPAZX_44_120        SETUP     16#D2 /Ograve\n
 SP06131015ZBWIPPAZX_44_120        SETUP     16#D3 /Oacute\n
 SP06132020ZBWIPPAZX_44_120        SETUP     16#D4 /Ocircumflex\n
 SP06133015ZBWIPPAZX_44_120        SETUP     16#D5 /Otilde\n
 SP06134018ZBWIPPAZX_44_120        SETUP     16#D6 /Odieresis\n
 SP06135017ZBWIPPAZX_44_120        SETUP     16#D7 /multiply\n
 SP06136015ZBWIPPAZX_44_120        SETUP     16#D8 /Oslash\n
 SP06137015ZBWIPPAZX_44_120        SETUP     16#D9 /Ugrave\n
 SP06138015ZBWIPPAZX_44_120        SETUP     16#DA /Uacute\n
 SP06139020ZBWIPPAZX_44_120        SETUP     16#DB /Ucircumflex\n
 SP06140018ZBWIPPAZX_44_120        SETUP     16#DC /Udieresis\n
 SP06141015ZBWIPPAZX_44_120        SETUP     16#DD /Yacute\n
 SP06142014ZBWIPPAZX_44_120        SETUP     16#DE /Thorn\n
 SP06143019ZBWIPPAZX_44_120        SETUP     16#DF /germandbls\n
 SP06144015ZBWIPPAZX_44_120        SETUP     16#E0 /agrave\n
 SP06145015ZBWIPPAZX_44_120        SETUP     16#E1 /aacute\n
 SP06146020ZBWIPPAZX_44_120        SETUP     16#E2 /acircumflex\n
 SP06147015ZBWIPPAZX_44_120        SETUP     16#E3 /atilde\n
 SP06148018ZBWIPPAZX_44_120        SETUP     16#E4 /adieresis\n
 SP06149014ZBWIPPAZX_44_120        SETUP     16#E5 /aring\n
 SP06150011ZBWIPPAZX_44_120        SETUP     16#E6 /ae\n
 SP06151017ZBWIPPAZX_44_120        SETUP     16#E7 /ccedilla\n
 SP06152015ZBWIPPAZX_44_120        SETUP     16#E8 /egrave\n
 SP06153015ZBWIPPAZX_44_120        SETUP     16#E9 /eacute\n
 SP06154020ZBWIPPAZX_44_120        SETUP     16#EA /ecircumflex\n
 SP06155018ZBWIPPAZX_44_120        SETUP     16#EB /edieresis\n
 SP06156015ZBWIPPAZX_44_120        SETUP     16#EC /igrave\n
 SP06157015ZBWIPPAZX_44_120        SETUP     16#ED /iacute\n
 SP06158020ZBWIPPAZX_44_120        SETUP     16#EE /icircumflex\n
 SP06159018ZBWIPPAZX_44_120        SETUP     16#EF /idieresis\n
 SP06160012ZBWIPPAZX_44_120        SETUP     16#F0 /eth\n
 SP06161015ZBWIPPAZX_44_120        SETUP     16#F1 /ntilde\n
 SP06162015ZBWIPPAZX_44_120        SETUP     16#F2 /ograve\n
 SP06163015ZBWIPPAZX_44_120        SETUP     16#F3 /oacute\n
 SP06164020ZBWIPPAZX_44_120        SETUP     16#F4 /ocircumflex\n
 SP06165015ZBWIPPAZX_44_120        SETUP     16#F5 /otilde\n
 SP06166018ZBWIPPAZX_44_120        SETUP     16#F6 /odieresis\n
 SP06167015ZBWIPPAZX_44_120        SETUP     16#F7 /divide\n
 SP06168015ZBWIPPAZX_44_120        SETUP     16#F8 /oslash\n
 SP06169015ZBWIPPAZX_44_120        SETUP     16#F9 /ugrave\n
 SP06170015ZBWIPPAZX_44_120        SETUP     16#FA /uacute\n
 SP06171020ZBWIPPAZX_44_120        SETUP     16#FB /ucircumflex\n
 SP06172018ZBWIPPAZX_44_120        SETUP     16#FC /udieresis\n
 SP06173015ZBWIPPAZX_44_120        SETUP     16#FD /yacute\n
 SP06174014ZBWIPPAZX_44_120        SETUP     16#FE /thorn\n
 SP06175018ZBWIPPAZX_44_120        SETUP     16#FF /ydieresis\n
 SP06176039ZBWIPPAZX_44_120        SETUP     counttomark array astore exch pop def\n
 SP06177055ZBWIPPAZX_44_120        SETUP     % utility functions used by list printer driver POST:\n
 SP06178021ZBWIPPAZX_44_120        SETUP     /PrintModeSimplex {\n
 SP06179021ZBWIPPAZX_44_120        SETUP       <</Duplex false>>\n
 SP06180017ZBWIPPAZX_44_120        SETUP       setpagedevice\n
 SP06181007ZBWIPPAZX_44_120        SETUP     } def\n
 SP06182020ZBWIPPAZX_44_120        SETUP     /PrintModeDuplex {\n
 SP06183034ZBWIPPAZX_44_120        SETUP       <</Duplex true /Tumble false>>\n
 SP06184017ZBWIPPAZX_44_120        SETUP       setpagedevice\n
 SP06185007ZBWIPPAZX_44_120        SETUP     } def\n
 SP06186026ZBWIPPAZX_44_120        SETUP     /PrintModeTumbleDuplex {\n
 SP06187033ZBWIPPAZX_44_120        SETUP       <</Duplex true /Tumble true>>\n
 SP06188017ZBWIPPAZX_44_120        SETUP       setpagedevice\n
 SP06189007ZBWIPPAZX_44_120        SETUP     } def\n
 SP06190013ZBWIPPAZX_44_120        SETUP     /InputTray1 {
 SP06191053ZBWIPPAZX_44_120        SETUP       <</DeferredMediaSelection true /MediaPosition 0>>\n
 SP06192017ZBWIPPAZX_44_120        SETUP       setpagedevice\n
 SP06193007ZBWIPPAZX_44_120        SETUP     } def\n
 SP06194013ZBWIPPAZX_44_120        SETUP     /InputTray2 {
 SP06195053ZBWIPPAZX_44_120        SETUP       <</DeferredMediaSelection true /MediaPosition 1>>\n
 SP06196017ZBWIPPAZX_44_120        SETUP       setpagedevice\n
 SP06197007ZBWIPPAZX_44_120        SETUP     } def\n
 SP06198013ZBWIPPAZX_44_120        SETUP     /InputTray3 {
 SP06199053ZBWIPPAZX_44_120        SETUP       <</DeferredMediaSelection true /MediaPosition 2>>\n
 SP06200017ZBWIPPAZX_44_120        SETUP       setpagedevice\n
 SP06201007ZBWIPPAZX_44_120        SETUP     } def\n
 SP06202015ZBWIPPAZX_44_120        SETUP     /InputTrayMan {
 SP06203053ZBWIPPAZX_44_120        SETUP       <</DeferredMediaSelection true /ManualFeed true>>\n
 SP06204017ZBWIPPAZX_44_120        SETUP       setpagedevice\n
 SP06205007ZBWIPPAZX_44_120        SETUP     } def\n
 SP06206013ZBWIPPAZX_44_120        SETUP     %%EndProlog\n
 SP06207027ZBWIPPAZX_44_120        SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06208027ZBWIPPAZX_44_120        SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06209026ZBWIPPAZX_44_120        SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06210026ZBWIPPAZX_44_120        SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06211000ZBWIPPAZX_44_120        SETUP
 SP1DX_58_170        ANY     LL0017000058SAP         1998040710430640C BIN     SAP         1997081213492140A BIN     SAP
 SP1XX_58_170        M000000000000000000000000
 SP06001006ZBWIPPAZX_58_170        CONTROL     2 \n
 SP06002072ZBWIPPAZX_58_170        CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZX_58_170        CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZX_58_170        CONTROL                                                                         \n
 SP06001002ZBWIPPAZX_58_170        ENDLINE   \n
 SP06001011ZBWIPPAZX_58_170        ENDPAGE   # no action
 SP06001022ZBWIPPAZX_58_170        LEAVE     # CTRL-D to finish job
 SP06002005ZBWIPPAZX_58_170        LEAVE     \0x04
 SP06001007ZBWIPPAZX_58_170        SETUP     %!PS-\n
 SP06002029ZBWIPPAZX_58_170        SETUP     %%Creator: SAP R/3 rel.4.0C\n
 SP06003015ZBWIPPAZX_58_170        SETUP     %%EndComments\n
 SP06004022ZBWIPPAZX_58_170        SETUP     /SAPdict 12 dict def\n
 SP06005012ZBWIPPAZX_58_170        SETUP     /SAPencode\n
 SP06006017ZBWIPPAZX_58_170        SETUP     { SAPdict begin\n
 SP06007026ZBWIPPAZX_58_170        SETUP       /basefontname exch def\n
 SP06008025ZBWIPPAZX_58_170        SETUP       /SAPfontname exch def\n
 SP06009043ZBWIPPAZX_58_170        SETUP       /basefontdict basefontname findfont def\n
 SP06010049ZBWIPPAZX_58_170        SETUP       /SAPfont      basefontdict maxlength dict def\n
 SP06011016ZBWIPPAZX_58_170        SETUP       basefontdict\n
 SP06012022ZBWIPPAZX_58_170        SETUP       { exch dup /FID ne\n
 SP06013024ZBWIPPAZX_58_170        SETUP         { dup /Encoding eq\n
 SP06014059ZBWIPPAZX_58_170        SETUP           { exch dup length array copy SAPfont 3 1 roll put }\n
 SP06015037ZBWIPPAZX_58_170        SETUP           { exch SAPfont 3 1 roll put }\n
 SP06016016ZBWIPPAZX_58_170        SETUP           ifelse }\n
 SP06017017ZBWIPPAZX_58_170        SETUP         { pop pop }\n
 SP06018014ZBWIPPAZX_58_170        SETUP         ifelse }\n
 SP06019010ZBWIPPAZX_58_170        SETUP       forall\n
 SP06020037ZBWIPPAZX_58_170        SETUP       SAPfont /FontName SAPfontname put\n
 SP06021022ZBWIPPAZX_58_170        SETUP       SAPcodes aload pop\n
 SP06022026ZBWIPPAZX_58_170        SETUP       SAPcodes length 2 idiv\n
 SP06023051ZBWIPPAZX_58_170        SETUP         { SAPfont /Encoding get 3 1 roll put } repeat\n
 SP06024040ZBWIPPAZX_58_170        SETUP         SAPfontname SAPfont definefont pop\n
 SP06025011ZBWIPPAZX_58_170        SETUP     end } def\n
 SP06026016ZBWIPPAZX_58_170        SETUP     /SAPcodes mark\n
 SP06027014ZBWIPPAZX_58_170        SETUP     16#20 /space\n
 SP06028015ZBWIPPAZX_58_170        SETUP     16#21 /exclam\n
 SP06029017ZBWIPPAZX_58_170        SETUP     16#22 /quotedbl\n
 SP06030019ZBWIPPAZX_58_170        SETUP     16#23 /numbersign\n
 SP06031015ZBWIPPAZX_58_170        SETUP     16#24 /dollar\n
 SP06032016ZBWIPPAZX_58_170        SETUP     16#25 /percent\n
 SP06033018ZBWIPPAZX_58_170        SETUP     16#26 /ampersand\n
 SP06034019ZBWIPPAZX_58_170        SETUP     16#27 /quoteright\n
 SP06035018ZBWIPPAZX_58_170        SETUP     16#28 /parenleft\n
 SP06036019ZBWIPPAZX_58_170        SETUP     16#29 /parenright\n
 SP06037017ZBWIPPAZX_58_170        SETUP     16#2A /asterisk\n
 SP06038013ZBWIPPAZX_58_170        SETUP     16#2B /plus\n
 SP06039014ZBWIPPAZX_58_170        SETUP     16#2C /comma\n
 SP06040015ZBWIPPAZX_58_170        SETUP     16#2D /hyphen\n
 SP06041015ZBWIPPAZX_58_170        SETUP     16#2E /period\n
 SP06042014ZBWIPPAZX_58_170        SETUP     16#2F /slash\n
 SP06043013ZBWIPPAZX_58_170        SETUP     16#30 /zero\n
 SP06044012ZBWIPPAZX_58_170        SETUP     16#31 /one\n
 SP06045012ZBWIPPAZX_58_170        SETUP     16#32 /two\n
 SP06046014ZBWIPPAZX_58_170        SETUP     16#33 /three\n
 SP06047013ZBWIPPAZX_58_170        SETUP     16#34 /four\n
 SP06048013ZBWIPPAZX_58_170        SETUP     16#35 /five\n
 SP06049012ZBWIPPAZX_58_170        SETUP     16#36 /six\n
 SP06050014ZBWIPPAZX_58_170        SETUP     16#37 /seven\n
 SP06051014ZBWIPPAZX_58_170        SETUP     16#38 /eight\n
 SP06052013ZBWIPPAZX_58_170        SETUP     16#39 /nine\n
 SP06053014ZBWIPPAZX_58_170        SETUP     16#3A /colon\n
 SP06054018ZBWIPPAZX_58_170        SETUP     16#3B /semicolon\n
 SP06055013ZBWIPPAZX_58_170        SETUP     16#3C /less\n
 SP06056014ZBWIPPAZX_58_170        SETUP     16#3D /equal\n
 SP06057016ZBWIPPAZX_58_170        SETUP     16#3E /greater\n
 SP06058017ZBWIPPAZX_58_170        SETUP     16#3F /question\n
 SP06059011ZBWIPPAZX_58_170        SETUP     16#40 /at\n
 SP06060070ZBWIPPAZX_58_170        SETUP     16#41 /A  16#42 /B  16#43 /C  16#44 /D  16#45 /E  16#46 /F  16#47 /G\n
 SP06061070ZBWIPPAZX_58_170        SETUP     16#48 /H  16#49 /I  16#4A /J  16#4B /K  16#4C /L  16#4D /M  16#4E /N\n
 SP06062070ZBWIPPAZX_58_170        SETUP     16#4F /O  16#50 /P  16#51 /Q  16#52 /R  16#53 /S  16#54 /T  16#55 /U\n
 SP06063050ZBWIPPAZX_58_170        SETUP     16#56 /V  16#57 /W  16#58 /X  16#59 /Y  16#5A /Z\n
 SP06064020ZBWIPPAZX_58_170        SETUP     16#5B /bracketleft\n
 SP06065018ZBWIPPAZX_58_170        SETUP     16#5C /backslash\n
 SP06066021ZBWIPPAZX_58_170        SETUP     16#5D /bracketright\n
 SP06067020ZBWIPPAZX_58_170        SETUP     16#5E /asciicircum\n
 SP06068019ZBWIPPAZX_58_170        SETUP     16#5F /underscore\n
 SP06069018ZBWIPPAZX_58_170        SETUP     16#60 /quoteleft\n
 SP06070070ZBWIPPAZX_58_170        SETUP     16#61 /a  16#62 /b  16#63 /c  16#64 /d  16#65 /e  16#66 /f  16#67 /g\n
 SP06071070ZBWIPPAZX_58_170        SETUP     16#68 /h  16#69 /i  16#6A /j  16#6B /k  16#6C /l  16#6D /m  16#6E /n\n
 SP06072070ZBWIPPAZX_58_170        SETUP     16#6F /o  16#70 /p  16#71 /q  16#72 /r  16#73 /s  16#74 /t  16#75 /u\n
 SP06073050ZBWIPPAZX_58_170        SETUP     16#76 /v  16#77 /w  16#78 /x  16#79 /y  16#7A /z\n
 SP06074018ZBWIPPAZX_58_170        SETUP     16#7B /braceleft\n
 SP06075012ZBWIPPAZX_58_170        SETUP     16#7C /bar\n
 SP06076019ZBWIPPAZX_58_170        SETUP     16#7D /braceright\n
 SP06077019ZBWIPPAZX_58_170        SETUP     16#7E /asciitilde\n
 SP06078066ZBWIPPAZX_58_170        SETUP     16#80 /grave  16#81 /acute    16#82 /circumflex     16#83 /tilde\n
 SP06079069ZBWIPPAZX_58_170        SETUP     16#84 /ogonek 16#85 /breve    16#86 /dotaccent      16#87 /dieresis\n
 SP06080066ZBWIPPAZX_58_170        SETUP     16#88 /ring   16#89 /cedilla  16#8A /hungarumlaut   16#8B /caron\n
 SP06081019ZBWIPPAZX_58_170        SETUP     16#A1 /exclamdown\n
 SP06082013ZBWIPPAZX_58_170        SETUP     16#A2 /cent\n
 SP06083017ZBWIPPAZX_58_170        SETUP     16#A3 /sterling\n
 SP06084017ZBWIPPAZX_58_170        SETUP     16#A4 /currency\n
 SP06085012ZBWIPPAZX_58_170        SETUP     16#A5 /yen\n
 SP06086018ZBWIPPAZX_58_170        SETUP     16#A6 /brokenbar\n
 SP06087016ZBWIPPAZX_58_170        SETUP     16#A7 /section\n
 SP06088017ZBWIPPAZX_58_170        SETUP     16#A8 /dieresis\n
 SP06089018ZBWIPPAZX_58_170        SETUP     16#A9 /copyright\n
 SP06090020ZBWIPPAZX_58_170        SETUP     16#AA /ordfeminine\n
 SP06091022ZBWIPPAZX_58_170        SETUP     16#AB /guillemotleft\n
 SP06092019ZBWIPPAZX_58_170        SETUP     16#AC /logicalnot\n
 SP06093014ZBWIPPAZX_58_170        SETUP     16#AD /minus\n
 SP06094019ZBWIPPAZX_58_170        SETUP     16#AE /registered\n
 SP06095015ZBWIPPAZX_58_170        SETUP     16#AF /macron\n
 SP06096015ZBWIPPAZX_58_170        SETUP     16#B0 /degree\n
 SP06097018ZBWIPPAZX_58_170        SETUP     16#B1 /plusminus\n
 SP06098020ZBWIPPAZX_58_170        SETUP     16#B2 /twosuperior\n
 SP06099022ZBWIPPAZX_58_170        SETUP     16#B3 /threesuperior\n
 SP06100020ZBWIPPAZX_58_170        SETUP     16#B4 /quotesingle\n
 SP06101011ZBWIPPAZX_58_170        SETUP     16#B5 /mu\n
 SP06102018ZBWIPPAZX_58_170        SETUP     16#B6 /paragraph\n
 SP06103023ZBWIPPAZX_58_170        SETUP     16#B7 /periodcentered\n
 SP06104016ZBWIPPAZX_58_170        SETUP     16#B8 /cedilla\n
 SP06105020ZBWIPPAZX_58_170        SETUP     16#B9 /onesuperior\n
 SP06106021ZBWIPPAZX_58_170        SETUP     16#BA /ordmasculine\n
 SP06107023ZBWIPPAZX_58_170        SETUP     16#BB /guillemotright\n
 SP06108019ZBWIPPAZX_58_170        SETUP     16#BC /onequarter\n
 SP06109016ZBWIPPAZX_58_170        SETUP     16#BD /onehalf\n
 SP06110022ZBWIPPAZX_58_170        SETUP     16#BE /threequarters\n
 SP06111021ZBWIPPAZX_58_170        SETUP     16#BF /questiondown\n
 SP06112015ZBWIPPAZX_58_170        SETUP     16#C0 /Agrave\n
 SP06113015ZBWIPPAZX_58_170        SETUP     16#C1 /Aacute\n
 SP06114020ZBWIPPAZX_58_170        SETUP     16#C2 /Acircumflex\n
 SP06115015ZBWIPPAZX_58_170        SETUP     16#C3 /Atilde\n
 SP06116018ZBWIPPAZX_58_170        SETUP     16#C4 /Adieresis\n
 SP06117014ZBWIPPAZX_58_170        SETUP     16#C5 /Aring\n
 SP06118011ZBWIPPAZX_58_170        SETUP     16#C6 /AE\n
 SP06119017ZBWIPPAZX_58_170        SETUP     16#C7 /Ccedilla\n
 SP06120015ZBWIPPAZX_58_170        SETUP     16#C8 /Egrave\n
 SP06121015ZBWIPPAZX_58_170        SETUP     16#C9 /Eacute\n
 SP06122020ZBWIPPAZX_58_170        SETUP     16#CA /Ecircumflex\n
 SP06123018ZBWIPPAZX_58_170        SETUP     16#CB /Edieresis\n
 SP06124015ZBWIPPAZX_58_170        SETUP     16#CC /Igrave\n
 SP06125015ZBWIPPAZX_58_170        SETUP     16#CD /Iacute\n
 SP06126020ZBWIPPAZX_58_170        SETUP     16#CE /Icircumflex\n
 SP06127018ZBWIPPAZX_58_170        SETUP     16#CF /Idieresis\n
 SP06128012ZBWIPPAZX_58_170        SETUP     16#D0 /Eth\n
 SP06129015ZBWIPPAZX_58_170        SETUP     16#D1 /Ntilde\n
 SP06130015ZBWIPPAZX_58_170        SETUP     16#D2 /Ograve\n
 SP06131015ZBWIPPAZX_58_170        SETUP     16#D3 /Oacute\n
 SP06132020ZBWIPPAZX_58_170        SETUP     16#D4 /Ocircumflex\n
 SP06133015ZBWIPPAZX_58_170        SETUP     16#D5 /Otilde\n
 SP06134018ZBWIPPAZX_58_170        SETUP     16#D6 /Odieresis\n
 SP06135017ZBWIPPAZX_58_170        SETUP     16#D7 /multiply\n
 SP06136015ZBWIPPAZX_58_170        SETUP     16#D8 /Oslash\n
 SP06137015ZBWIPPAZX_58_170        SETUP     16#D9 /Ugrave\n
 SP06138015ZBWIPPAZX_58_170        SETUP     16#DA /Uacute\n
 SP06139020ZBWIPPAZX_58_170        SETUP     16#DB /Ucircumflex\n
 SP06140018ZBWIPPAZX_58_170        SETUP     16#DC /Udieresis\n
 SP06141015ZBWIPPAZX_58_170        SETUP     16#DD /Yacute\n
 SP06142014ZBWIPPAZX_58_170        SETUP     16#DE /Thorn\n
 SP06143019ZBWIPPAZX_58_170        SETUP     16#DF /germandbls\n
 SP06144015ZBWIPPAZX_58_170        SETUP     16#E0 /agrave\n
 SP06145015ZBWIPPAZX_58_170        SETUP     16#E1 /aacute\n
 SP06146020ZBWIPPAZX_58_170        SETUP     16#E2 /acircumflex\n
 SP06147015ZBWIPPAZX_58_170        SETUP     16#E3 /atilde\n
 SP06148018ZBWIPPAZX_58_170        SETUP     16#E4 /adieresis\n
 SP06149014ZBWIPPAZX_58_170        SETUP     16#E5 /aring\n
 SP06150011ZBWIPPAZX_58_170        SETUP     16#E6 /ae\n
 SP06151017ZBWIPPAZX_58_170        SETUP     16#E7 /ccedilla\n
 SP06152015ZBWIPPAZX_58_170        SETUP     16#E8 /egrave\n
 SP06153015ZBWIPPAZX_58_170        SETUP     16#E9 /eacute\n
 SP06154020ZBWIPPAZX_58_170        SETUP     16#EA /ecircumflex\n
 SP06155018ZBWIPPAZX_58_170        SETUP     16#EB /edieresis\n
 SP06156015ZBWIPPAZX_58_170        SETUP     16#EC /igrave\n
 SP06157015ZBWIPPAZX_58_170        SETUP     16#ED /iacute\n
 SP06158020ZBWIPPAZX_58_170        SETUP     16#EE /icircumflex\n
 SP06159018ZBWIPPAZX_58_170        SETUP     16#EF /idieresis\n
 SP06160012ZBWIPPAZX_58_170        SETUP     16#F0 /eth\n
 SP06161015ZBWIPPAZX_58_170        SETUP     16#F1 /ntilde\n
 SP06162015ZBWIPPAZX_58_170        SETUP     16#F2 /ograve\n
 SP06163015ZBWIPPAZX_58_170        SETUP     16#F3 /oacute\n
 SP06164020ZBWIPPAZX_58_170        SETUP     16#F4 /ocircumflex\n
 SP06165015ZBWIPPAZX_58_170        SETUP     16#F5 /otilde\n
 SP06166018ZBWIPPAZX_58_170        SETUP     16#F6 /odieresis\n
 SP06167015ZBWIPPAZX_58_170        SETUP     16#F7 /divide\n
 SP06168015ZBWIPPAZX_58_170        SETUP     16#F8 /oslash\n
 SP06169015ZBWIPPAZX_58_170        SETUP     16#F9 /ugrave\n
 SP06170015ZBWIPPAZX_58_170        SETUP     16#FA /uacute\n
 SP06171020ZBWIPPAZX_58_170        SETUP     16#FB /ucircumflex\n
 SP06172018ZBWIPPAZX_58_170        SETUP     16#FC /udieresis\n
 SP06173015ZBWIPPAZX_58_170        SETUP     16#FD /yacute\n
 SP06174014ZBWIPPAZX_58_170        SETUP     16#FE /thorn\n
 SP06175018ZBWIPPAZX_58_170        SETUP     16#FF /ydieresis\n
 SP06176039ZBWIPPAZX_58_170        SETUP     counttomark array astore exch pop def\n
 SP06177055ZBWIPPAZX_58_170        SETUP     % utility functions used by list printer driver POST:\n
 SP06178021ZBWIPPAZX_58_170        SETUP     /PrintModeSimplex {\n
 SP06179021ZBWIPPAZX_58_170        SETUP       <</Duplex false>>\n
 SP06180017ZBWIPPAZX_58_170        SETUP       setpagedevice\n
 SP06181007ZBWIPPAZX_58_170        SETUP     } def\n
 SP06182020ZBWIPPAZX_58_170        SETUP     /PrintModeDuplex {\n
 SP06183034ZBWIPPAZX_58_170        SETUP       <</Duplex true /Tumble false>>\n
 SP06184017ZBWIPPAZX_58_170        SETUP       setpagedevice\n
 SP06185007ZBWIPPAZX_58_170        SETUP     } def\n
 SP06186026ZBWIPPAZX_58_170        SETUP     /PrintModeTumbleDuplex {\n
 SP06187033ZBWIPPAZX_58_170        SETUP       <</Duplex true /Tumble true>>\n
 SP06188017ZBWIPPAZX_58_170        SETUP       setpagedevice\n
 SP06189007ZBWIPPAZX_58_170        SETUP     } def\n
 SP06190013ZBWIPPAZX_58_170        SETUP     /InputTray1 {
 SP06191053ZBWIPPAZX_58_170        SETUP       <</DeferredMediaSelection true /MediaPosition 0>>\n
 SP06192017ZBWIPPAZX_58_170        SETUP       setpagedevice\n
 SP06193007ZBWIPPAZX_58_170        SETUP     } def\n
 SP06194013ZBWIPPAZX_58_170        SETUP     /InputTray2 {
 SP06195053ZBWIPPAZX_58_170        SETUP       <</DeferredMediaSelection true /MediaPosition 1>>\n
 SP06196017ZBWIPPAZX_58_170        SETUP       setpagedevice\n
 SP06197007ZBWIPPAZX_58_170        SETUP     } def\n
 SP06198013ZBWIPPAZX_58_170        SETUP     /InputTray3 {
 SP06199053ZBWIPPAZX_58_170        SETUP       <</DeferredMediaSelection true /MediaPosition 2>>\n
 SP06200017ZBWIPPAZX_58_170        SETUP       setpagedevice\n
 SP06201007ZBWIPPAZX_58_170        SETUP     } def\n
 SP06202015ZBWIPPAZX_58_170        SETUP     /InputTrayMan {
 SP06203053ZBWIPPAZX_58_170        SETUP       <</DeferredMediaSelection true /ManualFeed true>>\n
 SP06204017ZBWIPPAZX_58_170        SETUP       setpagedevice\n
 SP06205007ZBWIPPAZX_58_170        SETUP     } def\n
 SP06206013ZBWIPPAZX_58_170        SETUP     %%EndProlog\n
 SP06207027ZBWIPPAZX_58_170        SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06208027ZBWIPPAZX_58_170        SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06209026ZBWIPPAZX_58_170        SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06210026ZBWIPPAZX_58_170        SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06211000ZBWIPPAZX_58_170        SETUP
 SP1DX_65_132        ANY     LL0013200065SAP         1998040710432140C BIN     SAP         1997081213583340A BIN     SAP
 SP1XX_65_132        M000000000000000000000000
 SP06001006ZBWIPPAZX_65_132        CONTROL     2 \n
 SP06002072ZBWIPPAZX_65_132        CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZX_65_132        CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZX_65_132        CONTROL                                                                         \n
 SP06001002ZBWIPPAZX_65_132        ENDLINE   \n
 SP06001011ZBWIPPAZX_65_132        ENDPAGE   # no action
 SP06001022ZBWIPPAZX_65_132        LEAVE     # CTRL-D to finish job
 SP06002005ZBWIPPAZX_65_132        LEAVE     \0x04
 SP06001007ZBWIPPAZX_65_132        SETUP     %!PS-\n
 SP06002029ZBWIPPAZX_65_132        SETUP     %%Creator: SAP R/3 rel.4.0C\n
 SP06003015ZBWIPPAZX_65_132        SETUP     %%EndComments\n
 SP06004022ZBWIPPAZX_65_132        SETUP     /SAPdict 12 dict def\n
 SP06005012ZBWIPPAZX_65_132        SETUP     /SAPencode\n
 SP06006017ZBWIPPAZX_65_132        SETUP     { SAPdict begin\n
 SP06007026ZBWIPPAZX_65_132        SETUP       /basefontname exch def\n
 SP06008025ZBWIPPAZX_65_132        SETUP       /SAPfontname exch def\n
 SP06009043ZBWIPPAZX_65_132        SETUP       /basefontdict basefontname findfont def\n
 SP06010049ZBWIPPAZX_65_132        SETUP       /SAPfont      basefontdict maxlength dict def\n
 SP06011016ZBWIPPAZX_65_132        SETUP       basefontdict\n
 SP06012022ZBWIPPAZX_65_132        SETUP       { exch dup /FID ne\n
 SP06013024ZBWIPPAZX_65_132        SETUP         { dup /Encoding eq\n
 SP06014059ZBWIPPAZX_65_132        SETUP           { exch dup length array copy SAPfont 3 1 roll put }\n
 SP06015037ZBWIPPAZX_65_132        SETUP           { exch SAPfont 3 1 roll put }\n
 SP06016016ZBWIPPAZX_65_132        SETUP           ifelse }\n
 SP06017017ZBWIPPAZX_65_132        SETUP         { pop pop }\n
 SP06018014ZBWIPPAZX_65_132        SETUP         ifelse }\n
 SP06019010ZBWIPPAZX_65_132        SETUP       forall\n
 SP06020037ZBWIPPAZX_65_132        SETUP       SAPfont /FontName SAPfontname put\n
 SP06021022ZBWIPPAZX_65_132        SETUP       SAPcodes aload pop\n
 SP06022026ZBWIPPAZX_65_132        SETUP       SAPcodes length 2 idiv\n
 SP06023051ZBWIPPAZX_65_132        SETUP         { SAPfont /Encoding get 3 1 roll put } repeat\n
 SP06024040ZBWIPPAZX_65_132        SETUP         SAPfontname SAPfont definefont pop\n
 SP06025011ZBWIPPAZX_65_132        SETUP     end } def\n
 SP06026016ZBWIPPAZX_65_132        SETUP     /SAPcodes mark\n
 SP06027014ZBWIPPAZX_65_132        SETUP     16#20 /space\n
 SP06028015ZBWIPPAZX_65_132        SETUP     16#21 /exclam\n
 SP06029017ZBWIPPAZX_65_132        SETUP     16#22 /quotedbl\n
 SP06030019ZBWIPPAZX_65_132        SETUP     16#23 /numbersign\n
 SP06031015ZBWIPPAZX_65_132        SETUP     16#24 /dollar\n
 SP06032016ZBWIPPAZX_65_132        SETUP     16#25 /percent\n
 SP06033018ZBWIPPAZX_65_132        SETUP     16#26 /ampersand\n
 SP06034019ZBWIPPAZX_65_132        SETUP     16#27 /quoteright\n
 SP06035018ZBWIPPAZX_65_132        SETUP     16#28 /parenleft\n
 SP06036019ZBWIPPAZX_65_132        SETUP     16#29 /parenright\n
 SP06037017ZBWIPPAZX_65_132        SETUP     16#2A /asterisk\n
 SP06038013ZBWIPPAZX_65_132        SETUP     16#2B /plus\n
 SP06039014ZBWIPPAZX_65_132        SETUP     16#2C /comma\n
 SP06040015ZBWIPPAZX_65_132        SETUP     16#2D /hyphen\n
 SP06041015ZBWIPPAZX_65_132        SETUP     16#2E /period\n
 SP06042014ZBWIPPAZX_65_132        SETUP     16#2F /slash\n
 SP06043013ZBWIPPAZX_65_132        SETUP     16#30 /zero\n
 SP06044012ZBWIPPAZX_65_132        SETUP     16#31 /one\n
 SP06045012ZBWIPPAZX_65_132        SETUP     16#32 /two\n
 SP06046014ZBWIPPAZX_65_132        SETUP     16#33 /three\n
 SP06047013ZBWIPPAZX_65_132        SETUP     16#34 /four\n
 SP06048013ZBWIPPAZX_65_132        SETUP     16#35 /five\n
 SP06049012ZBWIPPAZX_65_132        SETUP     16#36 /six\n
 SP06050014ZBWIPPAZX_65_132        SETUP     16#37 /seven\n
 SP06051014ZBWIPPAZX_65_132        SETUP     16#38 /eight\n
 SP06052013ZBWIPPAZX_65_132        SETUP     16#39 /nine\n
 SP06053014ZBWIPPAZX_65_132        SETUP     16#3A /colon\n
 SP06054018ZBWIPPAZX_65_132        SETUP     16#3B /semicolon\n
 SP06055013ZBWIPPAZX_65_132        SETUP     16#3C /less\n
 SP06056014ZBWIPPAZX_65_132        SETUP     16#3D /equal\n
 SP06057016ZBWIPPAZX_65_132        SETUP     16#3E /greater\n
 SP06058017ZBWIPPAZX_65_132        SETUP     16#3F /question\n
 SP06059011ZBWIPPAZX_65_132        SETUP     16#40 /at\n
 SP06060070ZBWIPPAZX_65_132        SETUP     16#41 /A  16#42 /B  16#43 /C  16#44 /D  16#45 /E  16#46 /F  16#47 /G\n
 SP06061070ZBWIPPAZX_65_132        SETUP     16#48 /H  16#49 /I  16#4A /J  16#4B /K  16#4C /L  16#4D /M  16#4E /N\n
 SP06062070ZBWIPPAZX_65_132        SETUP     16#4F /O  16#50 /P  16#51 /Q  16#52 /R  16#53 /S  16#54 /T  16#55 /U\n
 SP06063050ZBWIPPAZX_65_132        SETUP     16#56 /V  16#57 /W  16#58 /X  16#59 /Y  16#5A /Z\n
 SP06064020ZBWIPPAZX_65_132        SETUP     16#5B /bracketleft\n
 SP06065018ZBWIPPAZX_65_132        SETUP     16#5C /backslash\n
 SP06066021ZBWIPPAZX_65_132        SETUP     16#5D /bracketright\n
 SP06067020ZBWIPPAZX_65_132        SETUP     16#5E /asciicircum\n
 SP06068019ZBWIPPAZX_65_132        SETUP     16#5F /underscore\n
 SP06069018ZBWIPPAZX_65_132        SETUP     16#60 /quoteleft\n
 SP06070070ZBWIPPAZX_65_132        SETUP     16#61 /a  16#62 /b  16#63 /c  16#64 /d  16#65 /e  16#66 /f  16#67 /g\n
 SP06071070ZBWIPPAZX_65_132        SETUP     16#68 /h  16#69 /i  16#6A /j  16#6B /k  16#6C /l  16#6D /m  16#6E /n\n
 SP06072070ZBWIPPAZX_65_132        SETUP     16#6F /o  16#70 /p  16#71 /q  16#72 /r  16#73 /s  16#74 /t  16#75 /u\n
 SP06073050ZBWIPPAZX_65_132        SETUP     16#76 /v  16#77 /w  16#78 /x  16#79 /y  16#7A /z\n
 SP06074018ZBWIPPAZX_65_132        SETUP     16#7B /braceleft\n
 SP06075012ZBWIPPAZX_65_132        SETUP     16#7C /bar\n
 SP06076019ZBWIPPAZX_65_132        SETUP     16#7D /braceright\n
 SP06077019ZBWIPPAZX_65_132        SETUP     16#7E /asciitilde\n
 SP06078066ZBWIPPAZX_65_132        SETUP     16#80 /grave  16#81 /acute    16#82 /circumflex     16#83 /tilde\n
 SP06079069ZBWIPPAZX_65_132        SETUP     16#84 /ogonek 16#85 /breve    16#86 /dotaccent      16#87 /dieresis\n
 SP06080066ZBWIPPAZX_65_132        SETUP     16#88 /ring   16#89 /cedilla  16#8A /hungarumlaut   16#8B /caron\n
 SP06081019ZBWIPPAZX_65_132        SETUP     16#A1 /exclamdown\n
 SP06082013ZBWIPPAZX_65_132        SETUP     16#A2 /cent\n
 SP06083017ZBWIPPAZX_65_132        SETUP     16#A3 /sterling\n
 SP06084017ZBWIPPAZX_65_132        SETUP     16#A4 /currency\n
 SP06085012ZBWIPPAZX_65_132        SETUP     16#A5 /yen\n
 SP06086018ZBWIPPAZX_65_132        SETUP     16#A6 /brokenbar\n
 SP06087016ZBWIPPAZX_65_132        SETUP     16#A7 /section\n
 SP06088017ZBWIPPAZX_65_132        SETUP     16#A8 /dieresis\n
 SP06089018ZBWIPPAZX_65_132        SETUP     16#A9 /copyright\n
 SP06090020ZBWIPPAZX_65_132        SETUP     16#AA /ordfeminine\n
 SP06091022ZBWIPPAZX_65_132        SETUP     16#AB /guillemotleft\n
 SP06092019ZBWIPPAZX_65_132        SETUP     16#AC /logicalnot\n
 SP06093014ZBWIPPAZX_65_132        SETUP     16#AD /minus\n
 SP06094019ZBWIPPAZX_65_132        SETUP     16#AE /registered\n
 SP06095015ZBWIPPAZX_65_132        SETUP     16#AF /macron\n
 SP06096015ZBWIPPAZX_65_132        SETUP     16#B0 /degree\n
 SP06097018ZBWIPPAZX_65_132        SETUP     16#B1 /plusminus\n
 SP06098020ZBWIPPAZX_65_132        SETUP     16#B2 /twosuperior\n
 SP06099022ZBWIPPAZX_65_132        SETUP     16#B3 /threesuperior\n
 SP06100020ZBWIPPAZX_65_132        SETUP     16#B4 /quotesingle\n
 SP06101011ZBWIPPAZX_65_132        SETUP     16#B5 /mu\n
 SP06102018ZBWIPPAZX_65_132        SETUP     16#B6 /paragraph\n
 SP06103023ZBWIPPAZX_65_132        SETUP     16#B7 /periodcentered\n
 SP06104016ZBWIPPAZX_65_132        SETUP     16#B8 /cedilla\n
 SP06105020ZBWIPPAZX_65_132        SETUP     16#B9 /onesuperior\n
 SP06106021ZBWIPPAZX_65_132        SETUP     16#BA /ordmasculine\n
 SP06107023ZBWIPPAZX_65_132        SETUP     16#BB /guillemotright\n
 SP06108019ZBWIPPAZX_65_132        SETUP     16#BC /onequarter\n
 SP06109016ZBWIPPAZX_65_132        SETUP     16#BD /onehalf\n
 SP06110022ZBWIPPAZX_65_132        SETUP     16#BE /threequarters\n
 SP06111021ZBWIPPAZX_65_132        SETUP     16#BF /questiondown\n
 SP06112015ZBWIPPAZX_65_132        SETUP     16#C0 /Agrave\n
 SP06113015ZBWIPPAZX_65_132        SETUP     16#C1 /Aacute\n
 SP06114020ZBWIPPAZX_65_132        SETUP     16#C2 /Acircumflex\n
 SP06115015ZBWIPPAZX_65_132        SETUP     16#C3 /Atilde\n
 SP06116018ZBWIPPAZX_65_132        SETUP     16#C4 /Adieresis\n
 SP06117014ZBWIPPAZX_65_132        SETUP     16#C5 /Aring\n
 SP06118011ZBWIPPAZX_65_132        SETUP     16#C6 /AE\n
 SP06119017ZBWIPPAZX_65_132        SETUP     16#C7 /Ccedilla\n
 SP06120015ZBWIPPAZX_65_132        SETUP     16#C8 /Egrave\n
 SP06121015ZBWIPPAZX_65_132        SETUP     16#C9 /Eacute\n
 SP06122020ZBWIPPAZX_65_132        SETUP     16#CA /Ecircumflex\n
 SP06123018ZBWIPPAZX_65_132        SETUP     16#CB /Edieresis\n
 SP06124015ZBWIPPAZX_65_132        SETUP     16#CC /Igrave\n
 SP06125015ZBWIPPAZX_65_132        SETUP     16#CD /Iacute\n
 SP06126020ZBWIPPAZX_65_132        SETUP     16#CE /Icircumflex\n
 SP06127018ZBWIPPAZX_65_132        SETUP     16#CF /Idieresis\n
 SP06128012ZBWIPPAZX_65_132        SETUP     16#D0 /Eth\n
 SP06129015ZBWIPPAZX_65_132        SETUP     16#D1 /Ntilde\n
 SP06130015ZBWIPPAZX_65_132        SETUP     16#D2 /Ograve\n
 SP06131015ZBWIPPAZX_65_132        SETUP     16#D3 /Oacute\n
 SP06132020ZBWIPPAZX_65_132        SETUP     16#D4 /Ocircumflex\n
 SP06133015ZBWIPPAZX_65_132        SETUP     16#D5 /Otilde\n
 SP06134018ZBWIPPAZX_65_132        SETUP     16#D6 /Odieresis\n
 SP06135017ZBWIPPAZX_65_132        SETUP     16#D7 /multiply\n
 SP06136015ZBWIPPAZX_65_132        SETUP     16#D8 /Oslash\n
 SP06137015ZBWIPPAZX_65_132        SETUP     16#D9 /Ugrave\n
 SP06138015ZBWIPPAZX_65_132        SETUP     16#DA /Uacute\n
 SP06139020ZBWIPPAZX_65_132        SETUP     16#DB /Ucircumflex\n
 SP06140018ZBWIPPAZX_65_132        SETUP     16#DC /Udieresis\n
 SP06141015ZBWIPPAZX_65_132        SETUP     16#DD /Yacute\n
 SP06142014ZBWIPPAZX_65_132        SETUP     16#DE /Thorn\n
 SP06143019ZBWIPPAZX_65_132        SETUP     16#DF /germandbls\n
 SP06144015ZBWIPPAZX_65_132        SETUP     16#E0 /agrave\n
 SP06145015ZBWIPPAZX_65_132        SETUP     16#E1 /aacute\n
 SP06146020ZBWIPPAZX_65_132        SETUP     16#E2 /acircumflex\n
 SP06147015ZBWIPPAZX_65_132        SETUP     16#E3 /atilde\n
 SP06148018ZBWIPPAZX_65_132        SETUP     16#E4 /adieresis\n
 SP06149014ZBWIPPAZX_65_132        SETUP     16#E5 /aring\n
 SP06150011ZBWIPPAZX_65_132        SETUP     16#E6 /ae\n
 SP06151017ZBWIPPAZX_65_132        SETUP     16#E7 /ccedilla\n
 SP06152015ZBWIPPAZX_65_132        SETUP     16#E8 /egrave\n
 SP06153015ZBWIPPAZX_65_132        SETUP     16#E9 /eacute\n
 SP06154020ZBWIPPAZX_65_132        SETUP     16#EA /ecircumflex\n
 SP06155018ZBWIPPAZX_65_132        SETUP     16#EB /edieresis\n
 SP06156015ZBWIPPAZX_65_132        SETUP     16#EC /igrave\n
 SP06157015ZBWIPPAZX_65_132        SETUP     16#ED /iacute\n
 SP06158020ZBWIPPAZX_65_132        SETUP     16#EE /icircumflex\n
 SP06159018ZBWIPPAZX_65_132        SETUP     16#EF /idieresis\n
 SP06160012ZBWIPPAZX_65_132        SETUP     16#F0 /eth\n
 SP06161015ZBWIPPAZX_65_132        SETUP     16#F1 /ntilde\n
 SP06162015ZBWIPPAZX_65_132        SETUP     16#F2 /ograve\n
 SP06163015ZBWIPPAZX_65_132        SETUP     16#F3 /oacute\n
 SP06164020ZBWIPPAZX_65_132        SETUP     16#F4 /ocircumflex\n
 SP06165015ZBWIPPAZX_65_132        SETUP     16#F5 /otilde\n
 SP06166018ZBWIPPAZX_65_132        SETUP     16#F6 /odieresis\n
 SP06167015ZBWIPPAZX_65_132        SETUP     16#F7 /divide\n
 SP06168015ZBWIPPAZX_65_132        SETUP     16#F8 /oslash\n
 SP06169015ZBWIPPAZX_65_132        SETUP     16#F9 /ugrave\n
 SP06170015ZBWIPPAZX_65_132        SETUP     16#FA /uacute\n
 SP06171020ZBWIPPAZX_65_132        SETUP     16#FB /ucircumflex\n
 SP06172018ZBWIPPAZX_65_132        SETUP     16#FC /udieresis\n
 SP06173015ZBWIPPAZX_65_132        SETUP     16#FD /yacute\n
 SP06174014ZBWIPPAZX_65_132        SETUP     16#FE /thorn\n
 SP06175018ZBWIPPAZX_65_132        SETUP     16#FF /ydieresis\n
 SP06176039ZBWIPPAZX_65_132        SETUP     counttomark array astore exch pop def\n
 SP06177055ZBWIPPAZX_65_132        SETUP     % utility functions used by list printer driver POST:\n
 SP06178021ZBWIPPAZX_65_132        SETUP     /PrintModeSimplex {\n
 SP06179021ZBWIPPAZX_65_132        SETUP       <</Duplex false>>\n
 SP06180017ZBWIPPAZX_65_132        SETUP       setpagedevice\n
 SP06181007ZBWIPPAZX_65_132        SETUP     } def\n
 SP06182020ZBWIPPAZX_65_132        SETUP     /PrintModeDuplex {\n
 SP06183034ZBWIPPAZX_65_132        SETUP       <</Duplex true /Tumble false>>\n
 SP06184017ZBWIPPAZX_65_132        SETUP       setpagedevice\n
 SP06185007ZBWIPPAZX_65_132        SETUP     } def\n
 SP06186026ZBWIPPAZX_65_132        SETUP     /PrintModeTumbleDuplex {\n
 SP06187033ZBWIPPAZX_65_132        SETUP       <</Duplex true /Tumble true>>\n
 SP06188017ZBWIPPAZX_65_132        SETUP       setpagedevice\n
 SP06189007ZBWIPPAZX_65_132        SETUP     } def\n
 SP06190013ZBWIPPAZX_65_132        SETUP     /InputTray1 {
 SP06191053ZBWIPPAZX_65_132        SETUP       <</DeferredMediaSelection true /MediaPosition 0>>\n
 SP06192017ZBWIPPAZX_65_132        SETUP       setpagedevice\n
 SP06193007ZBWIPPAZX_65_132        SETUP     } def\n
 SP06194013ZBWIPPAZX_65_132        SETUP     /InputTray2 {
 SP06195053ZBWIPPAZX_65_132        SETUP       <</DeferredMediaSelection true /MediaPosition 1>>\n
 SP06196017ZBWIPPAZX_65_132        SETUP       setpagedevice\n
 SP06197007ZBWIPPAZX_65_132        SETUP     } def\n
 SP06198013ZBWIPPAZX_65_132        SETUP     /InputTray3 {
 SP06199053ZBWIPPAZX_65_132        SETUP       <</DeferredMediaSelection true /MediaPosition 2>>\n
 SP06200017ZBWIPPAZX_65_132        SETUP       setpagedevice\n
 SP06201007ZBWIPPAZX_65_132        SETUP     } def\n
 SP06202015ZBWIPPAZX_65_132        SETUP     /InputTrayMan {
 SP06203053ZBWIPPAZX_65_132        SETUP       <</DeferredMediaSelection true /ManualFeed true>>\n
 SP06204017ZBWIPPAZX_65_132        SETUP       setpagedevice\n
 SP06205007ZBWIPPAZX_65_132        SETUP     } def\n
 SP06206013ZBWIPPAZX_65_132        SETUP     %%EndProlog\n
 SP06207027ZBWIPPAZX_65_132        SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06208027ZBWIPPAZX_65_132        SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06209026ZBWIPPAZX_65_132        SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06210026ZBWIPPAZX_65_132        SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06211000ZBWIPPAZX_65_132        SETUP
 SP1DX_65_200        ANY     LL0020000065SAP         1998102911155246A BIN     SAP         1998040710425340C BIN     SAP         1997081213463340A BIN
 SP1XX_65_200        M000000000000000000000000
 SP06001006ZBWIPPAZX_65_200        CONTROL     2 \n
 SP06002072ZBWIPPAZX_65_200        CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZX_65_200        CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZX_65_200        CONTROL                                                                         \n
 SP06001002ZBWIPPAZX_65_200        ENDLINE   \n
 SP06001011ZBWIPPAZX_65_200        ENDPAGE   # no action
 SP06001022ZBWIPPAZX_65_200        LEAVE     # CTRL-D to finish job
 SP06002005ZBWIPPAZX_65_200        LEAVE     \0x04
 SP06001007ZBWIPPAZX_65_200        SETUP     %!PS-\n
 SP06002029ZBWIPPAZX_65_200        SETUP     %%Creator: SAP R/3 rel.4.6A\n
 SP06003015ZBWIPPAZX_65_200        SETUP     %%EndComments\n
 SP06004022ZBWIPPAZX_65_200        SETUP     /SAPdict 12 dict def\n
 SP06005012ZBWIPPAZX_65_200        SETUP     /SAPencode\n
 SP06006017ZBWIPPAZX_65_200        SETUP     { SAPdict begin\n
 SP06007026ZBWIPPAZX_65_200        SETUP       /basefontname exch def\n
 SP06008025ZBWIPPAZX_65_200        SETUP       /SAPfontname exch def\n
 SP06009043ZBWIPPAZX_65_200        SETUP       /basefontdict basefontname findfont def\n
 SP06010049ZBWIPPAZX_65_200        SETUP       /SAPfont      basefontdict maxlength dict def\n
 SP06011016ZBWIPPAZX_65_200        SETUP       basefontdict\n
 SP06012022ZBWIPPAZX_65_200        SETUP       { exch dup /FID ne\n
 SP06013024ZBWIPPAZX_65_200        SETUP         { dup /Encoding eq\n
 SP06014059ZBWIPPAZX_65_200        SETUP           { exch dup length array copy SAPfont 3 1 roll put }\n
 SP06015037ZBWIPPAZX_65_200        SETUP           { exch SAPfont 3 1 roll put }\n
 SP06016016ZBWIPPAZX_65_200        SETUP           ifelse }\n
 SP06017017ZBWIPPAZX_65_200        SETUP         { pop pop }\n
 SP06018014ZBWIPPAZX_65_200        SETUP         ifelse }\n
 SP06019010ZBWIPPAZX_65_200        SETUP       forall\n
 SP06020037ZBWIPPAZX_65_200        SETUP       SAPfont /FontName SAPfontname put\n
 SP06021022ZBWIPPAZX_65_200        SETUP       SAPcodes aload pop\n
 SP06022026ZBWIPPAZX_65_200        SETUP       SAPcodes length 2 idiv\n
 SP06023051ZBWIPPAZX_65_200        SETUP         { SAPfont /Encoding get 3 1 roll put } repeat\n
 SP06024040ZBWIPPAZX_65_200        SETUP         SAPfontname SAPfont definefont pop\n
 SP06025011ZBWIPPAZX_65_200        SETUP     end } def\n
 SP06026016ZBWIPPAZX_65_200        SETUP     /SAPcodes mark\n
 SP06027014ZBWIPPAZX_65_200        SETUP     16#20 /space\n
 SP06028015ZBWIPPAZX_65_200        SETUP     16#21 /exclam\n
 SP06029017ZBWIPPAZX_65_200        SETUP     16#22 /quotedbl\n
 SP06030019ZBWIPPAZX_65_200        SETUP     16#23 /numbersign\n
 SP06031015ZBWIPPAZX_65_200        SETUP     16#24 /dollar\n
 SP06032016ZBWIPPAZX_65_200        SETUP     16#25 /percent\n
 SP06033018ZBWIPPAZX_65_200        SETUP     16#26 /ampersand\n
 SP06034019ZBWIPPAZX_65_200        SETUP     16#27 /quoteright\n
 SP06035018ZBWIPPAZX_65_200        SETUP     16#28 /parenleft\n
 SP06036019ZBWIPPAZX_65_200        SETUP     16#29 /parenright\n
 SP06037017ZBWIPPAZX_65_200        SETUP     16#2A /asterisk\n
 SP06038013ZBWIPPAZX_65_200        SETUP     16#2B /plus\n
 SP06039014ZBWIPPAZX_65_200        SETUP     16#2C /comma\n
 SP06040015ZBWIPPAZX_65_200        SETUP     16#2D /hyphen\n
 SP06041015ZBWIPPAZX_65_200        SETUP     16#2E /period\n
 SP06042014ZBWIPPAZX_65_200        SETUP     16#2F /slash\n
 SP06043013ZBWIPPAZX_65_200        SETUP     16#30 /zero\n
 SP06044012ZBWIPPAZX_65_200        SETUP     16#31 /one\n
 SP06045012ZBWIPPAZX_65_200        SETUP     16#32 /two\n
 SP06046014ZBWIPPAZX_65_200        SETUP     16#33 /three\n
 SP06047013ZBWIPPAZX_65_200        SETUP     16#34 /four\n
 SP06048013ZBWIPPAZX_65_200        SETUP     16#35 /five\n
 SP06049012ZBWIPPAZX_65_200        SETUP     16#36 /six\n
 SP06050014ZBWIPPAZX_65_200        SETUP     16#37 /seven\n
 SP06051014ZBWIPPAZX_65_200        SETUP     16#38 /eight\n
 SP06052013ZBWIPPAZX_65_200        SETUP     16#39 /nine\n
 SP06053014ZBWIPPAZX_65_200        SETUP     16#3A /colon\n
 SP06054018ZBWIPPAZX_65_200        SETUP     16#3B /semicolon\n
 SP06055013ZBWIPPAZX_65_200        SETUP     16#3C /less\n
 SP06056014ZBWIPPAZX_65_200        SETUP     16#3D /equal\n
 SP06057016ZBWIPPAZX_65_200        SETUP     16#3E /greater\n
 SP06058017ZBWIPPAZX_65_200        SETUP     16#3F /question\n
 SP06059011ZBWIPPAZX_65_200        SETUP     16#40 /at\n
 SP06060070ZBWIPPAZX_65_200        SETUP     16#41 /A  16#42 /B  16#43 /C  16#44 /D  16#45 /E  16#46 /F  16#47 /G\n
 SP06061070ZBWIPPAZX_65_200        SETUP     16#48 /H  16#49 /I  16#4A /J  16#4B /K  16#4C /L  16#4D /M  16#4E /N\n
 SP06062070ZBWIPPAZX_65_200        SETUP     16#4F /O  16#50 /P  16#51 /Q  16#52 /R  16#53 /S  16#54 /T  16#55 /U\n
 SP06063050ZBWIPPAZX_65_200        SETUP     16#56 /V  16#57 /W  16#58 /X  16#59 /Y  16#5A /Z\n
 SP06064020ZBWIPPAZX_65_200        SETUP     16#5B /bracketleft\n
 SP06065018ZBWIPPAZX_65_200        SETUP     16#5C /backslash\n
 SP06066021ZBWIPPAZX_65_200        SETUP     16#5D /bracketright\n
 SP06067020ZBWIPPAZX_65_200        SETUP     16#5E /asciicircum\n
 SP06068019ZBWIPPAZX_65_200        SETUP     16#5F /underscore\n
 SP06069018ZBWIPPAZX_65_200        SETUP     16#60 /quoteleft\n
 SP06070070ZBWIPPAZX_65_200        SETUP     16#61 /a  16#62 /b  16#63 /c  16#64 /d  16#65 /e  16#66 /f  16#67 /g\n
 SP06071070ZBWIPPAZX_65_200        SETUP     16#68 /h  16#69 /i  16#6A /j  16#6B /k  16#6C /l  16#6D /m  16#6E /n\n
 SP06072070ZBWIPPAZX_65_200        SETUP     16#6F /o  16#70 /p  16#71 /q  16#72 /r  16#73 /s  16#74 /t  16#75 /u\n
 SP06073050ZBWIPPAZX_65_200        SETUP     16#76 /v  16#77 /w  16#78 /x  16#79 /y  16#7A /z\n
 SP06074018ZBWIPPAZX_65_200        SETUP     16#7B /braceleft\n
 SP06075012ZBWIPPAZX_65_200        SETUP     16#7C /bar\n
 SP06076019ZBWIPPAZX_65_200        SETUP     16#7D /braceright\n
 SP06077019ZBWIPPAZX_65_200        SETUP     16#7E /asciitilde\n
 SP06078066ZBWIPPAZX_65_200        SETUP     16#80 /grave  16#81 /acute    16#82 /circumflex     16#83 /tilde\n
 SP06079069ZBWIPPAZX_65_200        SETUP     16#84 /ogonek 16#85 /breve    16#86 /dotaccent      16#87 /dieresis\n
 SP06080066ZBWIPPAZX_65_200        SETUP     16#88 /ring   16#89 /cedilla  16#8A /hungarumlaut   16#8B /caron\n
 SP06081019ZBWIPPAZX_65_200        SETUP     16#A1 /exclamdown\n
 SP06082013ZBWIPPAZX_65_200        SETUP     16#A2 /cent\n
 SP06083017ZBWIPPAZX_65_200        SETUP     16#A3 /sterling\n
 SP06084017ZBWIPPAZX_65_200        SETUP     16#A4 /currency\n
 SP06085012ZBWIPPAZX_65_200        SETUP     16#A5 /yen\n
 SP06086018ZBWIPPAZX_65_200        SETUP     16#A6 /brokenbar\n
 SP06087016ZBWIPPAZX_65_200        SETUP     16#A7 /section\n
 SP06088017ZBWIPPAZX_65_200        SETUP     16#A8 /dieresis\n
 SP06089018ZBWIPPAZX_65_200        SETUP     16#A9 /copyright\n
 SP06090020ZBWIPPAZX_65_200        SETUP     16#AA /ordfeminine\n
 SP06091022ZBWIPPAZX_65_200        SETUP     16#AB /guillemotleft\n
 SP06092019ZBWIPPAZX_65_200        SETUP     16#AC /logicalnot\n
 SP06093014ZBWIPPAZX_65_200        SETUP     16#AD /minus\n
 SP06094019ZBWIPPAZX_65_200        SETUP     16#AE /registered\n
 SP06095015ZBWIPPAZX_65_200        SETUP     16#AF /macron\n
 SP06096015ZBWIPPAZX_65_200        SETUP     16#B0 /degree\n
 SP06097018ZBWIPPAZX_65_200        SETUP     16#B1 /plusminus\n
 SP06098020ZBWIPPAZX_65_200        SETUP     16#B2 /twosuperior\n
 SP06099022ZBWIPPAZX_65_200        SETUP     16#B3 /threesuperior\n
 SP06100020ZBWIPPAZX_65_200        SETUP     16#B4 /quotesingle\n
 SP06101011ZBWIPPAZX_65_200        SETUP     16#B5 /mu\n
 SP06102018ZBWIPPAZX_65_200        SETUP     16#B6 /paragraph\n
 SP06103023ZBWIPPAZX_65_200        SETUP     16#B7 /periodcentered\n
 SP06104016ZBWIPPAZX_65_200        SETUP     16#B8 /cedilla\n
 SP06105020ZBWIPPAZX_65_200        SETUP     16#B9 /onesuperior\n
 SP06106021ZBWIPPAZX_65_200        SETUP     16#BA /ordmasculine\n
 SP06107023ZBWIPPAZX_65_200        SETUP     16#BB /guillemotright\n
 SP06108019ZBWIPPAZX_65_200        SETUP     16#BC /onequarter\n
 SP06109016ZBWIPPAZX_65_200        SETUP     16#BD /onehalf\n
 SP06110022ZBWIPPAZX_65_200        SETUP     16#BE /threequarters\n
 SP06111021ZBWIPPAZX_65_200        SETUP     16#BF /questiondown\n
 SP06112015ZBWIPPAZX_65_200        SETUP     16#C0 /Agrave\n
 SP06113015ZBWIPPAZX_65_200        SETUP     16#C1 /Aacute\n
 SP06114020ZBWIPPAZX_65_200        SETUP     16#C2 /Acircumflex\n
 SP06115015ZBWIPPAZX_65_200        SETUP     16#C3 /Atilde\n
 SP06116018ZBWIPPAZX_65_200        SETUP     16#C4 /Adieresis\n
 SP06117014ZBWIPPAZX_65_200        SETUP     16#C5 /Aring\n
 SP06118011ZBWIPPAZX_65_200        SETUP     16#C6 /AE\n
 SP06119017ZBWIPPAZX_65_200        SETUP     16#C7 /Ccedilla\n
 SP06120015ZBWIPPAZX_65_200        SETUP     16#C8 /Egrave\n
 SP06121015ZBWIPPAZX_65_200        SETUP     16#C9 /Eacute\n
 SP06122020ZBWIPPAZX_65_200        SETUP     16#CA /Ecircumflex\n
 SP06123018ZBWIPPAZX_65_200        SETUP     16#CB /Edieresis\n
 SP06124015ZBWIPPAZX_65_200        SETUP     16#CC /Igrave\n
 SP06125015ZBWIPPAZX_65_200        SETUP     16#CD /Iacute\n
 SP06126020ZBWIPPAZX_65_200        SETUP     16#CE /Icircumflex\n
 SP06127018ZBWIPPAZX_65_200        SETUP     16#CF /Idieresis\n
 SP06128012ZBWIPPAZX_65_200        SETUP     16#D0 /Eth\n
 SP06129015ZBWIPPAZX_65_200        SETUP     16#D1 /Ntilde\n
 SP06130015ZBWIPPAZX_65_200        SETUP     16#D2 /Ograve\n
 SP06131015ZBWIPPAZX_65_200        SETUP     16#D3 /Oacute\n
 SP06132020ZBWIPPAZX_65_200        SETUP     16#D4 /Ocircumflex\n
 SP06133015ZBWIPPAZX_65_200        SETUP     16#D5 /Otilde\n
 SP06134018ZBWIPPAZX_65_200        SETUP     16#D6 /Odieresis\n
 SP06135017ZBWIPPAZX_65_200        SETUP     16#D7 /multiply\n
 SP06136015ZBWIPPAZX_65_200        SETUP     16#D8 /Oslash\n
 SP06137015ZBWIPPAZX_65_200        SETUP     16#D9 /Ugrave\n
 SP06138015ZBWIPPAZX_65_200        SETUP     16#DA /Uacute\n
 SP06139020ZBWIPPAZX_65_200        SETUP     16#DB /Ucircumflex\n
 SP06140018ZBWIPPAZX_65_200        SETUP     16#DC /Udieresis\n
 SP06141015ZBWIPPAZX_65_200        SETUP     16#DD /Yacute\n
 SP06142014ZBWIPPAZX_65_200        SETUP     16#DE /Thorn\n
 SP06143019ZBWIPPAZX_65_200        SETUP     16#DF /germandbls\n
 SP06144015ZBWIPPAZX_65_200        SETUP     16#E0 /agrave\n
 SP06145015ZBWIPPAZX_65_200        SETUP     16#E1 /aacute\n
 SP06146020ZBWIPPAZX_65_200        SETUP     16#E2 /acircumflex\n
 SP06147015ZBWIPPAZX_65_200        SETUP     16#E3 /atilde\n
 SP06148018ZBWIPPAZX_65_200        SETUP     16#E4 /adieresis\n
 SP06149014ZBWIPPAZX_65_200        SETUP     16#E5 /aring\n
 SP06150011ZBWIPPAZX_65_200        SETUP     16#E6 /ae\n
 SP06151017ZBWIPPAZX_65_200        SETUP     16#E7 /ccedilla\n
 SP06152015ZBWIPPAZX_65_200        SETUP     16#E8 /egrave\n
 SP06153015ZBWIPPAZX_65_200        SETUP     16#E9 /eacute\n
 SP06154020ZBWIPPAZX_65_200        SETUP     16#EA /ecircumflex\n
 SP06155018ZBWIPPAZX_65_200        SETUP     16#EB /edieresis\n
 SP06156015ZBWIPPAZX_65_200        SETUP     16#EC /igrave\n
 SP06157015ZBWIPPAZX_65_200        SETUP     16#ED /iacute\n
 SP06158020ZBWIPPAZX_65_200        SETUP     16#EE /icircumflex\n
 SP06159018ZBWIPPAZX_65_200        SETUP     16#EF /idieresis\n
 SP06160012ZBWIPPAZX_65_200        SETUP     16#F0 /eth\n
 SP06161015ZBWIPPAZX_65_200        SETUP     16#F1 /ntilde\n
 SP06162015ZBWIPPAZX_65_200        SETUP     16#F2 /ograve\n
 SP06163015ZBWIPPAZX_65_200        SETUP     16#F3 /oacute\n
 SP06164020ZBWIPPAZX_65_200        SETUP     16#F4 /ocircumflex\n
 SP06165015ZBWIPPAZX_65_200        SETUP     16#F5 /otilde\n
 SP06166018ZBWIPPAZX_65_200        SETUP     16#F6 /odieresis\n
 SP06167015ZBWIPPAZX_65_200        SETUP     16#F7 /divide\n
 SP06168015ZBWIPPAZX_65_200        SETUP     16#F8 /oslash\n
 SP06169015ZBWIPPAZX_65_200        SETUP     16#F9 /ugrave\n
 SP06170015ZBWIPPAZX_65_200        SETUP     16#FA /uacute\n
 SP06171020ZBWIPPAZX_65_200        SETUP     16#FB /ucircumflex\n
 SP06172018ZBWIPPAZX_65_200        SETUP     16#FC /udieresis\n
 SP06173015ZBWIPPAZX_65_200        SETUP     16#FD /yacute\n
 SP06174014ZBWIPPAZX_65_200        SETUP     16#FE /thorn\n
 SP06175018ZBWIPPAZX_65_200        SETUP     16#FF /ydieresis\n
 SP06176039ZBWIPPAZX_65_200        SETUP     counttomark array astore exch pop def\n
 SP06177055ZBWIPPAZX_65_200        SETUP     % utility functions used by list printer driver POST:\n
 SP06178021ZBWIPPAZX_65_200        SETUP     /PrintModeSimplex {\n
 SP06179021ZBWIPPAZX_65_200        SETUP       <</Duplex false>>\n
 SP06180017ZBWIPPAZX_65_200        SETUP       setpagedevice\n
 SP06181007ZBWIPPAZX_65_200        SETUP     } def\n
 SP06182020ZBWIPPAZX_65_200        SETUP     /PrintModeDuplex {\n
 SP06183034ZBWIPPAZX_65_200        SETUP       <</Duplex true /Tumble false>>\n
 SP06184017ZBWIPPAZX_65_200        SETUP       setpagedevice\n
 SP06185007ZBWIPPAZX_65_200        SETUP     } def\n
 SP06186026ZBWIPPAZX_65_200        SETUP     /PrintModeTumbleDuplex {\n
 SP06187033ZBWIPPAZX_65_200        SETUP       <</Duplex true /Tumble true>>\n
 SP06188017ZBWIPPAZX_65_200        SETUP       setpagedevice\n
 SP06189007ZBWIPPAZX_65_200        SETUP     } def\n
 SP06190013ZBWIPPAZX_65_200        SETUP     /InputTray1 {
 SP06191053ZBWIPPAZX_65_200        SETUP       <</DeferredMediaSelection true /MediaPosition 0>>\n
 SP06192017ZBWIPPAZX_65_200        SETUP       setpagedevice\n
 SP06193007ZBWIPPAZX_65_200        SETUP     } def\n
 SP06194013ZBWIPPAZX_65_200        SETUP     /InputTray2 {
 SP06195053ZBWIPPAZX_65_200        SETUP       <</DeferredMediaSelection true /MediaPosition 1>>\n
 SP06196017ZBWIPPAZX_65_200        SETUP       setpagedevice\n
 SP06197007ZBWIPPAZX_65_200        SETUP     } def\n
 SP06198013ZBWIPPAZX_65_200        SETUP     /InputTray3 {
 SP06199053ZBWIPPAZX_65_200        SETUP       <</DeferredMediaSelection true /MediaPosition 2>>\n
 SP06200017ZBWIPPAZX_65_200        SETUP       setpagedevice\n
 SP06201007ZBWIPPAZX_65_200        SETUP     } def\n
 SP06202015ZBWIPPAZX_65_200        SETUP     /InputTrayMan {
 SP06203053ZBWIPPAZX_65_200        SETUP       <</DeferredMediaSelection true /ManualFeed true>>\n
 SP06204017ZBWIPPAZX_65_200        SETUP       setpagedevice\n
 SP06205007ZBWIPPAZX_65_200        SETUP     } def\n
 SP06206013ZBWIPPAZX_65_200        SETUP     %%EndProlog\n
 SP06207027ZBWIPPAZX_65_200        SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06208027ZBWIPPAZX_65_200        SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06209026ZBWIPPAZX_65_200        SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06210026ZBWIPPAZX_65_200        SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06211000ZBWIPPAZX_65_200        SETUP
 SP1DX_65_255        ANY     LL0025500065SAP         1998040711020840C BIN     SAP         1997081213593540A BIN     SAP         1997062517535740A BIN
 SP1XX_65_255        M000000000000000000000000
 SP06001006ZBWIPPAZX_65_255        CONTROL     2 \n
 SP06002072ZBWIPPAZX_65_255        CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZX_65_255        CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZX_65_255        CONTROL                                                                         \n
 SP06001002ZBWIPPAZX_65_255        ENDLINE   \n
 SP06001011ZBWIPPAZX_65_255        ENDPAGE   # no action
 SP06001022ZBWIPPAZX_65_255        LEAVE     # CTRL-D to finish job
 SP06002005ZBWIPPAZX_65_255        LEAVE     \0x04
 SP06001007ZBWIPPAZX_65_255        SETUP     %!PS-\n
 SP06002029ZBWIPPAZX_65_255        SETUP     %%Creator: SAP R/3 rel.4.0C\n
 SP06003015ZBWIPPAZX_65_255        SETUP     %%EndComments\n
 SP06004022ZBWIPPAZX_65_255        SETUP     /SAPdict 12 dict def\n
 SP06005012ZBWIPPAZX_65_255        SETUP     /SAPencode\n
 SP06006017ZBWIPPAZX_65_255        SETUP     { SAPdict begin\n
 SP06007026ZBWIPPAZX_65_255        SETUP       /basefontname exch def\n
 SP06008025ZBWIPPAZX_65_255        SETUP       /SAPfontname exch def\n
 SP06009043ZBWIPPAZX_65_255        SETUP       /basefontdict basefontname findfont def\n
 SP06010049ZBWIPPAZX_65_255        SETUP       /SAPfont      basefontdict maxlength dict def\n
 SP06011016ZBWIPPAZX_65_255        SETUP       basefontdict\n
 SP06012022ZBWIPPAZX_65_255        SETUP       { exch dup /FID ne\n
 SP06013024ZBWIPPAZX_65_255        SETUP         { dup /Encoding eq\n
 SP06014059ZBWIPPAZX_65_255        SETUP           { exch dup length array copy SAPfont 3 1 roll put }\n
 SP06015037ZBWIPPAZX_65_255        SETUP           { exch SAPfont 3 1 roll put }\n
 SP06016016ZBWIPPAZX_65_255        SETUP           ifelse }\n
 SP06017017ZBWIPPAZX_65_255        SETUP         { pop pop }\n
 SP06018014ZBWIPPAZX_65_255        SETUP         ifelse }\n
 SP06019010ZBWIPPAZX_65_255        SETUP       forall\n
 SP06020037ZBWIPPAZX_65_255        SETUP       SAPfont /FontName SAPfontname put\n
 SP06021022ZBWIPPAZX_65_255        SETUP       SAPcodes aload pop\n
 SP06022026ZBWIPPAZX_65_255        SETUP       SAPcodes length 2 idiv\n
 SP06023051ZBWIPPAZX_65_255        SETUP         { SAPfont /Encoding get 3 1 roll put } repeat\n
 SP06024040ZBWIPPAZX_65_255        SETUP         SAPfontname SAPfont definefont pop\n
 SP06025011ZBWIPPAZX_65_255        SETUP     end } def\n
 SP06026016ZBWIPPAZX_65_255        SETUP     /SAPcodes mark\n
 SP06027014ZBWIPPAZX_65_255        SETUP     16#20 /space\n
 SP06028015ZBWIPPAZX_65_255        SETUP     16#21 /exclam\n
 SP06029017ZBWIPPAZX_65_255        SETUP     16#22 /quotedbl\n
 SP06030019ZBWIPPAZX_65_255        SETUP     16#23 /numbersign\n
 SP06031015ZBWIPPAZX_65_255        SETUP     16#24 /dollar\n
 SP06032016ZBWIPPAZX_65_255        SETUP     16#25 /percent\n
 SP06033018ZBWIPPAZX_65_255        SETUP     16#26 /ampersand\n
 SP06034019ZBWIPPAZX_65_255        SETUP     16#27 /quoteright\n
 SP06035018ZBWIPPAZX_65_255        SETUP     16#28 /parenleft\n
 SP06036019ZBWIPPAZX_65_255        SETUP     16#29 /parenright\n
 SP06037017ZBWIPPAZX_65_255        SETUP     16#2A /asterisk\n
 SP06038013ZBWIPPAZX_65_255        SETUP     16#2B /plus\n
 SP06039014ZBWIPPAZX_65_255        SETUP     16#2C /comma\n
 SP06040015ZBWIPPAZX_65_255        SETUP     16#2D /hyphen\n
 SP06041015ZBWIPPAZX_65_255        SETUP     16#2E /period\n
 SP06042014ZBWIPPAZX_65_255        SETUP     16#2F /slash\n
 SP06043013ZBWIPPAZX_65_255        SETUP     16#30 /zero\n
 SP06044012ZBWIPPAZX_65_255        SETUP     16#31 /one\n
 SP06045012ZBWIPPAZX_65_255        SETUP     16#32 /two\n
 SP06046014ZBWIPPAZX_65_255        SETUP     16#33 /three\n
 SP06047013ZBWIPPAZX_65_255        SETUP     16#34 /four\n
 SP06048013ZBWIPPAZX_65_255        SETUP     16#35 /five\n
 SP06049012ZBWIPPAZX_65_255        SETUP     16#36 /six\n
 SP06050014ZBWIPPAZX_65_255        SETUP     16#37 /seven\n
 SP06051014ZBWIPPAZX_65_255        SETUP     16#38 /eight\n
 SP06052013ZBWIPPAZX_65_255        SETUP     16#39 /nine\n
 SP06053014ZBWIPPAZX_65_255        SETUP     16#3A /colon\n
 SP06054018ZBWIPPAZX_65_255        SETUP     16#3B /semicolon\n
 SP06055013ZBWIPPAZX_65_255        SETUP     16#3C /less\n
 SP06056014ZBWIPPAZX_65_255        SETUP     16#3D /equal\n
 SP06057016ZBWIPPAZX_65_255        SETUP     16#3E /greater\n
 SP06058017ZBWIPPAZX_65_255        SETUP     16#3F /question\n
 SP06059011ZBWIPPAZX_65_255        SETUP     16#40 /at\n
 SP06060070ZBWIPPAZX_65_255        SETUP     16#41 /A  16#42 /B  16#43 /C  16#44 /D  16#45 /E  16#46 /F  16#47 /G\n
 SP06061070ZBWIPPAZX_65_255        SETUP     16#48 /H  16#49 /I  16#4A /J  16#4B /K  16#4C /L  16#4D /M  16#4E /N\n
 SP06062070ZBWIPPAZX_65_255        SETUP     16#4F /O  16#50 /P  16#51 /Q  16#52 /R  16#53 /S  16#54 /T  16#55 /U\n
 SP06063050ZBWIPPAZX_65_255        SETUP     16#56 /V  16#57 /W  16#58 /X  16#59 /Y  16#5A /Z\n
 SP06064020ZBWIPPAZX_65_255        SETUP     16#5B /bracketleft\n
 SP06065018ZBWIPPAZX_65_255        SETUP     16#5C /backslash\n
 SP06066021ZBWIPPAZX_65_255        SETUP     16#5D /bracketright\n
 SP06067020ZBWIPPAZX_65_255        SETUP     16#5E /asciicircum\n
 SP06068019ZBWIPPAZX_65_255        SETUP     16#5F /underscore\n
 SP06069018ZBWIPPAZX_65_255        SETUP     16#60 /quoteleft\n
 SP06070070ZBWIPPAZX_65_255        SETUP     16#61 /a  16#62 /b  16#63 /c  16#64 /d  16#65 /e  16#66 /f  16#67 /g\n
 SP06071070ZBWIPPAZX_65_255        SETUP     16#68 /h  16#69 /i  16#6A /j  16#6B /k  16#6C /l  16#6D /m  16#6E /n\n
 SP06072070ZBWIPPAZX_65_255        SETUP     16#6F /o  16#70 /p  16#71 /q  16#72 /r  16#73 /s  16#74 /t  16#75 /u\n
 SP06073050ZBWIPPAZX_65_255        SETUP     16#76 /v  16#77 /w  16#78 /x  16#79 /y  16#7A /z\n
 SP06074018ZBWIPPAZX_65_255        SETUP     16#7B /braceleft\n
 SP06075012ZBWIPPAZX_65_255        SETUP     16#7C /bar\n
 SP06076019ZBWIPPAZX_65_255        SETUP     16#7D /braceright\n
 SP06077019ZBWIPPAZX_65_255        SETUP     16#7E /asciitilde\n
 SP06078066ZBWIPPAZX_65_255        SETUP     16#80 /grave  16#81 /acute    16#82 /circumflex     16#83 /tilde\n
 SP06079069ZBWIPPAZX_65_255        SETUP     16#84 /ogonek 16#85 /breve    16#86 /dotaccent      16#87 /dieresis\n
 SP06080066ZBWIPPAZX_65_255        SETUP     16#88 /ring   16#89 /cedilla  16#8A /hungarumlaut   16#8B /caron\n
 SP06081019ZBWIPPAZX_65_255        SETUP     16#A1 /exclamdown\n
 SP06082013ZBWIPPAZX_65_255        SETUP     16#A2 /cent\n
 SP06083017ZBWIPPAZX_65_255        SETUP     16#A3 /sterling\n
 SP06084017ZBWIPPAZX_65_255        SETUP     16#A4 /currency\n
 SP06085012ZBWIPPAZX_65_255        SETUP     16#A5 /yen\n
 SP06086018ZBWIPPAZX_65_255        SETUP     16#A6 /brokenbar\n
 SP06087016ZBWIPPAZX_65_255        SETUP     16#A7 /section\n
 SP06088017ZBWIPPAZX_65_255        SETUP     16#A8 /dieresis\n
 SP06089018ZBWIPPAZX_65_255        SETUP     16#A9 /copyright\n
 SP06090020ZBWIPPAZX_65_255        SETUP     16#AA /ordfeminine\n
 SP06091022ZBWIPPAZX_65_255        SETUP     16#AB /guillemotleft\n
 SP06092019ZBWIPPAZX_65_255        SETUP     16#AC /logicalnot\n
 SP06093014ZBWIPPAZX_65_255        SETUP     16#AD /minus\n
 SP06094019ZBWIPPAZX_65_255        SETUP     16#AE /registered\n
 SP06095015ZBWIPPAZX_65_255        SETUP     16#AF /macron\n
 SP06096015ZBWIPPAZX_65_255        SETUP     16#B0 /degree\n
 SP06097018ZBWIPPAZX_65_255        SETUP     16#B1 /plusminus\n
 SP06098020ZBWIPPAZX_65_255        SETUP     16#B2 /twosuperior\n
 SP06099022ZBWIPPAZX_65_255        SETUP     16#B3 /threesuperior\n
 SP06100020ZBWIPPAZX_65_255        SETUP     16#B4 /quotesingle\n
 SP06101011ZBWIPPAZX_65_255        SETUP     16#B5 /mu\n
 SP06102018ZBWIPPAZX_65_255        SETUP     16#B6 /paragraph\n
 SP06103023ZBWIPPAZX_65_255        SETUP     16#B7 /periodcentered\n
 SP06104016ZBWIPPAZX_65_255        SETUP     16#B8 /cedilla\n
 SP06105020ZBWIPPAZX_65_255        SETUP     16#B9 /onesuperior\n
 SP06106021ZBWIPPAZX_65_255        SETUP     16#BA /ordmasculine\n
 SP06107023ZBWIPPAZX_65_255        SETUP     16#BB /guillemotright\n
 SP06108019ZBWIPPAZX_65_255        SETUP     16#BC /onequarter\n
 SP06109016ZBWIPPAZX_65_255        SETUP     16#BD /onehalf\n
 SP06110022ZBWIPPAZX_65_255        SETUP     16#BE /threequarters\n
 SP06111021ZBWIPPAZX_65_255        SETUP     16#BF /questiondown\n
 SP06112015ZBWIPPAZX_65_255        SETUP     16#C0 /Agrave\n
 SP06113015ZBWIPPAZX_65_255        SETUP     16#C1 /Aacute\n
 SP06114020ZBWIPPAZX_65_255        SETUP     16#C2 /Acircumflex\n
 SP06115015ZBWIPPAZX_65_255        SETUP     16#C3 /Atilde\n
 SP06116018ZBWIPPAZX_65_255        SETUP     16#C4 /Adieresis\n
 SP06117014ZBWIPPAZX_65_255        SETUP     16#C5 /Aring\n
 SP06118011ZBWIPPAZX_65_255        SETUP     16#C6 /AE\n
 SP06119017ZBWIPPAZX_65_255        SETUP     16#C7 /Ccedilla\n
 SP06120015ZBWIPPAZX_65_255        SETUP     16#C8 /Egrave\n
 SP06121015ZBWIPPAZX_65_255        SETUP     16#C9 /Eacute\n
 SP06122020ZBWIPPAZX_65_255        SETUP     16#CA /Ecircumflex\n
 SP06123018ZBWIPPAZX_65_255        SETUP     16#CB /Edieresis\n
 SP06124015ZBWIPPAZX_65_255        SETUP     16#CC /Igrave\n
 SP06125015ZBWIPPAZX_65_255        SETUP     16#CD /Iacute\n
 SP06126020ZBWIPPAZX_65_255        SETUP     16#CE /Icircumflex\n
 SP06127018ZBWIPPAZX_65_255        SETUP     16#CF /Idieresis\n
 SP06128012ZBWIPPAZX_65_255        SETUP     16#D0 /Eth\n
 SP06129015ZBWIPPAZX_65_255        SETUP     16#D1 /Ntilde\n
 SP06130015ZBWIPPAZX_65_255        SETUP     16#D2 /Ograve\n
 SP06131015ZBWIPPAZX_65_255        SETUP     16#D3 /Oacute\n
 SP06132020ZBWIPPAZX_65_255        SETUP     16#D4 /Ocircumflex\n
 SP06133015ZBWIPPAZX_65_255        SETUP     16#D5 /Otilde\n
 SP06134018ZBWIPPAZX_65_255        SETUP     16#D6 /Odieresis\n
 SP06135017ZBWIPPAZX_65_255        SETUP     16#D7 /multiply\n
 SP06136015ZBWIPPAZX_65_255        SETUP     16#D8 /Oslash\n
 SP06137015ZBWIPPAZX_65_255        SETUP     16#D9 /Ugrave\n
 SP06138015ZBWIPPAZX_65_255        SETUP     16#DA /Uacute\n
 SP06139020ZBWIPPAZX_65_255        SETUP     16#DB /Ucircumflex\n
 SP06140018ZBWIPPAZX_65_255        SETUP     16#DC /Udieresis\n
 SP06141015ZBWIPPAZX_65_255        SETUP     16#DD /Yacute\n
 SP06142014ZBWIPPAZX_65_255        SETUP     16#DE /Thorn\n
 SP06143019ZBWIPPAZX_65_255        SETUP     16#DF /germandbls\n
 SP06144015ZBWIPPAZX_65_255        SETUP     16#E0 /agrave\n
 SP06145015ZBWIPPAZX_65_255        SETUP     16#E1 /aacute\n
 SP06146020ZBWIPPAZX_65_255        SETUP     16#E2 /acircumflex\n
 SP06147015ZBWIPPAZX_65_255        SETUP     16#E3 /atilde\n
 SP06148018ZBWIPPAZX_65_255        SETUP     16#E4 /adieresis\n
 SP06149014ZBWIPPAZX_65_255        SETUP     16#E5 /aring\n
 SP06150011ZBWIPPAZX_65_255        SETUP     16#E6 /ae\n
 SP06151017ZBWIPPAZX_65_255        SETUP     16#E7 /ccedilla\n
 SP06152015ZBWIPPAZX_65_255        SETUP     16#E8 /egrave\n
 SP06153015ZBWIPPAZX_65_255        SETUP     16#E9 /eacute\n
 SP06154020ZBWIPPAZX_65_255        SETUP     16#EA /ecircumflex\n
 SP06155018ZBWIPPAZX_65_255        SETUP     16#EB /edieresis\n
 SP06156015ZBWIPPAZX_65_255        SETUP     16#EC /igrave\n
 SP06157015ZBWIPPAZX_65_255        SETUP     16#ED /iacute\n
 SP06158020ZBWIPPAZX_65_255        SETUP     16#EE /icircumflex\n
 SP06159018ZBWIPPAZX_65_255        SETUP     16#EF /idieresis\n
 SP06160012ZBWIPPAZX_65_255        SETUP     16#F0 /eth\n
 SP06161015ZBWIPPAZX_65_255        SETUP     16#F1 /ntilde\n
 SP06162015ZBWIPPAZX_65_255        SETUP     16#F2 /ograve\n
 SP06163015ZBWIPPAZX_65_255        SETUP     16#F3 /oacute\n
 SP06164020ZBWIPPAZX_65_255        SETUP     16#F4 /ocircumflex\n
 SP06165015ZBWIPPAZX_65_255        SETUP     16#F5 /otilde\n
 SP06166018ZBWIPPAZX_65_255        SETUP     16#F6 /odieresis\n
 SP06167015ZBWIPPAZX_65_255        SETUP     16#F7 /divide\n
 SP06168015ZBWIPPAZX_65_255        SETUP     16#F8 /oslash\n
 SP06169015ZBWIPPAZX_65_255        SETUP     16#F9 /ugrave\n
 SP06170015ZBWIPPAZX_65_255        SETUP     16#FA /uacute\n
 SP06171020ZBWIPPAZX_65_255        SETUP     16#FB /ucircumflex\n
 SP06172018ZBWIPPAZX_65_255        SETUP     16#FC /udieresis\n
 SP06173015ZBWIPPAZX_65_255        SETUP     16#FD /yacute\n
 SP06174014ZBWIPPAZX_65_255        SETUP     16#FE /thorn\n
 SP06175018ZBWIPPAZX_65_255        SETUP     16#FF /ydieresis\n
 SP06176014ZBWIPPAZX_65_255        SETUP     /upd 250 def\n
 SP06177014ZBWIPPAZX_65_255        SETUP     /acd 120 def\n
 SP06178017ZBWIPPAZX_65_255        SETUP     %%INSERTBARCODE\n
 SP06179039ZBWIPPAZX_65_255        SETUP     counttomark array astore exch pop def\n
 SP06180055ZBWIPPAZX_65_255        SETUP     % utility functions used by list printer driver POST:\n
 SP06181021ZBWIPPAZX_65_255        SETUP     /PrintModeSimplex {\n
 SP06182021ZBWIPPAZX_65_255        SETUP       <</Duplex false>>\n
 SP06183017ZBWIPPAZX_65_255        SETUP       setpagedevice\n
 SP06184007ZBWIPPAZX_65_255        SETUP     } def\n
 SP06185020ZBWIPPAZX_65_255        SETUP     /PrintModeDuplex {\n
 SP06186034ZBWIPPAZX_65_255        SETUP       <</Duplex true /Tumble false>>\n
 SP06187017ZBWIPPAZX_65_255        SETUP       setpagedevice\n
 SP06188007ZBWIPPAZX_65_255        SETUP     } def\n
 SP06189026ZBWIPPAZX_65_255        SETUP     /PrintModeTumbleDuplex {\n
 SP06190033ZBWIPPAZX_65_255        SETUP       <</Duplex true /Tumble true>>\n
 SP06191017ZBWIPPAZX_65_255        SETUP       setpagedevice\n
 SP06192007ZBWIPPAZX_65_255        SETUP     } def\n
 SP06193013ZBWIPPAZX_65_255        SETUP     /InputTray1 {
 SP06194053ZBWIPPAZX_65_255        SETUP       <</DeferredMediaSelection true /MediaPosition 0>>\n
 SP06195017ZBWIPPAZX_65_255        SETUP       setpagedevice\n
 SP06196007ZBWIPPAZX_65_255        SETUP     } def\n
 SP06197013ZBWIPPAZX_65_255        SETUP     /InputTray2 {
 SP06198053ZBWIPPAZX_65_255        SETUP       <</DeferredMediaSelection true /MediaPosition 1>>\n
 SP06199017ZBWIPPAZX_65_255        SETUP       setpagedevice\n
 SP06200007ZBWIPPAZX_65_255        SETUP     } def\n
 SP06201013ZBWIPPAZX_65_255        SETUP     /InputTray3 {
 SP06202053ZBWIPPAZX_65_255        SETUP       <</DeferredMediaSelection true /MediaPosition 2>>\n
 SP06203017ZBWIPPAZX_65_255        SETUP       setpagedevice\n
 SP06204007ZBWIPPAZX_65_255        SETUP     } def\n
 SP06205015ZBWIPPAZX_65_255        SETUP     /InputTrayMan {
 SP06206053ZBWIPPAZX_65_255        SETUP       <</DeferredMediaSelection true /ManualFeed true>>\n
 SP06207017ZBWIPPAZX_65_255        SETUP       setpagedevice\n
 SP06208007ZBWIPPAZX_65_255        SETUP     } def\n
 SP06209013ZBWIPPAZX_65_255        SETUP     %%EndProlog\n
 SP06210027ZBWIPPAZX_65_255        SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06211027ZBWIPPAZX_65_255        SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06212026ZBWIPPAZX_65_255        SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06213026ZBWIPPAZX_65_255        SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06214000ZBWIPPAZX_65_255        SETUP
 SP06001015ZBWIPPAZX_65_255        STRTPAGE  %%GOTOBARCODE\n
 SP1DX_65_80         ANY     PL0008000065SAP         1998040711022440C BIN     SAP         1997081214014140A BIN     SAP
 SP1XX_65_80         M000000000000000000000000
 SP06001006ZBWIPPAZX_65_80         CONTROL     2 \n
 SP06002072ZBWIPPAZX_65_80         CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZX_65_80         CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZX_65_80         CONTROL                                                                         \n
 SP06001002ZBWIPPAZX_65_80         ENDLINE   \n
 SP06001011ZBWIPPAZX_65_80         ENDPAGE   # no action
 SP06001022ZBWIPPAZX_65_80         LEAVE     # CTRL-D to finish job
 SP06002005ZBWIPPAZX_65_80         LEAVE     \0x04
 SP06001007ZBWIPPAZX_65_80         SETUP     %!PS-\n
 SP06002029ZBWIPPAZX_65_80         SETUP     %%Creator: SAP R/3 rel.4.0C\n
 SP06003015ZBWIPPAZX_65_80         SETUP     %%EndComments\n
 SP06004022ZBWIPPAZX_65_80         SETUP     /SAPdict 12 dict def\n
 SP06005012ZBWIPPAZX_65_80         SETUP     /SAPencode\n
 SP06006017ZBWIPPAZX_65_80         SETUP     { SAPdict begin\n
 SP06007026ZBWIPPAZX_65_80         SETUP       /basefontname exch def\n
 SP06008025ZBWIPPAZX_65_80         SETUP       /SAPfontname exch def\n
 SP06009043ZBWIPPAZX_65_80         SETUP       /basefontdict basefontname findfont def\n
 SP06010049ZBWIPPAZX_65_80         SETUP       /SAPfont      basefontdict maxlength dict def\n
 SP06011016ZBWIPPAZX_65_80         SETUP       basefontdict\n
 SP06012022ZBWIPPAZX_65_80         SETUP       { exch dup /FID ne\n
 SP06013024ZBWIPPAZX_65_80         SETUP         { dup /Encoding eq\n
 SP06014059ZBWIPPAZX_65_80         SETUP           { exch dup length array copy SAPfont 3 1 roll put }\n
 SP06015037ZBWIPPAZX_65_80         SETUP           { exch SAPfont 3 1 roll put }\n
 SP06016016ZBWIPPAZX_65_80         SETUP           ifelse }\n
 SP06017017ZBWIPPAZX_65_80         SETUP         { pop pop }\n
 SP06018014ZBWIPPAZX_65_80         SETUP         ifelse }\n
 SP06019010ZBWIPPAZX_65_80         SETUP       forall\n
 SP06020037ZBWIPPAZX_65_80         SETUP       SAPfont /FontName SAPfontname put\n
 SP06021022ZBWIPPAZX_65_80         SETUP       SAPcodes aload pop\n
 SP06022026ZBWIPPAZX_65_80         SETUP       SAPcodes length 2 idiv\n
 SP06023051ZBWIPPAZX_65_80         SETUP         { SAPfont /Encoding get 3 1 roll put } repeat\n
 SP06024040ZBWIPPAZX_65_80         SETUP         SAPfontname SAPfont definefont pop\n
 SP06025011ZBWIPPAZX_65_80         SETUP     end } def\n
 SP06026016ZBWIPPAZX_65_80         SETUP     /SAPcodes mark\n
 SP06027014ZBWIPPAZX_65_80         SETUP     16#20 /space\n
 SP06028015ZBWIPPAZX_65_80         SETUP     16#21 /exclam\n
 SP06029017ZBWIPPAZX_65_80         SETUP     16#22 /quotedbl\n
 SP06030019ZBWIPPAZX_65_80         SETUP     16#23 /numbersign\n
 SP06031015ZBWIPPAZX_65_80         SETUP     16#24 /dollar\n
 SP06032016ZBWIPPAZX_65_80         SETUP     16#25 /percent\n
 SP06033018ZBWIPPAZX_65_80         SETUP     16#26 /ampersand\n
 SP06034019ZBWIPPAZX_65_80         SETUP     16#27 /quoteright\n
 SP06035018ZBWIPPAZX_65_80         SETUP     16#28 /parenleft\n
 SP06036019ZBWIPPAZX_65_80         SETUP     16#29 /parenright\n
 SP06037017ZBWIPPAZX_65_80         SETUP     16#2A /asterisk\n
 SP06038013ZBWIPPAZX_65_80         SETUP     16#2B /plus\n
 SP06039014ZBWIPPAZX_65_80         SETUP     16#2C /comma\n
 SP06040015ZBWIPPAZX_65_80         SETUP     16#2D /hyphen\n
 SP06041015ZBWIPPAZX_65_80         SETUP     16#2E /period\n
 SP06042014ZBWIPPAZX_65_80         SETUP     16#2F /slash\n
 SP06043013ZBWIPPAZX_65_80         SETUP     16#30 /zero\n
 SP06044012ZBWIPPAZX_65_80         SETUP     16#31 /one\n
 SP06045012ZBWIPPAZX_65_80         SETUP     16#32 /two\n
 SP06046014ZBWIPPAZX_65_80         SETUP     16#33 /three\n
 SP06047013ZBWIPPAZX_65_80         SETUP     16#34 /four\n
 SP06048013ZBWIPPAZX_65_80         SETUP     16#35 /five\n
 SP06049012ZBWIPPAZX_65_80         SETUP     16#36 /six\n
 SP06050014ZBWIPPAZX_65_80         SETUP     16#37 /seven\n
 SP06051014ZBWIPPAZX_65_80         SETUP     16#38 /eight\n
 SP06052013ZBWIPPAZX_65_80         SETUP     16#39 /nine\n
 SP06053014ZBWIPPAZX_65_80         SETUP     16#3A /colon\n
 SP06054018ZBWIPPAZX_65_80         SETUP     16#3B /semicolon\n
 SP06055013ZBWIPPAZX_65_80         SETUP     16#3C /less\n
 SP06056014ZBWIPPAZX_65_80         SETUP     16#3D /equal\n
 SP06057016ZBWIPPAZX_65_80         SETUP     16#3E /greater\n
 SP06058017ZBWIPPAZX_65_80         SETUP     16#3F /question\n
 SP06059011ZBWIPPAZX_65_80         SETUP     16#40 /at\n
 SP06060070ZBWIPPAZX_65_80         SETUP     16#41 /A  16#42 /B  16#43 /C  16#44 /D  16#45 /E  16#46 /F  16#47 /G\n
 SP06061070ZBWIPPAZX_65_80         SETUP     16#48 /H  16#49 /I  16#4A /J  16#4B /K  16#4C /L  16#4D /M  16#4E /N\n
 SP06062070ZBWIPPAZX_65_80         SETUP     16#4F /O  16#50 /P  16#51 /Q  16#52 /R  16#53 /S  16#54 /T  16#55 /U\n
 SP06063050ZBWIPPAZX_65_80         SETUP     16#56 /V  16#57 /W  16#58 /X  16#59 /Y  16#5A /Z\n
 SP06064020ZBWIPPAZX_65_80         SETUP     16#5B /bracketleft\n
 SP06065018ZBWIPPAZX_65_80         SETUP     16#5C /backslash\n
 SP06066021ZBWIPPAZX_65_80         SETUP     16#5D /bracketright\n
 SP06067020ZBWIPPAZX_65_80         SETUP     16#5E /asciicircum\n
 SP06068019ZBWIPPAZX_65_80         SETUP     16#5F /underscore\n
 SP06069018ZBWIPPAZX_65_80         SETUP     16#60 /quoteleft\n
 SP06070070ZBWIPPAZX_65_80         SETUP     16#61 /a  16#62 /b  16#63 /c  16#64 /d  16#65 /e  16#66 /f  16#67 /g\n
 SP06071070ZBWIPPAZX_65_80         SETUP     16#68 /h  16#69 /i  16#6A /j  16#6B /k  16#6C /l  16#6D /m  16#6E /n\n
 SP06072070ZBWIPPAZX_65_80         SETUP     16#6F /o  16#70 /p  16#71 /q  16#72 /r  16#73 /s  16#74 /t  16#75 /u\n
 SP06073050ZBWIPPAZX_65_80         SETUP     16#76 /v  16#77 /w  16#78 /x  16#79 /y  16#7A /z\n
 SP06074018ZBWIPPAZX_65_80         SETUP     16#7B /braceleft\n
 SP06075012ZBWIPPAZX_65_80         SETUP     16#7C /bar\n
 SP06076019ZBWIPPAZX_65_80         SETUP     16#7D /braceright\n
 SP06077019ZBWIPPAZX_65_80         SETUP     16#7E /asciitilde\n
 SP06078066ZBWIPPAZX_65_80         SETUP     16#80 /grave  16#81 /acute    16#82 /circumflex     16#83 /tilde\n
 SP06079069ZBWIPPAZX_65_80         SETUP     16#84 /ogonek 16#85 /breve    16#86 /dotaccent      16#87 /dieresis\n
 SP06080066ZBWIPPAZX_65_80         SETUP     16#88 /ring   16#89 /cedilla  16#8A /hungarumlaut   16#8B /caron\n
 SP06081019ZBWIPPAZX_65_80         SETUP     16#A1 /exclamdown\n
 SP06082013ZBWIPPAZX_65_80         SETUP     16#A2 /cent\n
 SP06083017ZBWIPPAZX_65_80         SETUP     16#A3 /sterling\n
 SP06084017ZBWIPPAZX_65_80         SETUP     16#A4 /currency\n
 SP06085012ZBWIPPAZX_65_80         SETUP     16#A5 /yen\n
 SP06086018ZBWIPPAZX_65_80         SETUP     16#A6 /brokenbar\n
 SP06087016ZBWIPPAZX_65_80         SETUP     16#A7 /section\n
 SP06088017ZBWIPPAZX_65_80         SETUP     16#A8 /dieresis\n
 SP06089018ZBWIPPAZX_65_80         SETUP     16#A9 /copyright\n
 SP06090020ZBWIPPAZX_65_80         SETUP     16#AA /ordfeminine\n
 SP06091022ZBWIPPAZX_65_80         SETUP     16#AB /guillemotleft\n
 SP06092019ZBWIPPAZX_65_80         SETUP     16#AC /logicalnot\n
 SP06093014ZBWIPPAZX_65_80         SETUP     16#AD /minus\n
 SP06094019ZBWIPPAZX_65_80         SETUP     16#AE /registered\n
 SP06095015ZBWIPPAZX_65_80         SETUP     16#AF /macron\n
 SP06096015ZBWIPPAZX_65_80         SETUP     16#B0 /degree\n
 SP06097018ZBWIPPAZX_65_80         SETUP     16#B1 /plusminus\n
 SP06098020ZBWIPPAZX_65_80         SETUP     16#B2 /twosuperior\n
 SP06099022ZBWIPPAZX_65_80         SETUP     16#B3 /threesuperior\n
 SP06100020ZBWIPPAZX_65_80         SETUP     16#B4 /quotesingle\n
 SP06101011ZBWIPPAZX_65_80         SETUP     16#B5 /mu\n
 SP06102018ZBWIPPAZX_65_80         SETUP     16#B6 /paragraph\n
 SP06103023ZBWIPPAZX_65_80         SETUP     16#B7 /periodcentered\n
 SP06104016ZBWIPPAZX_65_80         SETUP     16#B8 /cedilla\n
 SP06105020ZBWIPPAZX_65_80         SETUP     16#B9 /onesuperior\n
 SP06106021ZBWIPPAZX_65_80         SETUP     16#BA /ordmasculine\n
 SP06107023ZBWIPPAZX_65_80         SETUP     16#BB /guillemotright\n
 SP06108019ZBWIPPAZX_65_80         SETUP     16#BC /onequarter\n
 SP06109016ZBWIPPAZX_65_80         SETUP     16#BD /onehalf\n
 SP06110022ZBWIPPAZX_65_80         SETUP     16#BE /threequarters\n
 SP06111021ZBWIPPAZX_65_80         SETUP     16#BF /questiondown\n
 SP06112015ZBWIPPAZX_65_80         SETUP     16#C0 /Agrave\n
 SP06113015ZBWIPPAZX_65_80         SETUP     16#C1 /Aacute\n
 SP06114020ZBWIPPAZX_65_80         SETUP     16#C2 /Acircumflex\n
 SP06115015ZBWIPPAZX_65_80         SETUP     16#C3 /Atilde\n
 SP06116018ZBWIPPAZX_65_80         SETUP     16#C4 /Adieresis\n
 SP06117014ZBWIPPAZX_65_80         SETUP     16#C5 /Aring\n
 SP06118011ZBWIPPAZX_65_80         SETUP     16#C6 /AE\n
 SP06119017ZBWIPPAZX_65_80         SETUP     16#C7 /Ccedilla\n
 SP06120015ZBWIPPAZX_65_80         SETUP     16#C8 /Egrave\n
 SP06121015ZBWIPPAZX_65_80         SETUP     16#C9 /Eacute\n
 SP06122020ZBWIPPAZX_65_80         SETUP     16#CA /Ecircumflex\n
 SP06123018ZBWIPPAZX_65_80         SETUP     16#CB /Edieresis\n
 SP06124015ZBWIPPAZX_65_80         SETUP     16#CC /Igrave\n
 SP06125015ZBWIPPAZX_65_80         SETUP     16#CD /Iacute\n
 SP06126020ZBWIPPAZX_65_80         SETUP     16#CE /Icircumflex\n
 SP06127018ZBWIPPAZX_65_80         SETUP     16#CF /Idieresis\n
 SP06128012ZBWIPPAZX_65_80         SETUP     16#D0 /Eth\n
 SP06129015ZBWIPPAZX_65_80         SETUP     16#D1 /Ntilde\n
 SP06130015ZBWIPPAZX_65_80         SETUP     16#D2 /Ograve\n
 SP06131015ZBWIPPAZX_65_80         SETUP     16#D3 /Oacute\n
 SP06132020ZBWIPPAZX_65_80         SETUP     16#D4 /Ocircumflex\n
 SP06133015ZBWIPPAZX_65_80         SETUP     16#D5 /Otilde\n
 SP06134018ZBWIPPAZX_65_80         SETUP     16#D6 /Odieresis\n
 SP06135017ZBWIPPAZX_65_80         SETUP     16#D7 /multiply\n
 SP06136015ZBWIPPAZX_65_80         SETUP     16#D8 /Oslash\n
 SP06137015ZBWIPPAZX_65_80         SETUP     16#D9 /Ugrave\n
 SP06138015ZBWIPPAZX_65_80         SETUP     16#DA /Uacute\n
 SP06139020ZBWIPPAZX_65_80         SETUP     16#DB /Ucircumflex\n
 SP06140018ZBWIPPAZX_65_80         SETUP     16#DC /Udieresis\n
 SP06141015ZBWIPPAZX_65_80         SETUP     16#DD /Yacute\n
 SP06142014ZBWIPPAZX_65_80         SETUP     16#DE /Thorn\n
 SP06143019ZBWIPPAZX_65_80         SETUP     16#DF /germandbls\n
 SP06144015ZBWIPPAZX_65_80         SETUP     16#E0 /agrave\n
 SP06145015ZBWIPPAZX_65_80         SETUP     16#E1 /aacute\n
 SP06146020ZBWIPPAZX_65_80         SETUP     16#E2 /acircumflex\n
 SP06147015ZBWIPPAZX_65_80         SETUP     16#E3 /atilde\n
 SP06148018ZBWIPPAZX_65_80         SETUP     16#E4 /adieresis\n
 SP06149014ZBWIPPAZX_65_80         SETUP     16#E5 /aring\n
 SP06150011ZBWIPPAZX_65_80         SETUP     16#E6 /ae\n
 SP06151017ZBWIPPAZX_65_80         SETUP     16#E7 /ccedilla\n
 SP06152015ZBWIPPAZX_65_80         SETUP     16#E8 /egrave\n
 SP06153015ZBWIPPAZX_65_80         SETUP     16#E9 /eacute\n
 SP06154020ZBWIPPAZX_65_80         SETUP     16#EA /ecircumflex\n
 SP06155018ZBWIPPAZX_65_80         SETUP     16#EB /edieresis\n
 SP06156015ZBWIPPAZX_65_80         SETUP     16#EC /igrave\n
 SP06157015ZBWIPPAZX_65_80         SETUP     16#ED /iacute\n
 SP06158020ZBWIPPAZX_65_80         SETUP     16#EE /icircumflex\n
 SP06159018ZBWIPPAZX_65_80         SETUP     16#EF /idieresis\n
 SP06160012ZBWIPPAZX_65_80         SETUP     16#F0 /eth\n
 SP06161015ZBWIPPAZX_65_80         SETUP     16#F1 /ntilde\n
 SP06162015ZBWIPPAZX_65_80         SETUP     16#F2 /ograve\n
 SP06163015ZBWIPPAZX_65_80         SETUP     16#F3 /oacute\n
 SP06164020ZBWIPPAZX_65_80         SETUP     16#F4 /ocircumflex\n
 SP06165015ZBWIPPAZX_65_80         SETUP     16#F5 /otilde\n
 SP06166018ZBWIPPAZX_65_80         SETUP     16#F6 /odieresis\n
 SP06167015ZBWIPPAZX_65_80         SETUP     16#F7 /divide\n
 SP06168015ZBWIPPAZX_65_80         SETUP     16#F8 /oslash\n
 SP06169015ZBWIPPAZX_65_80         SETUP     16#F9 /ugrave\n
 SP06170015ZBWIPPAZX_65_80         SETUP     16#FA /uacute\n
 SP06171020ZBWIPPAZX_65_80         SETUP     16#FB /ucircumflex\n
 SP06172018ZBWIPPAZX_65_80         SETUP     16#FC /udieresis\n
 SP06173015ZBWIPPAZX_65_80         SETUP     16#FD /yacute\n
 SP06174014ZBWIPPAZX_65_80         SETUP     16#FE /thorn\n
 SP06175018ZBWIPPAZX_65_80         SETUP     16#FF /ydieresis\n
 SP06176039ZBWIPPAZX_65_80         SETUP     counttomark array astore exch pop def\n
 SP06177055ZBWIPPAZX_65_80         SETUP     % utility functions used by list printer driver POST:\n
 SP06178021ZBWIPPAZX_65_80         SETUP     /PrintModeSimplex {\n
 SP06179021ZBWIPPAZX_65_80         SETUP       <</Duplex false>>\n
 SP06180017ZBWIPPAZX_65_80         SETUP       setpagedevice\n
 SP06181007ZBWIPPAZX_65_80         SETUP     } def\n
 SP06182020ZBWIPPAZX_65_80         SETUP     /PrintModeDuplex {\n
 SP06183034ZBWIPPAZX_65_80         SETUP       <</Duplex true /Tumble false>>\n
 SP06184017ZBWIPPAZX_65_80         SETUP       setpagedevice\n
 SP06185007ZBWIPPAZX_65_80         SETUP     } def\n
 SP06186026ZBWIPPAZX_65_80         SETUP     /PrintModeTumbleDuplex {\n
 SP06187033ZBWIPPAZX_65_80         SETUP       <</Duplex true /Tumble true>>\n
 SP06188017ZBWIPPAZX_65_80         SETUP       setpagedevice\n
 SP06189007ZBWIPPAZX_65_80         SETUP     } def\n
 SP06190013ZBWIPPAZX_65_80         SETUP     /InputTray1 {
 SP06191053ZBWIPPAZX_65_80         SETUP       <</DeferredMediaSelection true /MediaPosition 0>>\n
 SP06192017ZBWIPPAZX_65_80         SETUP       setpagedevice\n
 SP06193007ZBWIPPAZX_65_80         SETUP     } def\n
 SP06194013ZBWIPPAZX_65_80         SETUP     /InputTray2 {
 SP06195053ZBWIPPAZX_65_80         SETUP       <</DeferredMediaSelection true /MediaPosition 1>>\n
 SP06196017ZBWIPPAZX_65_80         SETUP       setpagedevice\n
 SP06197007ZBWIPPAZX_65_80         SETUP     } def\n
 SP06198013ZBWIPPAZX_65_80         SETUP     /InputTray3 {
 SP06199053ZBWIPPAZX_65_80         SETUP       <</DeferredMediaSelection true /MediaPosition 2>>\n
 SP06200017ZBWIPPAZX_65_80         SETUP       setpagedevice\n
 SP06201007ZBWIPPAZX_65_80         SETUP     } def\n
 SP06202015ZBWIPPAZX_65_80         SETUP     /InputTrayMan {
 SP06203053ZBWIPPAZX_65_80         SETUP       <</DeferredMediaSelection true /ManualFeed true>>\n
 SP06204017ZBWIPPAZX_65_80         SETUP       setpagedevice\n
 SP06205007ZBWIPPAZX_65_80         SETUP     } def\n
 SP06206013ZBWIPPAZX_65_80         SETUP     %%EndProlog\n
 SP06207027ZBWIPPAZX_65_80         SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06208027ZBWIPPAZX_65_80         SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06209026ZBWIPPAZX_65_80         SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06210026ZBWIPPAZX_65_80         SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06211000ZBWIPPAZX_65_80         SETUP
 SP1DX_90_120        ANY     PL0012000090SAP         1998122813075346A BIN     SAP         1998040711023740C BIN     SAP         1997081214022440A BIN
 SP1XX_90_120        M000000000000000000000000
 SP06001006ZBWIPPAZX_90_120        CONTROL     2 \n
 SP06002072ZBWIPPAZX_90_120        CONTROL   DEVELOPER   101118N4S 700 DEVELOPER   101001N4S 700 DEVELOPER   101001\n
 SP06003072ZBWIPPAZX_90_120        CONTROL     0000                                                                \n
 SP06004072ZBWIPPAZX_90_120        CONTROL                                                                         \n
 SP06001002ZBWIPPAZX_90_120        ENDLINE   \n
 SP06001011ZBWIPPAZX_90_120        ENDPAGE   # no action
 SP06001022ZBWIPPAZX_90_120        LEAVE     # CTRL-D to finish job
 SP06002005ZBWIPPAZX_90_120        LEAVE     \0x04
 SP06001007ZBWIPPAZX_90_120        SETUP     %!PS-\n
 SP06002029ZBWIPPAZX_90_120        SETUP     %%Creator: SAP R/3 rel.4.0C\n
 SP06003015ZBWIPPAZX_90_120        SETUP     %%EndComments\n
 SP06004022ZBWIPPAZX_90_120        SETUP     /SAPdict 12 dict def\n
 SP06005012ZBWIPPAZX_90_120        SETUP     /SAPencode\n
 SP06006017ZBWIPPAZX_90_120        SETUP     { SAPdict begin\n
 SP06007026ZBWIPPAZX_90_120        SETUP       /basefontname exch def\n
 SP06008025ZBWIPPAZX_90_120        SETUP       /SAPfontname exch def\n
 SP06009043ZBWIPPAZX_90_120        SETUP       /basefontdict basefontname findfont def\n
 SP06010049ZBWIPPAZX_90_120        SETUP       /SAPfont      basefontdict maxlength dict def\n
 SP06011016ZBWIPPAZX_90_120        SETUP       basefontdict\n
 SP06012022ZBWIPPAZX_90_120        SETUP       { exch dup /FID ne\n
 SP06013024ZBWIPPAZX_90_120        SETUP         { dup /Encoding eq\n
 SP06014059ZBWIPPAZX_90_120        SETUP           { exch dup length array copy SAPfont 3 1 roll put }\n
 SP06015037ZBWIPPAZX_90_120        SETUP           { exch SAPfont 3 1 roll put }\n
 SP06016016ZBWIPPAZX_90_120        SETUP           ifelse }\n
 SP06017017ZBWIPPAZX_90_120        SETUP         { pop pop }\n
 SP06018014ZBWIPPAZX_90_120        SETUP         ifelse }\n
 SP06019010ZBWIPPAZX_90_120        SETUP       forall\n
 SP06020037ZBWIPPAZX_90_120        SETUP       SAPfont /FontName SAPfontname put\n
 SP06021022ZBWIPPAZX_90_120        SETUP       SAPcodes aload pop\n
 SP06022026ZBWIPPAZX_90_120        SETUP       SAPcodes length 2 idiv\n
 SP06023051ZBWIPPAZX_90_120        SETUP         { SAPfont /Encoding get 3 1 roll put } repeat\n
 SP06024040ZBWIPPAZX_90_120        SETUP         SAPfontname SAPfont definefont pop\n
 SP06025011ZBWIPPAZX_90_120        SETUP     end } def\n
 SP06026016ZBWIPPAZX_90_120        SETUP     /SAPcodes mark\n
 SP06027014ZBWIPPAZX_90_120        SETUP     16#20 /space\n
 SP06028015ZBWIPPAZX_90_120        SETUP     16#21 /exclam\n
 SP06029017ZBWIPPAZX_90_120        SETUP     16#22 /quotedbl\n
 SP06030019ZBWIPPAZX_90_120        SETUP     16#23 /numbersign\n
 SP06031015ZBWIPPAZX_90_120        SETUP     16#24 /dollar\n
 SP06032016ZBWIPPAZX_90_120        SETUP     16#25 /percent\n
 SP06033018ZBWIPPAZX_90_120        SETUP     16#26 /ampersand\n
 SP06034019ZBWIPPAZX_90_120        SETUP     16#27 /quoteright\n
 SP06035018ZBWIPPAZX_90_120        SETUP     16#28 /parenleft\n
 SP06036019ZBWIPPAZX_90_120        SETUP     16#29 /parenright\n
 SP06037017ZBWIPPAZX_90_120        SETUP     16#2A /asterisk\n
 SP06038013ZBWIPPAZX_90_120        SETUP     16#2B /plus\n
 SP06039014ZBWIPPAZX_90_120        SETUP     16#2C /comma\n
 SP06040015ZBWIPPAZX_90_120        SETUP     16#2D /hyphen\n
 SP06041015ZBWIPPAZX_90_120        SETUP     16#2E /period\n
 SP06042014ZBWIPPAZX_90_120        SETUP     16#2F /slash\n
 SP06043013ZBWIPPAZX_90_120        SETUP     16#30 /zero\n
 SP06044012ZBWIPPAZX_90_120        SETUP     16#31 /one\n
 SP06045012ZBWIPPAZX_90_120        SETUP     16#32 /two\n
 SP06046014ZBWIPPAZX_90_120        SETUP     16#33 /three\n
 SP06047013ZBWIPPAZX_90_120        SETUP     16#34 /four\n
 SP06048013ZBWIPPAZX_90_120        SETUP     16#35 /five\n
 SP06049012ZBWIPPAZX_90_120        SETUP     16#36 /six\n
 SP06050014ZBWIPPAZX_90_120        SETUP     16#37 /seven\n
 SP06051014ZBWIPPAZX_90_120        SETUP     16#38 /eight\n
 SP06052013ZBWIPPAZX_90_120        SETUP     16#39 /nine\n
 SP06053014ZBWIPPAZX_90_120        SETUP     16#3A /colon\n
 SP06054018ZBWIPPAZX_90_120        SETUP     16#3B /semicolon\n
 SP06055013ZBWIPPAZX_90_120        SETUP     16#3C /less\n
 SP06056014ZBWIPPAZX_90_120        SETUP     16#3D /equal\n
 SP06057016ZBWIPPAZX_90_120        SETUP     16#3E /greater\n
 SP06058017ZBWIPPAZX_90_120        SETUP     16#3F /question\n
 SP06059011ZBWIPPAZX_90_120        SETUP     16#40 /at\n
 SP06060070ZBWIPPAZX_90_120        SETUP     16#41 /A  16#42 /B  16#43 /C  16#44 /D  16#45 /E  16#46 /F  16#47 /G\n
 SP06061070ZBWIPPAZX_90_120        SETUP     16#48 /H  16#49 /I  16#4A /J  16#4B /K  16#4C /L  16#4D /M  16#4E /N\n
 SP06062070ZBWIPPAZX_90_120        SETUP     16#4F /O  16#50 /P  16#51 /Q  16#52 /R  16#53 /S  16#54 /T  16#55 /U\n
 SP06063050ZBWIPPAZX_90_120        SETUP     16#56 /V  16#57 /W  16#58 /X  16#59 /Y  16#5A /Z\n
 SP06064020ZBWIPPAZX_90_120        SETUP     16#5B /bracketleft\n
 SP06065018ZBWIPPAZX_90_120        SETUP     16#5C /backslash\n
 SP06066021ZBWIPPAZX_90_120        SETUP     16#5D /bracketright\n
 SP06067020ZBWIPPAZX_90_120        SETUP     16#5E /asciicircum\n
 SP06068019ZBWIPPAZX_90_120        SETUP     16#5F /underscore\n
 SP06069018ZBWIPPAZX_90_120        SETUP     16#60 /quoteleft\n
 SP06070070ZBWIPPAZX_90_120        SETUP     16#61 /a  16#62 /b  16#63 /c  16#64 /d  16#65 /e  16#66 /f  16#67 /g\n
 SP06071070ZBWIPPAZX_90_120        SETUP     16#68 /h  16#69 /i  16#6A /j  16#6B /k  16#6C /l  16#6D /m  16#6E /n\n
 SP06072070ZBWIPPAZX_90_120        SETUP     16#6F /o  16#70 /p  16#71 /q  16#72 /r  16#73 /s  16#74 /t  16#75 /u\n
 SP06073050ZBWIPPAZX_90_120        SETUP     16#76 /v  16#77 /w  16#78 /x  16#79 /y  16#7A /z\n
 SP06074018ZBWIPPAZX_90_120        SETUP     16#7B /braceleft\n
 SP06075012ZBWIPPAZX_90_120        SETUP     16#7C /bar\n
 SP06076019ZBWIPPAZX_90_120        SETUP     16#7D /braceright\n
 SP06077019ZBWIPPAZX_90_120        SETUP     16#7E /asciitilde\n
 SP06078066ZBWIPPAZX_90_120        SETUP     16#80 /grave  16#81 /acute    16#82 /circumflex     16#83 /tilde\n
 SP06079069ZBWIPPAZX_90_120        SETUP     16#84 /ogonek 16#85 /breve    16#86 /dotaccent      16#87 /dieresis\n
 SP06080066ZBWIPPAZX_90_120        SETUP     16#88 /ring   16#89 /cedilla  16#8A /hungarumlaut   16#8B /caron\n
 SP06081019ZBWIPPAZX_90_120        SETUP     16#A1 /exclamdown\n
 SP06082013ZBWIPPAZX_90_120        SETUP     16#A2 /cent\n
 SP06083017ZBWIPPAZX_90_120        SETUP     16#A3 /sterling\n
 SP06084017ZBWIPPAZX_90_120        SETUP     16#A4 /currency\n
 SP06085012ZBWIPPAZX_90_120        SETUP     16#A5 /yen\n
 SP06086018ZBWIPPAZX_90_120        SETUP     16#A6 /brokenbar\n
 SP06087016ZBWIPPAZX_90_120        SETUP     16#A7 /section\n
 SP06088017ZBWIPPAZX_90_120        SETUP     16#A8 /dieresis\n
 SP06089018ZBWIPPAZX_90_120        SETUP     16#A9 /copyright\n
 SP06090020ZBWIPPAZX_90_120        SETUP     16#AA /ordfeminine\n
 SP06091022ZBWIPPAZX_90_120        SETUP     16#AB /guillemotleft\n
 SP06092019ZBWIPPAZX_90_120        SETUP     16#AC /logicalnot\n
 SP06093014ZBWIPPAZX_90_120        SETUP     16#AD /minus\n
 SP06094019ZBWIPPAZX_90_120        SETUP     16#AE /registered\n
 SP06095015ZBWIPPAZX_90_120        SETUP     16#AF /macron\n
 SP06096015ZBWIPPAZX_90_120        SETUP     16#B0 /degree\n
 SP06097018ZBWIPPAZX_90_120        SETUP     16#B1 /plusminus\n
 SP06098020ZBWIPPAZX_90_120        SETUP     16#B2 /twosuperior\n
 SP06099022ZBWIPPAZX_90_120        SETUP     16#B3 /threesuperior\n
 SP06100020ZBWIPPAZX_90_120        SETUP     16#B4 /quotesingle\n
 SP06101011ZBWIPPAZX_90_120        SETUP     16#B5 /mu\n
 SP06102018ZBWIPPAZX_90_120        SETUP     16#B6 /paragraph\n
 SP06103023ZBWIPPAZX_90_120        SETUP     16#B7 /periodcentered\n
 SP06104016ZBWIPPAZX_90_120        SETUP     16#B8 /cedilla\n
 SP06105020ZBWIPPAZX_90_120        SETUP     16#B9 /onesuperior\n
 SP06106021ZBWIPPAZX_90_120        SETUP     16#BA /ordmasculine\n
 SP06107023ZBWIPPAZX_90_120        SETUP     16#BB /guillemotright\n
 SP06108019ZBWIPPAZX_90_120        SETUP     16#BC /onequarter\n
 SP06109016ZBWIPPAZX_90_120        SETUP     16#BD /onehalf\n
 SP06110022ZBWIPPAZX_90_120        SETUP     16#BE /threequarters\n
 SP06111021ZBWIPPAZX_90_120        SETUP     16#BF /questiondown\n
 SP06112015ZBWIPPAZX_90_120        SETUP     16#C0 /Agrave\n
 SP06113015ZBWIPPAZX_90_120        SETUP     16#C1 /Aacute\n
 SP06114020ZBWIPPAZX_90_120        SETUP     16#C2 /Acircumflex\n
 SP06115015ZBWIPPAZX_90_120        SETUP     16#C3 /Atilde\n
 SP06116018ZBWIPPAZX_90_120        SETUP     16#C4 /Adieresis\n
 SP06117014ZBWIPPAZX_90_120        SETUP     16#C5 /Aring\n
 SP06118011ZBWIPPAZX_90_120        SETUP     16#C6 /AE\n
 SP06119017ZBWIPPAZX_90_120        SETUP     16#C7 /Ccedilla\n
 SP06120015ZBWIPPAZX_90_120        SETUP     16#C8 /Egrave\n
 SP06121015ZBWIPPAZX_90_120        SETUP     16#C9 /Eacute\n
 SP06122020ZBWIPPAZX_90_120        SETUP     16#CA /Ecircumflex\n
 SP06123018ZBWIPPAZX_90_120        SETUP     16#CB /Edieresis\n
 SP06124015ZBWIPPAZX_90_120        SETUP     16#CC /Igrave\n
 SP06125015ZBWIPPAZX_90_120        SETUP     16#CD /Iacute\n
 SP06126020ZBWIPPAZX_90_120        SETUP     16#CE /Icircumflex\n
 SP06127018ZBWIPPAZX_90_120        SETUP     16#CF /Idieresis\n
 SP06128012ZBWIPPAZX_90_120        SETUP     16#D0 /Eth\n
 SP06129015ZBWIPPAZX_90_120        SETUP     16#D1 /Ntilde\n
 SP06130015ZBWIPPAZX_90_120        SETUP     16#D2 /Ograve\n
 SP06131015ZBWIPPAZX_90_120        SETUP     16#D3 /Oacute\n
 SP06132020ZBWIPPAZX_90_120        SETUP     16#D4 /Ocircumflex\n
 SP06133015ZBWIPPAZX_90_120        SETUP     16#D5 /Otilde\n
 SP06134018ZBWIPPAZX_90_120        SETUP     16#D6 /Odieresis\n
 SP06135017ZBWIPPAZX_90_120        SETUP     16#D7 /multiply\n
 SP06136015ZBWIPPAZX_90_120        SETUP     16#D8 /Oslash\n
 SP06137015ZBWIPPAZX_90_120        SETUP     16#D9 /Ugrave\n
 SP06138015ZBWIPPAZX_90_120        SETUP     16#DA /Uacute\n
 SP06139020ZBWIPPAZX_90_120        SETUP     16#DB /Ucircumflex\n
 SP06140018ZBWIPPAZX_90_120        SETUP     16#DC /Udieresis\n
 SP06141015ZBWIPPAZX_90_120        SETUP     16#DD /Yacute\n
 SP06142014ZBWIPPAZX_90_120        SETUP     16#DE /Thorn\n
 SP06143019ZBWIPPAZX_90_120        SETUP     16#DF /germandbls\n
 SP06144015ZBWIPPAZX_90_120        SETUP     16#E0 /agrave\n
 SP06145015ZBWIPPAZX_90_120        SETUP     16#E1 /aacute\n
 SP06146020ZBWIPPAZX_90_120        SETUP     16#E2 /acircumflex\n
 SP06147015ZBWIPPAZX_90_120        SETUP     16#E3 /atilde\n
 SP06148018ZBWIPPAZX_90_120        SETUP     16#E4 /adieresis\n
 SP06149014ZBWIPPAZX_90_120        SETUP     16#E5 /aring\n
 SP06150011ZBWIPPAZX_90_120        SETUP     16#E6 /ae\n
 SP06151017ZBWIPPAZX_90_120        SETUP     16#E7 /ccedilla\n
 SP06152015ZBWIPPAZX_90_120        SETUP     16#E8 /egrave\n
 SP06153015ZBWIPPAZX_90_120        SETUP     16#E9 /eacute\n
 SP06154020ZBWIPPAZX_90_120        SETUP     16#EA /ecircumflex\n
 SP06155018ZBWIPPAZX_90_120        SETUP     16#EB /edieresis\n
 SP06156015ZBWIPPAZX_90_120        SETUP     16#EC /igrave\n
 SP06157015ZBWIPPAZX_90_120        SETUP     16#ED /iacute\n
 SP06158020ZBWIPPAZX_90_120        SETUP     16#EE /icircumflex\n
 SP06159018ZBWIPPAZX_90_120        SETUP     16#EF /idieresis\n
 SP06160012ZBWIPPAZX_90_120        SETUP     16#F0 /eth\n
 SP06161015ZBWIPPAZX_90_120        SETUP     16#F1 /ntilde\n
 SP06162015ZBWIPPAZX_90_120        SETUP     16#F2 /ograve\n
 SP06163015ZBWIPPAZX_90_120        SETUP     16#F3 /oacute\n
 SP06164020ZBWIPPAZX_90_120        SETUP     16#F4 /ocircumflex\n
 SP06165015ZBWIPPAZX_90_120        SETUP     16#F5 /otilde\n
 SP06166018ZBWIPPAZX_90_120        SETUP     16#F6 /odieresis\n
 SP06167015ZBWIPPAZX_90_120        SETUP     16#F7 /divide\n
 SP06168015ZBWIPPAZX_90_120        SETUP     16#F8 /oslash\n
 SP06169015ZBWIPPAZX_90_120        SETUP     16#F9 /ugrave\n
 SP06170015ZBWIPPAZX_90_120        SETUP     16#FA /uacute\n
 SP06171020ZBWIPPAZX_90_120        SETUP     16#FB /ucircumflex\n
 SP06172018ZBWIPPAZX_90_120        SETUP     16#FC /udieresis\n
 SP06173015ZBWIPPAZX_90_120        SETUP     16#FD /yacute\n
 SP06174014ZBWIPPAZX_90_120        SETUP     16#FE /thorn\n
 SP06175018ZBWIPPAZX_90_120        SETUP     16#FF /ydieresis\n
 SP06176039ZBWIPPAZX_90_120        SETUP     counttomark array astore exch pop def\n
 SP06177055ZBWIPPAZX_90_120        SETUP     % utility functions used by list printer driver POST:\n
 SP06178021ZBWIPPAZX_90_120        SETUP     /PrintModeSimplex {\n
 SP06179021ZBWIPPAZX_90_120        SETUP       <</Duplex false>>\n
 SP06180017ZBWIPPAZX_90_120        SETUP       setpagedevice\n
 SP06181007ZBWIPPAZX_90_120        SETUP     } def\n
 SP06182020ZBWIPPAZX_90_120        SETUP     /PrintModeDuplex {\n
 SP06183034ZBWIPPAZX_90_120        SETUP       <</Duplex true /Tumble false>>\n
 SP06184017ZBWIPPAZX_90_120        SETUP       setpagedevice\n
 SP06185007ZBWIPPAZX_90_120        SETUP     } def\n
 SP06186026ZBWIPPAZX_90_120        SETUP     /PrintModeTumbleDuplex {\n
 SP06187033ZBWIPPAZX_90_120        SETUP       <</Duplex true /Tumble true>>\n
 SP06188017ZBWIPPAZX_90_120        SETUP       setpagedevice\n
 SP06189007ZBWIPPAZX_90_120        SETUP     } def\n
 SP06190013ZBWIPPAZX_90_120        SETUP     /InputTray1 {
 SP06191053ZBWIPPAZX_90_120        SETUP       <</DeferredMediaSelection true /MediaPosition 0>>\n
 SP06192017ZBWIPPAZX_90_120        SETUP       setpagedevice\n
 SP06193007ZBWIPPAZX_90_120        SETUP     } def\n
 SP06194013ZBWIPPAZX_90_120        SETUP     /InputTray2 {
 SP06195053ZBWIPPAZX_90_120        SETUP       <</DeferredMediaSelection true /MediaPosition 1>>\n
 SP06196017ZBWIPPAZX_90_120        SETUP       setpagedevice\n
 SP06197007ZBWIPPAZX_90_120        SETUP     } def\n
 SP06198013ZBWIPPAZX_90_120        SETUP     /InputTray3 {
 SP06199053ZBWIPPAZX_90_120        SETUP       <</DeferredMediaSelection true /MediaPosition 2>>\n
 SP06200017ZBWIPPAZX_90_120        SETUP       setpagedevice\n
 SP06201007ZBWIPPAZX_90_120        SETUP     } def\n
 SP06202015ZBWIPPAZX_90_120        SETUP     /InputTrayMan {
 SP06203053ZBWIPPAZX_90_120        SETUP       <</DeferredMediaSelection true /ManualFeed true>>\n
 SP06204017ZBWIPPAZX_90_120        SETUP       setpagedevice\n
 SP06205007ZBWIPPAZX_90_120        SETUP     } def\n
 SP06206013ZBWIPPAZX_90_120        SETUP     %%EndProlog\n
 SP06207027ZBWIPPAZX_90_120        SETUP     \i<ZBWIPPAZ:DINA4:ZBWIPP>\n
 SP06208027ZBWIPPAZX_90_120        SETUP     \i<ZBWIPPAZ:DINA4:ZREND3>\n
 SP06209026ZBWIPPAZX_90_120        SETUP     \i<ZBWIPPAZ:DINA4:ZENC1>\n
 SP06210026ZBWIPPAZX_90_120        SETUP     \i<ZBWIPPAZ:DINA4:ZENC2>\n
 SP06211000ZBWIPPAZX_90_120        SETUP
 FO04ZBWIPPAZCOURIER 000  001sapLinkToAFM POSTSCPT COURIER 000 false false
 FO04ZBWIPPAZCOURIER 000 X001sapLinkToAFM POSTSCPT COURIER 000 false true
 FO04ZBWIPPAZCOURIER 000X 001sapLinkToAFM POSTSCPT COURIER 000 true false
 FO04ZBWIPPAZCOURIER 000XX001sapLinkToAFM POSTSCPT COURIER 000 true true
 FO04ZBWIPPAZHELVE   000  001sapLinkToAFM POSTSCPT HELVE 000 false false
 FO04ZBWIPPAZHELVE   000 X001sapLinkToAFM POSTSCPT HELVE 000 false true
 FO04ZBWIPPAZHELVE   000X 001sapLinkToAFM POSTSCPT HELVE 000 true false
 FO04ZBWIPPAZHELVE   000XX001sapLinkToAFM POSTSCPT HELVE 000 true true
 FO04ZBWIPPAZTIMES   000  001sapLinkToAFM POSTSCPT TIMES 000 false false
 FO04ZBWIPPAZTIMES   000 X001sapLinkToAFM POSTSCPT TIMES 000 false true
 FO04ZBWIPPAZTIMES   000X 001sapLinkToAFM POSTSCPT TIMES 000 true false
 FO04ZBWIPPAZTIMES   000XX001sapLinkToAFM POSTSCPT TIMES 000 true true
E
